PROMPT Crea Sinonimo a Procedimiento LDC_PROGENNOVOFERTSENSEVAESCA
BEGIN
	EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM LDC_PROGENNOVOFERTSENSEVAESCA FOR ADM_PERSON.LDC_PROGENNOVOFERTSENSEVAESCA';
END;
/