PROMPT Crea Sinonimo a tabla LDC_TIPO_TRAB_X_NOV_OFERTADOS para LDC_PROGENNOVOFERTSENSEVAESCA
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.LDC_TIPO_TRAB_X_NOV_OFERTADOS FOR LDC_TIPO_TRAB_X_NOV_OFERTADOS';
END;
/