PROMPT Crea Sinonimo a tabla LDC_ZONA_LOC_OFER_CART para LDC_PROGENERANOVELTYOFERTADOS
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.LDC_ZONA_LOC_OFER_CART FOR LDC_ZONA_LOC_OFER_CART';
END;
/