PROMPT Crea Sinonimo a paquete CT_ORDER_CERTIFICA para LDC_PROGENERANOVELTYOFERTADOS
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.CT_ORDER_CERTIFICA FOR CT_ORDER_CERTIFICA';
END;
/