PROMPT Crea Sinonimo a paquete LDC_UNID_OPER_HIJA_MOD_TAR para LDC_PROGENERANOVELTYOFERTADOS
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.LDC_UNID_OPER_HIJA_MOD_TAR FOR LDC_UNID_OPER_HIJA_MOD_TAR';
END;
/