GRANT SELECT ON SEQ_LDC_CONF_COMM_AUT_CONT TO SYSTEM_OBJ_PRIVS_ROLE;

GRANT SELECT ON SEQ_LDC_CONF_COMM_AUT_CONT TO RSELOPEN;

GRANT SELECT ON SEQ_LDC_CONF_COMM_AUT_CONT TO REPORTES;
/

GRANT SELECT ON SEQ_LDC_COMM_AUT_CONT TO SYSTEM_OBJ_PRIVS_ROLE;

GRANT SELECT ON SEQ_LDC_COMM_AUT_CONT TO RSELOPEN;

GRANT SELECT ON SEQ_LDC_COMM_AUT_CONT TO REPORTES;
/

GRANT SELECT ON SEQ_LDC_LOG_COMM_AUT_CONT TO SYSTEM_OBJ_PRIVS_ROLE;

GRANT SELECT ON SEQ_LDC_LOG_COMM_AUT_CONT TO RSELOPEN;

GRANT SELECT ON SEQ_LDC_LOG_COMM_AUT_CONT TO REPORTES;
/