PROMPT Crea Sinonimo a Secuencia SEQ_GC_PROYCAST_172026 para LDC_PRVALEGAORDENPERSEC
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.SEQ_GC_PROYCAST_172026 FOR SEQ_GC_PROYCAST_172026';
END;
/