select *
from CC_COMMERCIAL_SEGM
WHERE COMMERCIAL_SEGM_ID = 758;

SELECT *
FROM  CC_COMMERCIAL_SEGM SE, OPEN.CC_COM_SEG_FEA_VAL CAR_GEOPOL, CC_COM_SEG_FINAN PLAFIN, OPEN.plandife
WHERE CAR_GEOPOL.COMMERCIAL_SEGM_ID=SE.COMMERCIAL_SEGM_ID
  AND PLAFIN.COMMERCIAL_SEGM_ID = SE.COMMERCIAL_SEGM_ID
  AND GEOG_CATEGORY_ID=3
  AND PLDICODI=PLAFIN.FINANCING_PLAN_ID;



  

