PROMPT Crea Sinonimo a funcion LDC_FNCRETORNASALDDIFVISITA para LDCPROCCREATRAMFLUJSACXML
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.LDC_FNCRETORNASALDDIFVISITA FOR LDC_FNCRETORNASALDDIFVISITA';
END;
/