PROMPT Crea Sinonimo a funcion LDCFNCRETORNAMARCAREPPRP para LDCPROCCREATRAMFLUJSACXML
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.LDCFNCRETORNAMARCAREPPRP FOR LDCFNCRETORNAMARCAREPPRP';
END;
/