create table OPEN.LDCBI_LDC_PROTECCION_DATOS
(
    PROTECCION_DATOS_ID       NUMBER(20)  not null,
    OPERATION      VARCHAR2(1) not null,
    PROCESS_STATUS NUMBER(3) default -1,
    CREATED_DATE   DATE      default SYSDATE
);

create index IDX_LDCBI_LDC_PROTECCION_DATOS on OPEN.LDCBI_LDC_PROTECCION_DATOS (PROCESS_STATUS, OPERATION);
create index IDX_LDCBI_LDC_PROT_DATOS_PRST on OPEN.LDCBI_LDC_PROTECCION_DATOS (PROCESS_STATUS);

grant select, insert, update, delete on OPEN.LDCBI_LDC_PROTECCION_DATOS to INNOVACIONBI;