//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3643
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINCECOMP.FNB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SinceComp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SinceComp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SINCECOMP.FNB.Properties.SinceComp", typeof(SinceComp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap asterisc {
            get {
                object obj = ResourceManager.GetObject("asterisc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igual.
        /// </summary>
        internal static string EQUAL {
            get {
                return ResourceManager.GetString("EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha superado su cupo disponible para el artículo [{0}]: - Cupo Total [{1:C}].
        /// </summary>
        internal static string ERROR_EXTRA_QUOTA {
            get {
                return ResourceManager.GetString("ERROR_EXTRA_QUOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayor o igual que.
        /// </summary>
        internal static string GREATEREQUALTHAN {
            get {
                return ResourceManager.GetString("GREATEREQUALTHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayor que.
        /// </summary>
        internal static string GREATERTHAN {
            get {
                return ResourceManager.GetString("GREATERTHAN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap imgQuery {
            get {
                object obj = ResourceManager.GetObject("imgQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como ....
        /// </summary>
        internal static string LIKE {
            get {
                return ResourceManager.GetString("LIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menor o igual que.
        /// </summary>
        internal static string LOWEREQUALTHAN {
            get {
                return ResourceManager.GetString("LOWEREQUALTHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menor que.
        /// </summary>
        internal static string LOWERTHAN {
            get {
                return ResourceManager.GetString("LOWERTHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diferente.
        /// </summary>
        internal static string NOEQUAL {
            get {
                return ResourceManager.GetString("NOEQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =,&lt;,&gt;,&lt;=,&gt;=,&lt;&gt;,*.
        /// </summary>
        internal static string QUERYOPERATORS {
            get {
                return ResourceManager.GetString("QUERYOPERATORS", resourceCulture);
            }
        }
    }
}
