DECLARE
  CURSOR cuTabla(sbTable VARCHAR2, sbEsquema VARCHAR2) IS
    SELECT * FROM all_tables WHERE upper(TABLE_NAME) = upper(sbTable) and owner = sbEsquema;

  rccuTabla cuTabla%ROWTYPE;

BEGIN
  Dbms_Output.Put_Line('Inicia Creacion tabla PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG');
  OPEN cuTabla('LDC_LOG_CXC_SIN_LEG','PERSONALIZACIONES');
  FETCH cuTabla
    INTO rccuTabla;

  IF (cuTabla%NOTFOUND) THEN

    Dbms_Output.Put_Line('Inicia Crea PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG');

    EXECUTE IMMEDIATE 'create table PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG
               (
                   FECHA_REGISTRO DATE NOT NULL,
                   MENSAJE VARCHAR2(4000) NOT NULL
                )';
    --- Comentarios de la tabla y campos.
    EXECUTE IMMEDIATE 'comment on table PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG is ''REGISTRO DE INCONSISTENCIA EN NOTIFICACION DE CXC SIN LEGALIZAR''';
    EXECUTE IMMEDIATE 'comment on column PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG.FECHA_REGISTRO is ''Fecha Registro Inconsistencia''';
    EXECUTE IMMEDIATE 'comment on column PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG.MENSAJE is ''Mensaje Inconsistencia''';

    --Llaves
    dbms_output.put_line('SCRIPT: APLICANDO INDICE...');
    EXECUTE IMMEDIATE 'create index IDX_LOG_CXC_SIN_LEG_01 on PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG (FECHA_REGISTRO)';
    EXECUTE IMMEDIATE 'create index IDX_LOG_CXC_SIN_LEG_02 on PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG (MENSAJE )';

    dbms_output.put_line('SCRIPT: APLICANDO PERMISOS...');
    --- Aplica Permisos.
    EXECUTE IMMEDIATE 'GRANT SELECT,UPDATE,DELETE,INSERT ON PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG TO SYSTEM_OBJ_PRIVS_ROLE';
    EXECUTE IMMEDIATE 'GRANT SELECT ON PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG TO REPORTES';
    EXECUTE IMMEDIATE 'GRANT SELECT ON PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG TO RSELOPEN';
    --- Fin.

    Dbms_Output.Put_Line('Fin Creacion tabla PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG');
  ELSE
    Dbms_Output.Put_Line('***************tabla PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG ya existe');
  END IF;
  CLOSE cuTabla;

END;
/