select l.cucocodi cuenta_cobro,
       l.cucodepa departamento,
       l.cucoloca localidad,
       l.cucoplsu plan_de_suscripcion,
       l.cucocate categoria,
       l.cucosuca subcategoria ,
       l.cucovaap valor_autorizado_pagar,
       l.cucovare valor_del_reclamo ,
       l.cucovaab valor_del_abono ,
       l.cucovato valor_total_cuenta_cobro ,
       l.cucofepa fecha_pago ,
       l.cuconuse producto,
       l.cucosacu saldo_cuenta_cobro ,
       l.cucovrap reclamos_pago_no_abonado,
       l.cucofact numero_factura,
       l.cucofaag fact_agrupadora,
       l.cucofeve fecha_vencimiento,
       l.cucovafa valor_facturado,
       l.cucosist cod_empresa_recuado,
       l.cucogrim grupo_impresion,
       l.cucoimfa valor_impuestos,
       l.cucodiin dir_instalacion
from open.cuencobr l 
