DECLARE
  nuConta NUMBER;
BEGIN
  SELECT COUNT(1) INTO nuConta
  FROM DBA_SYNONYMS
  WHERE SYNONYM_NAME = 'FA_BOACCOUNTSTATUSTODATE'
   AND OWNER = 'ADM_PERSON';

  IF nuConta = 0 THEN
      EXECUTE IMMEDIATE 'CREATE SYNONYM ADM_PERSON.FA_BOACCOUNTSTATUSTODATE FOR OPEN.FA_BOACCOUNTSTATUSTODATE';
  END IF;
END;
/