DECLARE
  nuConta NUMBER;
BEGIN
  SELECT COUNT(1) INTO nuConta
  FROM DBA_SYNONYMS
  WHERE SYNONYM_NAME = 'OS_SUBSCRIPTIONREGISTER'
   AND OWNER = 'ADM_PERSON';

  IF nuConta = 0 THEN
      EXECUTE IMMEDIATE 'CREATE SYNONYM ADM_PERSON.OS_SUBSCRIPTIONREGISTER FOR OPEN.OS_SUBSCRIPTIONREGISTER';
  END IF;
END;
/