DECLARE
  nuConta NUMBER;
BEGIN
  SELECT COUNT(1) INTO nuConta
  FROM DBA_SYNONYMS
  WHERE SYNONYM_NAME = 'OS_ASSIGN_ORDER'
   AND OWNER = 'PERSONALIZACIONES';

  IF nuConta = 0 THEN
      EXECUTE IMMEDIATE 'DROP SYNONYM PERSONALIZACIONES.OS_ASSIGN_ORDER';
  END IF;
END;
/