WITH BASE AS
 (SELECT SERIMMIT,
         SERINUME,
         SERIESTR,
         LENGTH(SERIESTR) TAM,
         D.SERIMARC,
         D.SERIANO,
         D.SERIREMA,
         D.SERITIEN
    FROM OPEN.LDCI_SERIDMIT D)
SELECT BASE.*,
       SUBSTR(SERIESTR, 3, TAM-8) SERIAL,
       DECODE(SUBSTR(SERIESTR, TAM - 1, 2), '01', 'I', 'D') TIPO_ENT,
       SUBSTR(SERIESTR, TAM - 3, 2) REFE,
       SUBSTR(SERIESTR, TAM - 5, 2) ANO,
       SUBSTR(SERIESTR, 1, 2) MARCA
  FROM BASE
 WHERE BASE.SERIANO != SUBSTR(SERIESTR, TAM - 5, 2)
    OR TO_NUMBER(BASE.SERIREMA) != TO_NUMBER(SUBSTR(SERIESTR, TAM - 3, 2))
    OR BASE.SERITIEN !=
       DECODE(SUBSTR(SERIESTR, TAM - 1, 2), '01', 'I', 'D')
