-- Extraer Configuracion Contable 
ALTER SESSION SET CURRENT_SCHEMA= "OPEN";
select distinct COD_TIPCOMPROBANTE,
       DESC_TIPCOMPROBANTE,
       COD_COMPROBANTE,       --
       DES_COMPROBANTE,       --
       DESC_TIPODOCUMENTO,
       COD_TIPOMOVIMIENTO,
       DESC_TIPOMOVIMIENTO,
       COD_CLASCONT,
       DESC_CLASCONT,
       DOMINIO,
       VALOR_REPORTAR, CTA_CONTABLE_DB,
       CTA_CONTABLE_CR,
       CRITERIO
       from ( 
SELECT
       COD_TIPCOMPROBANTE,
       DESC_TIPCOMPROBANTE,
       COD_COMPROBANTE,
       DES_COMPROBANTE,
       DESC_TIPODOCUMENTO,
       COD_TIPOMOVIMIENTO,
       DESC_TIPOMOVIMIENTO,
       COD_CLASCONT,
       DESC_CLASCONT,
       DOMINIO,
       VALOR_REPORTAR,
       max(CTA_CONTABLE_DB) CTA_CONTABLE_DB,
       max(CTA_CONTABLE_CR) CTA_CONTABLE_CR,
       CLCRCONS,
       CRITERIO
 FROM (
  SELECT A.COCOCODI COD_COMPROBANTE,
         A.COCODESC DES_COMPROBANTE,
         B.TCCOCODI COD_TIPCOMPROBANTE,
         B.TCCODESC DESC_TIPCOMPROBANTE,
         D.TIDCDESC DESC_TIPODOCUMENTO,
         E.TIMOCODI COD_TIPOMOVIMIENTO,
         E.TIMODESC DESC_TIPOMOVIMIENTO,
         F.CLCRCONS,
         G.CLCOCODI COD_CLASCONT,
         G.CLCODESC DESC_CLASCONT,
         DECODE(G.CLCODOMI,'C','Concepto','B','Banco','T''Tipo Trabajo') DOMINIO,
         DECODE(I.RCCCVALO,'V','Valor Total',I.RCCCVALO) VALOR_REPORTAR,
         decode (I.RCCCNATU,'D',I.RCCCCUCO) CTA_CONTABLE_DB,
         decode (I.RCCCNATU,'C',I.RCCCCUCO) CTA_CONTABLE_CR,
         (select listagg(J.CCRCCAMP||' '||J.CCRCOPER||' '||J.CCRCVALO||' ') within group(order by J.CCRCCAMP) as CAMPO
            from OPEN.IC_CRCORECO J
           WHERE J.CCRCCLCR(+)=F.CLCRCONS) Criterio
         --J.CCRCCAMP||' '||J.CCRCOPER||' '||J.CCRCVALO CRITERIO, 
         --(select description from ge_items g where to_char(g.items_id) = J.CCRCVALO ) itemdesc
  FROM  OPEN.IC_COMPCONT A, OPEN.IC_TICOCONT B, OPEN.IC_CONFRECO C , OPEN.IC_TIPODOCO D ,
        OPEN.IC_TIPOMOVI E ,OPEN.IC_CLASCORE F , OPEN.IC_CLASCONT G, OPEN.IC_RECOCLCO I, OPEN.IC_CRCORECO J
  WHERE J.CCRCCLCR(+)=F.CLCRCONS and
        A.COCOCODI=C.CORCCOCO AND
        C.CORCTIDO=D.TIDCCODI AND
        C.CORCTIMO=E.TIMOCODI AND
        C.CORCCONS=F.CLCRCORC AND
        F.CLCRCLCO=G.CLCOCODI AND
        F.CLCRCONS=I.RCCCCLCR AND
        A.COCOTCCO=B.TCCOCODI
        AND G.CLCODOMI IN ('C')
        )
where COD_TIPCOMPROBANTE = 2
--  and COD_CLASCONT = 16
GROUP BY COD_COMPROBANTE, DES_COMPROBANTE, COD_TIPCOMPROBANTE, DESC_TIPCOMPROBANTE, DESC_TIPODOCUMENTO, COD_TIPOMOVIMIENTO,
       DESC_TIPOMOVIMIENTO, CLCRCONS, COD_CLASCONT, DESC_CLASCONT, DOMINIO, VALOR_REPORTAR, criterio--, itemdesc                                     
ORDER BY COD_CLASCONT, CTA_CONTABLE_DB)
group by COD_TIPCOMPROBANTE, DESC_TIPCOMPROBANTE, COD_COMPROBANTE, DES_COMPROBANTE, DESC_TIPODOCUMENTO,
       COD_TIPOMOVIMIENTO, DESC_TIPOMOVIMIENTO, COD_CLASCONT, DESC_CLASCONT, DOMINIO, VALOR_REPORTAR, 
       CTA_CONTABLE_DB,CTA_CONTABLE_CR, criterio--, itemdesc
order by cod_tipomovimiento, cod_clascont
       

