CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_ELMESESU 
AFTER INSERT OR UPDATE OR DELETE ON ELMESESU
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

EMSSELME NUMBER(15);
EMSSCMSS NUMBER(15);
EMSSSESU NUMBER(15);
EMSSFEIN DATE;
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  EMSSELME := :new.EMSSELME;
  EMSSCMSS := :new.EMSSCMSS;
  EMSSSESU := :new.EMSSSESU;
  EMSSFEIN := :new.EMSSFEIN;
  OPERATION := 'I';
ELSIF UPDATING THEN
  EMSSELME := :new.EMSSELME;
  EMSSCMSS := :new.EMSSCMSS;
  EMSSSESU := :new.EMSSSESU;
  EMSSFEIN := :new.EMSSFEIN;
  OPERATION := 'U';
ELSE
  EMSSELME := :old.EMSSELME;
  EMSSCMSS := :old.EMSSCMSS;
  EMSSSESU := :old.EMSSSESU;
  EMSSFEIN := :old.EMSSFEIN;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_ELMESESU (
  EMSSELME,
  EMSSCMSS,
  EMSSSESU,
  EMSSFEIN,
  OPERATION
)
VALUES (
  EMSSELME,
  EMSSCMSS,
  EMSSSESU,
  EMSSFEIN,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EX.CONTROLLED_ERROR;
END;
/
