CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_GE_CONTRATISTA 
AFTER INSERT OR UPDATE OR DELETE ON GE_CONTRATISTA
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

ID_CONTRATISTA NUMBER(15);
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  ID_CONTRATISTA := :new.ID_CONTRATISTA;
  OPERATION := 'I';
ELSIF UPDATING THEN
  ID_CONTRATISTA := :new.ID_CONTRATISTA;
  OPERATION := 'U';
ELSE
  ID_CONTRATISTA := :old.ID_CONTRATISTA;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_GE_CONTRATISTA (
  ID_CONTRATISTA,
  OPERATION
)
VALUES (
  ID_CONTRATISTA,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EX.CONTROLLED_ERROR;
END;
/
