CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_OR_ORDER_ACTIVITY 
AFTER INSERT OR UPDATE OR DELETE ON OR_ORDER_ACTIVITY
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

ORDER_ACTIVITY_ID NUMBER(15);
IS_DELETE VARCHAR(1);

BEGIN

IF DELETING THEN
  ORDER_ACTIVITY_ID := :old.order_activity_id;
  IS_DELETE := 'Y';
ELSE
  ORDER_ACTIVITY_ID := :new.order_activity_id;
  IS_DELETE := 'N';
END IF;

INSERT INTO LDCBI_OR_ORDER_ACTIVITY (
  ORDER_ACTIVITY_ID,
  IS_DELETE
)
VALUES (
  ORDER_ACTIVITY_ID,
  IS_DELETE
);

EXCEPTION
    WHEN OTHERS THEN
        RAISE EX.CONTROLLED_ERROR;
END;
/
