CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_CM_FACOCOSS 
AFTER INSERT OR UPDATE OR DELETE ON CM_FACOCOSS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

FCCOCONS NUMBER(15);
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  FCCOCONS := :new.FCCOCONS;
  OPERATION := 'I';
ELSIF UPDATING THEN
  FCCOCONS := :new.FCCOCONS;
  OPERATION := 'U';
ELSE
  FCCOCONS := :old.FCCOCONS;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_CM_FACOCOSS (
  FCCOCONS,
  OPERATION
)
VALUES (
  FCCOCONS,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EX.CONTROLLED_ERROR;
END;
/
