CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_MO_SUSPENSION 
AFTER INSERT OR UPDATE OR DELETE ON MO_SUSPENSION
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

MOTIVE_ID NUMBER(15);
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  MOTIVE_ID := :new.MOTIVE_ID;
  OPERATION := 'I';
ELSIF UPDATING THEN
  MOTIVE_ID := :new.MOTIVE_ID;
  OPERATION := 'U';
ELSE
  MOTIVE_ID := :old.MOTIVE_ID;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_MO_SUSPENSION (
  MOTIVE_ID,
  OPERATION
)
VALUES (
  MOTIVE_ID,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EX.CONTROLLED_ERROR;
END;
/
