CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_FM_POSSIBLE_NTL 
AFTER INSERT OR UPDATE OR DELETE ON FM_POSSIBLE_NTL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

POSSIBLE_NTL_ID NUMBER(15);
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  POSSIBLE_NTL_ID := :new.POSSIBLE_NTL_ID;
  OPERATION := 'I';
ELSIF UPDATING THEN
  POSSIBLE_NTL_ID := :new.POSSIBLE_NTL_ID;
  OPERATION := 'U';
ELSE
  POSSIBLE_NTL_ID := :old.POSSIBLE_NTL_ID;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_FM_POSSIBLE_NTL (
  POSSIBLE_NTL_ID,
  OPERATION
)
VALUES (
  POSSIBLE_NTL_ID,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EX.CONTROLLED_ERROR;
END;
/
