CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_GC_DEBT_NEGOT_PROD 
AFTER INSERT OR UPDATE OR DELETE ON GC_DEBT_NEGOT_PROD
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

DEBT_NEGOT_PROD_ID NUMBER(15);
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  DEBT_NEGOT_PROD_ID := :new.DEBT_NEGOT_PROD_ID;
  OPERATION := 'I';
ELSIF UPDATING THEN
  DEBT_NEGOT_PROD_ID := :new.DEBT_NEGOT_PROD_ID;
  OPERATION := 'U';
ELSE
  DEBT_NEGOT_PROD_ID := :old.DEBT_NEGOT_PROD_ID;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_GC_DEBT_NEGOT_PROD (
  DEBT_NEGOT_PROD_ID,
  OPERATION
)
VALUES (
  DEBT_NEGOT_PROD_ID,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EX.CONTROLLED_ERROR;
END;
/
