CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_CC_FINANCING_REQUEST 
AFTER INSERT OR UPDATE OR DELETE ON CC_FINANCING_REQUEST
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

FINANCING_REQUEST_ID NUMBER(15);
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  FINANCING_REQUEST_ID := :new.FINANCING_REQUEST_ID;
  OPERATION := 'I';
ELSIF UPDATING THEN
  FINANCING_REQUEST_ID := :new.FINANCING_REQUEST_ID;
  OPERATION := 'U';
ELSE
  FINANCING_REQUEST_ID := :old.FINANCING_REQUEST_ID;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_CC_FINANCING_REQUEST (
  FINANCING_REQUEST_ID,
  OPERATION
)
VALUES (
  FINANCING_REQUEST_ID,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EX.CONTROLLED_ERROR;
END;
/
