DECLARE
  nuconta number;
BEGIN
  SELECT COUNT(1) INTO nuconta
  FROM DBA_TABLES
  WHERE TABLE_NAME = 'ACCIONES_GENERAL'
   AND OWNER = 'PERSONALIZACIONES';
  
  IF nuconta = 0 THEN 
     EXECUTE IMMEDIATE 'CREATE TABLE PERSONALIZACIONES.ACCIONES_GENERAL 
                        (	IDACCION NUMBER(4,0) NOT NULL ENABLE, 
                          DESCRIPCION VARCHAR2(100 BYTE) NOT NULL ENABLE, 
                          CONSTRAINT ACCION_PK PRIMARY KEY (IDACCION)
                        )';
     EXECUTE IMMEDIATE  q'#COMMENT ON COLUMN PERSONALIZACIONES.ACCIONES_GENERAL.IDACCION IS 'ID DE LA ACCION'#';
     EXECUTE IMMEDIATE q'#COMMENT ON COLUMN PERSONALIZACIONES.ACCIONES_GENERAL.DESCRIPCION IS 'DESCRIPCION DE LA ACCION'#';
  END IF;
  
  begin
  pkg_utilidades.prAplicarPermisos('ACCIONES_GENERAL', 'PERSONALIZACIONES');
  end;
  
END;
/