update ge_statement
   set module_id    = 4,
       description  = 'LDC_NOTI_ORDEN_TRAB_PETICIONES',
       statement    = q'#SELECT  O.CREATED_DATE FECHA_ORDEN, P.REQUEST_DATE FECHA_SOLIC,
        O.OPERATING_UNIT_ID||'-'||OPU.NAME UNIT_OPER,
        DAAB_ADDRESS.FNUGETGEOGRAP_LOCATION_ID(OA.ADDRESS_ID,NULL)||'-'||
        DAGE_GEOGRA_LOCATION.FSBGETDESCRIPTION(DAAB_ADDRESS.FNUGETGEOGRAP_LOCATION_ID(OA.ADDRESS_ID,NULL),NULL) LOCAL_SERV,
        O.ORDER_ID,
        DAAB_ADDRESS.FSBGETADDRESS(LDC_BONOTIFICACIONES.getAddressOrder(O.ORDER_ID))||' B/'||
        DAGE_GEOGRA_LOCATION.FSBGETDESCRIPTION(DAAB_ADDRESS.FNUGETNEIGHBORTHOOD_ID(LDC_BONOTIFICACIONES.getAddressOrder(O.ORDER_ID),NULL),NULL) DIR_AND_BARR_SERV,
        DECODE(P.PACKAGE_TYPE_ID,308,CC.DESCRIPTION,545,CC.DESCRIPTION,100030,CC.DESCRIPTION,PT.DESCRIPTION) SOL_REQUER,
        GS1.SUBSCRIBER_NAME||'-'||GS1.SUBS_LAST_NAME NOM_CLIENTE,
        LDC_CA_NOTI.FSBCATE(OA.SUBSCRIPTION_ID) CATEGORIA,
        LDC_CA_NOTI.FSBSUBCATE(OA.SUBSCRIPTION_ID) SUBCATEGORIA,
        decode (MT.SUBSCRIPTION_ID, null,'NO APLICA',MT.SUBSCRIPTION_ID ) CONTRATO,
        GS2.SUBSCRIBER_NAME||'-'||GS2.SUBS_LAST_NAME NOMBRE_SOLICITANTE, GS2.PHONE TEL_CONTACTO,
        OPEN.LDC_BONOTIFICACIONES.FSBNUMMEDIDOR(MT.SUBSCRIPTION_ID) MEDIDOR,
        decode(OPEN.LDC_BOUTILITIES.FSBGETVALORCAMPOTABLA('MO_COMMENT', 'PACKAGE_ID', 'COMMENT_', OA.PACKAGE_ID),-1,
               OPEN.LDC_BOUTILITIES.FSBGETVALORCAMPOTABLA('MO_PACKAGES', 'PACKAGE_ID', 'COMMENT_', OA.PACKAGE_ID)) OBSERVA,
        (SELECT SISTEMPR FROM SISTEMA WHERE SISTCODI = 99) EMPRESA,
        (SELECT VALUE_CHAIN FROM LD_PARAMETER, SISTEMA
            WHERE REPLACE(DESCRIPTION,'LÍNEA DE SERVICIO AL CLIENTE ','') = TRIM(SISTEMPR)
            AND SISTCODI = 99) TEL_ATENCION
FROM    OPEN.OR_ORDER O INNER JOIN OPEN.OR_ORDER_ACTIVITY OA
ON      O.ORDER_ID                = OA.ORDER_ID
INNER JOIN OPEN.MO_PACKAGES P
ON      OA.PACKAGE_ID             = P.PACKAGE_ID
INNER JOIN OPEN.GE_SUBSCRIBER GS1
ON      P.SUBSCRIBER_ID           = GS1.SUBSCRIBER_ID
INNER JOIN  OPEN.GE_SUBSCRIBER GS2
ON      P.CONTACT_ID              = GS2.SUBSCRIBER_ID
INNER JOIN OPEN.PS_PACKAGE_TYPE PT
ON      P.PACKAGE_TYPE_ID         = PT.PACKAGE_TYPE_ID
LEFT OUTER JOIN OPEN.MO_MOTIVE MT
ON    P.PACKAGE_ID         = MT.PACKAGE_ID
LEFT OUTER JOIN OPEN.CC_CAUSAL CC
ON    MT.CAUSAL_ID         = CC.CAUSAL_ID
LEFT OUTER JOIN OPEN.OR_OPERATING_UNIT OPU
ON      O.OPERATING_UNIT_ID       = OPU.OPERATING_UNIT_ID
WHERE  O.ORDER_ID  = :ORDER_ID#',
       name='LDC_NOTI_ORDEN_TRAB_PETICIONES'
 where statement_id = 120009035;
 commit;
