--
--SQL Statement which produced this data:
--  select t1.*, t1.rowid from LDC_TIPSOLPLANFINAN t1
--
MERGE INTO OPEN.LDC_TIPSOLPLANFINAN A USING
 (SELECT
  271 as "PACKAGE_TYPE_ID",
  23 as "PLDICODI",
  TO_DATE('08/19/2022 09:25:55', 'MM/DD/YYYY HH24:MI:SS') as "CREATED_TSPF",
  'OPEN' as "USUARIO_CREATED",
  NULL as "UPDATED_TSPF",
  NULL as "USUARIO_UPDATED"
  FROM DUAL) B
ON (A.PACKAGE_TYPE_ID = B.PACKAGE_TYPE_ID and A.PLDICODI = B.PLDICODI)
WHEN NOT MATCHED THEN 
INSERT (
  PACKAGE_TYPE_ID, PLDICODI, CREATED_TSPF, USUARIO_CREATED, UPDATED_TSPF, 
  USUARIO_UPDATED)
VALUES (
  B.PACKAGE_TYPE_ID, B.PLDICODI, B.CREATED_TSPF, B.USUARIO_CREATED, B.UPDATED_TSPF, 
  B.USUARIO_UPDATED)
WHEN MATCHED THEN
UPDATE SET 
  A.CREATED_TSPF = B.CREATED_TSPF,
  A.USUARIO_CREATED = B.USUARIO_CREATED,
  A.UPDATED_TSPF = B.UPDATED_TSPF,
  A.USUARIO_UPDATED = B.USUARIO_UPDATED;

MERGE INTO OPEN.LDC_TIPSOLPLANFINAN A USING
 (SELECT
  100229 as "PACKAGE_TYPE_ID",
  24 as "PLDICODI",
  TO_DATE('08/19/2022 09:25:55', 'MM/DD/YYYY HH24:MI:SS') as "CREATED_TSPF",
  'OPEN' as "USUARIO_CREATED",
  NULL as "UPDATED_TSPF",
  NULL as "USUARIO_UPDATED"
  FROM DUAL) B
ON (A.PACKAGE_TYPE_ID = B.PACKAGE_TYPE_ID and A.PLDICODI = B.PLDICODI)
WHEN NOT MATCHED THEN 
INSERT (
  PACKAGE_TYPE_ID, PLDICODI, CREATED_TSPF, USUARIO_CREATED, UPDATED_TSPF, 
  USUARIO_UPDATED)
VALUES (
  B.PACKAGE_TYPE_ID, B.PLDICODI, B.CREATED_TSPF, B.USUARIO_CREATED, B.UPDATED_TSPF, 
  B.USUARIO_UPDATED)
WHEN MATCHED THEN
UPDATE SET 
  A.CREATED_TSPF = B.CREATED_TSPF,
  A.USUARIO_CREATED = B.USUARIO_CREATED,
  A.UPDATED_TSPF = B.UPDATED_TSPF,
  A.USUARIO_UPDATED = B.USUARIO_UPDATED;

MERGE INTO OPEN.LDC_TIPSOLPLANFINAN A USING
 (SELECT
  100229 as "PACKAGE_TYPE_ID",
  26 as "PLDICODI",
  TO_DATE('08/19/2022 09:25:55', 'MM/DD/YYYY HH24:MI:SS') as "CREATED_TSPF",
  'OPEN' as "USUARIO_CREATED",
  NULL as "UPDATED_TSPF",
  NULL as "USUARIO_UPDATED"
  FROM DUAL) B
ON (A.PACKAGE_TYPE_ID = B.PACKAGE_TYPE_ID and A.PLDICODI = B.PLDICODI)
WHEN NOT MATCHED THEN 
INSERT (
  PACKAGE_TYPE_ID, PLDICODI, CREATED_TSPF, USUARIO_CREATED, UPDATED_TSPF, 
  USUARIO_UPDATED)
VALUES (
  B.PACKAGE_TYPE_ID, B.PLDICODI, B.CREATED_TSPF, B.USUARIO_CREATED, B.UPDATED_TSPF, 
  B.USUARIO_UPDATED)
WHEN MATCHED THEN
UPDATE SET 
  A.CREATED_TSPF = B.CREATED_TSPF,
  A.USUARIO_CREATED = B.USUARIO_CREATED,
  A.UPDATED_TSPF = B.UPDATED_TSPF,
  A.USUARIO_UPDATED = B.USUARIO_UPDATED;

MERGE INTO OPEN.LDC_TIPSOLPLANFINAN A USING
 (SELECT
  100229 as "PACKAGE_TYPE_ID",
  28 as "PLDICODI",
  TO_DATE('08/19/2022 09:25:55', 'MM/DD/YYYY HH24:MI:SS') as "CREATED_TSPF",
  'OPEN' as "USUARIO_CREATED",
  NULL as "UPDATED_TSPF",
  NULL as "USUARIO_UPDATED"
  FROM DUAL) B
ON (A.PACKAGE_TYPE_ID = B.PACKAGE_TYPE_ID and A.PLDICODI = B.PLDICODI)
WHEN NOT MATCHED THEN 
INSERT (
  PACKAGE_TYPE_ID, PLDICODI, CREATED_TSPF, USUARIO_CREATED, UPDATED_TSPF, 
  USUARIO_UPDATED)
VALUES (
  B.PACKAGE_TYPE_ID, B.PLDICODI, B.CREATED_TSPF, B.USUARIO_CREATED, B.UPDATED_TSPF, 
  B.USUARIO_UPDATED)
WHEN MATCHED THEN
UPDATE SET 
  A.CREATED_TSPF = B.CREATED_TSPF,
  A.USUARIO_CREATED = B.USUARIO_CREATED,
  A.UPDATED_TSPF = B.UPDATED_TSPF,
  A.USUARIO_UPDATED = B.USUARIO_UPDATED;

MERGE INTO OPEN.LDC_TIPSOLPLANFINAN A USING
 (SELECT
  100229 as "PACKAGE_TYPE_ID",
  31 as "PLDICODI",
  TO_DATE('08/19/2022 09:25:56', 'MM/DD/YYYY HH24:MI:SS') as "CREATED_TSPF",
  'OPEN' as "USUARIO_CREATED",
  NULL as "UPDATED_TSPF",
  NULL as "USUARIO_UPDATED"
  FROM DUAL) B
ON (A.PACKAGE_TYPE_ID = B.PACKAGE_TYPE_ID and A.PLDICODI = B.PLDICODI)
WHEN NOT MATCHED THEN 
INSERT (
  PACKAGE_TYPE_ID, PLDICODI, CREATED_TSPF, USUARIO_CREATED, UPDATED_TSPF, 
  USUARIO_UPDATED)
VALUES (
  B.PACKAGE_TYPE_ID, B.PLDICODI, B.CREATED_TSPF, B.USUARIO_CREATED, B.UPDATED_TSPF, 
  B.USUARIO_UPDATED)
WHEN MATCHED THEN
UPDATE SET 
  A.CREATED_TSPF = B.CREATED_TSPF,
  A.USUARIO_CREATED = B.USUARIO_CREATED,
  A.UPDATED_TSPF = B.UPDATED_TSPF,
  A.USUARIO_UPDATED = B.USUARIO_UPDATED;

MERGE INTO OPEN.LDC_TIPSOLPLANFINAN A USING
 (SELECT
  100229 as "PACKAGE_TYPE_ID",
  64 as "PLDICODI",
  TO_DATE('08/19/2022 09:25:56', 'MM/DD/YYYY HH24:MI:SS') as "CREATED_TSPF",
  'OPEN' as "USUARIO_CREATED",
  NULL as "UPDATED_TSPF",
  NULL as "USUARIO_UPDATED"
  FROM DUAL) B
ON (A.PACKAGE_TYPE_ID = B.PACKAGE_TYPE_ID and A.PLDICODI = B.PLDICODI)
WHEN NOT MATCHED THEN 
INSERT (
  PACKAGE_TYPE_ID, PLDICODI, CREATED_TSPF, USUARIO_CREATED, UPDATED_TSPF, 
  USUARIO_UPDATED)
VALUES (
  B.PACKAGE_TYPE_ID, B.PLDICODI, B.CREATED_TSPF, B.USUARIO_CREATED, B.UPDATED_TSPF, 
  B.USUARIO_UPDATED)
WHEN MATCHED THEN
UPDATE SET 
  A.CREATED_TSPF = B.CREATED_TSPF,
  A.USUARIO_CREATED = B.USUARIO_CREATED,
  A.UPDATED_TSPF = B.UPDATED_TSPF,
  A.USUARIO_UPDATED = B.USUARIO_UPDATED;

MERGE INTO OPEN.LDC_TIPSOLPLANFINAN A USING
 (SELECT
  100229 as "PACKAGE_TYPE_ID",
  142 as "PLDICODI",
  TO_DATE('08/19/2022 09:25:56', 'MM/DD/YYYY HH24:MI:SS') as "CREATED_TSPF",
  'OPEN' as "USUARIO_CREATED",
  NULL as "UPDATED_TSPF",
  NULL as "USUARIO_UPDATED"
  FROM DUAL) B
ON (A.PACKAGE_TYPE_ID = B.PACKAGE_TYPE_ID and A.PLDICODI = B.PLDICODI)
WHEN NOT MATCHED THEN 
INSERT (
  PACKAGE_TYPE_ID, PLDICODI, CREATED_TSPF, USUARIO_CREATED, UPDATED_TSPF, 
  USUARIO_UPDATED)
VALUES (
  B.PACKAGE_TYPE_ID, B.PLDICODI, B.CREATED_TSPF, B.USUARIO_CREATED, B.UPDATED_TSPF, 
  B.USUARIO_UPDATED)
WHEN MATCHED THEN
UPDATE SET 
  A.CREATED_TSPF = B.CREATED_TSPF,
  A.USUARIO_CREATED = B.USUARIO_CREATED,
  A.UPDATED_TSPF = B.UPDATED_TSPF,
  A.USUARIO_UPDATED = B.USUARIO_UPDATED;

COMMIT;
/