begin

MERGE INTO OPEN.LDCI_CARASEWE A USING
 (SELECT
  'HOST' as "CASECODI",
  'SERVIDOR' as "CASEDESC",
  '192.168.50.53' as "CASEVALO",
  'WS_FACELEC_EMI_ENERSOLAR' as "CASEDESE"
  FROM DUAL) B
ON (A.CASEDESE = B.CASEDESE AND A.CASECODI = B.CASECODI)
WHEN NOT MATCHED THEN 
INSERT (
  CASECODI, CASEDESC, CASEVALO, CASEDESE)
VALUES (
  B.CASECODI, B.CASEDESC, B.CASEVALO, B.CASEDESE)
WHEN MATCHED THEN
UPDATE SET 
  A.CASEVALO = B.CASEVALO;

end;
/