update  master_personalizaciones set COMENTARIO = 'MIGRADO ADM_PERSON'
where  NOMBRE in (
'LDCI_PKCONSULTABRILLA',
'LDCI_PKCRMFINBRILLAPORTAL',
'UT_EAN_CARDIF',
'LD_BCNONBANKFIRULES',
'LD_BOLIQUIDATIONMINUTE',
'LD_BOPLUGDATACRED',
'LD_BOUTILCANCELLATIONS',
'LDC_BCPRECUPON',
'LDC_PKVENTAFNB',
'UT_EAN',
'IDAUTOMATION',
'LD_BCFLOWFNBPACK',
'LD_BCLIQUIDATIONMINUTE',
'LD_BCPACKAGEFNB',
'LD_BCVISIT',
'LD_BODATACRED',
'LDC_BCCOTIZACIONCONSTRUCTORA',
'LDC_BCDATACREDITO',
'LD_BCQUOTATRANSFER',
'LDC_CALCULACUPOBRILLA',
'LDC_CODEUDORES',
'LDC_PKTRASFNB',
'LDC_PKVENTASEGUROVOLUNTARIO'
);

update  master_personalizaciones set COMENTARIO = 'OPEN'
where  NOMBRE in (
'LD_BCDATACRED',
'LD_BOPACKAGEFNB_SUPERSTORES',
'LDC_BCOTBYQUOTATION',
'LDC_PKVALIDASUSPCONE',
'LDCI_PKVENTABRILLA',
'UT_EAN_CENCO',
'UT_EAN_HOMENTER'
);

commit;
/