update  master_personalizaciones set COMENTARIO = 'MIGRADO ADM_PERSON'
where  NOMBRE in (
'LDCI_PKINBOXDETBRILLA',
'LDCI_PKINBOXDETONBASE',
'LDCI_PKINBOXDETREVP',
'LDCI_PKINFOADICIONALCART',
'LDCI_PKINFOADICIONALLEGA', 
'LDCI_PKINFOADICIONALOT',
'LDCI_PKINFOADICIONALOYM',
'LDCI_PKINFOADICIONALREVP',  
'LDCI_PKINFOADICIONALVENT',
'LDCI_PKIVR',
'LDCI_PKLEMADOPA',
'LDCI_PKORDENINTERNA',
'LDCI_PKREASIGNAORDEN',
'LDCI_PKUPDATECUSTOMER',
'LDCI_RESETINTMENSCAJAGRIS',
'LDCI_BOTRABAJOADICIONAL'
);

update  master_personalizaciones set COMENTARIO = 'OPEN'
where  NOMBRE in (
'LDCI_PKINTERFAZORDLEC',
'LDCI_PKINTERBCSFINAN',
'LDCI_PKINTERCENTROBENEF',
'LDCI_PKINTERCENTROCOSTO',
'LDCI_PKINTERCUENTACONT',
'LDCI_PKINTERFAZNIT',
'LDCI_PKINTERFAZONBASE'
);

update  master_personalizaciones set COMENTARIO = 'BORRADO'
where  NOMBRE in (
'LDCI_PKMOVIMATERIAL_SP'
);

commit;
/