column dt new_value vdt
column db new_value vdb
select to_char(sysdate,'yyyymmdd_hh24miss') dt, sys_context('userenv','db_name') db from dual;
set serveroutput on size unlimited
execute dbms_application_info.set_action('APLICANDO DATAFIX');
select to_char(sysdate,'yyyy-mm-dd hh:mi:ss p.m.') fecha_inicio from dual;

DECLARE
sbFactura1 CLOB;
sbFactura2 CLOB;
sbFactura3 CLOB;
sbFactura4 CLOB;
sbFactura5 CLOB;
BEGIN
    dbms_output.put_line('Inicia OSF-4160');
sbFactura1 := '<LDC_FACTURA>
<LDC_DATOS_CLIENTE><FACTURA>2013776371</FACTURA><FECH_FACT>06/MAY/2016</FECH_FACT><MES_FACT>ABR-2016</MES_FACT><PERIODO_FACT>ABRIL      2016</PERIODO_FACT><PAGO_HASTA>20/05/2016</PAGO_HASTA><DIAS_CONSUMO>31</DIAS_CONSUMO><CONTRATO>66428471</CONTRATO><CUPON>121435832</CUPON><NOMBRE>DIANA PATRICIA QUINTANA</NOMBRE><DIRECCION_COBRO>CL 49 KR 10C - 17 PISO 1 APTO 2</DIRECCION_COBRO><LOCALIDAD>SOLEDAD - ATL</LOCALIDAD><CATEGORIA>RESIDENCIAL</CATEGORIA><ESTRATO>ESTRATO 2</ESTRATO><CICLO>1406</CICLO><RUTA>14065811150537400</RUTA><MESES_DEUDA>2</MESES_DEUDA><NUM_CONTROL>2908058322</NUM_CONTROL><PERIODO_CONSUMO>30/MAR - 29/ABR</PERIODO_CONSUMO><SALDO_FAVOR>0</SALDO_FAVOR><FECHA_SUSPENSION>21/05/2016</FECHA_SUSPENSION><VALOR_RECL>0</VALOR_RECL><TOTAL_FACTURA>91,807</TOTAL_FACTURA><PAGO_SIN_RECARGO>20/05/2016</PAGO_SIN_RECARGO><CUPO_BRILLA>0</CUPO_BRILLA>
</LDC_DATOS_CLIENTE>
<LDC_DATOS_LECTURA>
<NUM_MEDIDOR>K-3207284-15</NUM_MEDIDOR><LECTURA_ANTERIOR>3</LECTURA_ANTERIOR><LECTURA_ACTUAL>6</LECTURA_ACTUAL><OBS_LECTURA></OBS_LECTURA>
</LDC_DATOS_LECTURA>
<LDC_DATOS_CONSUMO>
<CONS_CORREG>3</CONS_CORREG><FACTOR_CORRECCION> 0.9929</FACTOR_CORRECCION><CONSUMO_MES_1>3</CONSUMO_MES_1><FECHA_CONS_MES_1>MAR-16</FECHA_CONS_MES_1><CONSUMO_MES_2>0</CONSUMO_MES_2><FECHA_CONS_MES_2>FEB-16</FECHA_CONS_MES_2><CONSUMO_MES_3>0</CONSUMO_MES_3><FECHA_CONS_MES_3>ENE-16</FECHA_CONS_MES_3><CONSUMO_MES_4>0</CONSUMO_MES_4><FECHA_CONS_MES_4>DIC-15</FECHA_CONS_MES_4><CONSUMO_MES_5>0</CONSUMO_MES_5><FECHA_CONS_MES_5>NOV-15</FECHA_CONS_MES_5><CONSUMO_MES_6>0</CONSUMO_MES_6><FECHA_CONS_MES_6>OCT-15</FECHA_CONS_MES_6><CONSUMO_PROMEDIO>1</CONSUMO_PROMEDIO><TEMPERATURA>78.2857</TEMPERATURA><PRESION>.33</PRESION><EQUIVAL_KWH>3 M3 Equivalen a 31.11kwh</EQUIVAL_KWH><CALCCONS>LEC.MEDIDOR</CALCCONS>
</LDC_DATOS_CONSUMO>
<LDC_DATOS_REVISION>
<TIPO_NOTI>0</TIPO_NOTI><MENS_NOTI>La Revision Periodica debe Realizarse con Organismos de Inspeccion Acreditados.</MENS_NOTI><FECH_MAXIMA></FECH_MAXIMA><FECH_SUSP></FECH_SUSP>
</LDC_DATOS_REVISION>
<LDC_TOTALES>
<TOTAL_1></TOTAL_1>
</LDC_TOTALES>
<LDC_CARGOS>
<ETIQUETA>31</ETIQUETA><DESC_CONCEP>SERV.GAS (Serv.Susc.51129253)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>Saldo Anterior</DESC_CONCEP><SALDO_ANT>45,609</SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSUMO DE GAS NATURAL</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>4,736</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>73</CAPITAL><INTERES>363</INTERES><TOTAL></TOTAL><SALDO_DIF>15,943</SALDO_DIF><CUOTAS>70</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA BIENES Y SERVICIOS</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>52</CAPITAL><INTERES>254</INTERES><TOTAL></TOTAL><SALDO_DIF>11,167</SALDO_DIF><CUOTAS>70</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CARGO POR CONEXIÓN</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>2,152</CAPITAL><INTERES>10,646</INTERES><TOTAL></TOTAL><SALDO_DIF>468,211</SALDO_DIF><CUOTAS>70</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSTRUCCION DE INSTALACION INTERNA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>4,578</CAPITAL><INTERES>22,656</INTERES><TOTAL></TOTAL><SALDO_DIF>996,424</SALDO_DIF><CUOTAS>70</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CERTIFICACIÓN DE INSTALACIÓN PREVIA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>321</CAPITAL><INTERES>1,587</INTERES><TOTAL></TOTAL><SALDO_DIF>69,802</SALDO_DIF><CUOTAS>70</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>SUBSIDIO LEY 142/94(Hasta 20M3 44.19% Cons.)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>-2,093</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>IVA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>621</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>INTERES DE MORA(Tasa 2.239%)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES>252</INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>33</ETIQUETA><DESC_CONCEP>Total Servicio:</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>10,440</CAPITAL><INTERES>35,758</INTERES><TOTAL>46,198</TOTAL><SALDO_DIF>1,561,547</SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_RANGOS>
<LIM_INFERIOR>0</LIM_INFERIOR><LIM_SUPERIOR>20</LIM_SUPERIOR><VALOR_UNIDAD>1578.51</VALOR_UNIDAD><CONSUMO>3</CONSUMO><VAL_CONSUMO>4,735.53</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>21</LIM_INFERIOR><LIM_SUPERIOR>90000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>90001</LIM_INFERIOR><LIM_SUPERIOR>180000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>180001</LIM_INFERIOR><LIM_SUPERIOR>280000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>280001</LIM_INFERIOR><LIM_SUPERIOR>1000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>1000001</LIM_INFERIOR><LIM_SUPERIOR>5000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>5000001</LIM_INFERIOR><LIM_SUPERIOR>MAS</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_COMPCOST>
<COMPCOST>Gm = $725 Tm = $218 Dm = $200.52 Cv = $0 Cc = $0 Cm = $3570.76</COMPCOST><VALORESREF>DES(h)=0 IPLI=100% IO=100% IRST=NO APLICA</VALORESREF><VALCALC>DES(h)=0 COMPENSACION($)=0</VALCALC>
</LDC_COMPCOST>
<LDC_CUPON>
<COD_BAR>(415)7707232377896(8020)0121435832(3900)0000091807(96)20260520</COD_BAR>
</LDC_CUPON>
<EXTRA_BARCODE_>
<CODE>415770723237789680200121435832È39000000091807È9620160520</CODE>
<IMAGE></IMAGE>
</EXTRA_BARCODE_>
</LDC_FACTURA>
';	MERGE INTO OPEN.ED_DOCUMENT A USING
    (SELECT 2013776371 as DOCUCODI, 66 as DOCUTIDO, 67591 as DOCUPEFA, TO_DATE('07/05/2016 12:13:34 a.m.','DD/MM/YYYY HH:MI:SS A.M.') as DOCUFERE, sbFactura1 DOCUDOCU
      FROM DUAL) B
    ON (A.DOCUCODI = B.DOCUCODI and A.DOCUTIDO = B.DOCUTIDO)
    WHEN NOT MATCHED THEN  INSERT (
      DOCUCODI, DOCUTIDO, DOCUPEFA, DOCUFERE, DOCUDOCU)
     VALUES (
      B.DOCUCODI, B.DOCUTIDO, B.DOCUPEFA, B.DOCUFERE, B.DOCUDOCU)
    WHEN MATCHED THEN
     UPDATE SET 
      A.DOCUPEFA = B.DOCUPEFA,
      A.DOCUFERE = B.DOCUFERE,
      A.DOCUDOCU = B.DOCUDOCU;
sbFactura2 := '<LDC_FACTURA>
<LDC_DATOS_CLIENTE><FACTURA>2017672810</FACTURA><FECH_FACT>06/SEP/2016</FECH_FACT><MES_FACT>AGO-2016</MES_FACT><PERIODO_FACT>AGOSTO     2016</PERIODO_FACT><PAGO_HASTA>19/09/2016</PAGO_HASTA><DIAS_CONSUMO>31</DIAS_CONSUMO><CONTRATO>66428471</CONTRATO><CUPON>125322213</CUPON><NOMBRE>DIANA PATRICIA QUINTANA</NOMBRE><DIRECCION_COBRO>CL 49 KR 10C - 17 PISO 1 APTO 2</DIRECCION_COBRO><LOCALIDAD>SOLEDAD - ATL</LOCALIDAD><CATEGORIA>RESIDENCIAL</CATEGORIA><ESTRATO>ESTRATO 2</ESTRATO><CICLO>1406</CICLO><RUTA>14065811150537400</RUTA><MESES_DEUDA>2</MESES_DEUDA><NUM_CONTROL>2913227619</NUM_CONTROL><PERIODO_CONSUMO>30/JUL - 29/AGO</PERIODO_CONSUMO><SALDO_FAVOR>0</SALDO_FAVOR><FECHA_SUSPENSION>20/09/2016</FECHA_SUSPENSION><VALOR_RECL>0</VALOR_RECL><TOTAL_FACTURA>244,735</TOTAL_FACTURA><PAGO_SIN_RECARGO>19/09/2016</PAGO_SIN_RECARGO><CUPO_BRILLA>0</CUPO_BRILLA>
</LDC_DATOS_CLIENTE>
<LDC_DATOS_LECTURA>
<NUM_MEDIDOR>K-3207284-15</NUM_MEDIDOR><LECTURA_ANTERIOR>59.18</LECTURA_ANTERIOR><LECTURA_ACTUAL>138.72</LECTURA_ACTUAL><OBS_LECTURA></OBS_LECTURA>
</LDC_DATOS_LECTURA>
<LDC_DATOS_CONSUMO>
<CONS_CORREG>64</CONS_CORREG><FACTOR_CORRECCION> 0.9918</FACTOR_CORRECCION><CONSUMO_MES_1>62</CONSUMO_MES_1><FECHA_CONS_MES_1>JUL-16</FECHA_CONS_MES_1><CONSUMO_MES_2>2</CONSUMO_MES_2><FECHA_CONS_MES_2>JUN-16</FECHA_CONS_MES_2><CONSUMO_MES_3>3</CONSUMO_MES_3><FECHA_CONS_MES_3>MAY-16</FECHA_CONS_MES_3><CONSUMO_MES_4>3</CONSUMO_MES_4><FECHA_CONS_MES_4>ABR-16</FECHA_CONS_MES_4><CONSUMO_MES_5>3</CONSUMO_MES_5><FECHA_CONS_MES_5>MAR-16</FECHA_CONS_MES_5><CONSUMO_MES_6>0</CONSUMO_MES_6><FECHA_CONS_MES_6>FEB-16</FECHA_CONS_MES_6><CONSUMO_PROMEDIO>12</CONSUMO_PROMEDIO><TEMPERATURA>78.2894</TEMPERATURA><PRESION>.33</PRESION><EQUIVAL_KWH>64 M3 Equivalen a 663.68kwh</EQUIVAL_KWH><CALCCONS>LEC.MEDIDOR</CALCCONS>
</LDC_DATOS_CONSUMO>
<LDC_DATOS_REVISION>
<TIPO_NOTI>0</TIPO_NOTI><MENS_NOTI>La Revision Periodica debe Realizarse con Organismos de Inspeccion Acreditados.</MENS_NOTI><FECH_MAXIMA></FECH_MAXIMA><FECH_SUSP></FECH_SUSP>
</LDC_DATOS_REVISION>
<LDC_TOTALES>
<TOTAL_1></TOTAL_1>
</LDC_TOTALES>
<LDC_CARGOS>
<ETIQUETA>31</ETIQUETA><DESC_CONCEP>SERV.GAS (Serv.Susc.51129253)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>Saldo Anterior</DESC_CONCEP><SALDO_ANT>46,934</SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>IVA COBRO DUPLICADO</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>224</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSUMO DE GAS NATURALCO-59AJ-201607</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>84,591</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSUMO DE GAS NATURAL</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>95,395</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>53</CAPITAL><INTERES>393</INTERES><TOTAL></TOTAL><SALDO_DIF>15,680</SALDO_DIF><CUOTAS>66</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA BIENES Y SERVICIOS</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>37</CAPITAL><INTERES>275</INTERES><TOTAL></TOTAL><SALDO_DIF>10,982</SALDO_DIF><CUOTAS>66</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CARGO POR CONEXIÓN</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>1,533</CAPITAL><INTERES>11,539</INTERES><TOTAL></TOTAL><SALDO_DIF>460,524</SALDO_DIF><CUOTAS>66</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSTRUCCION DE INSTALACION INTERNA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>3,262</CAPITAL><INTERES>24,557</INTERES><TOTAL></TOTAL><SALDO_DIF>980,066</SALDO_DIF><CUOTAS>66</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CERTIFICACIÓN DE INSTALACIÓN PREVIA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>228</CAPITAL><INTERES>1,720</INTERES><TOTAL></TOTAL><SALDO_DIF>68,658</SALDO_DIF><CUOTAS>66</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>COBRO DUPLICADO FACTURA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>1,400</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>SUBSIDIO LEY 142/94(Hasta 20M3 45.26% Cons.) SU-17AJ-201607</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>-12,566</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>SUBSIDIO LEY 142/94(Hasta 20M3 46.81% Cons.)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>-15,819</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>IVA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>673</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>INTERES DE MORA(Tasa 2.315%)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES>306</INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>33</ETIQUETA><DESC_CONCEP>Total Servicio:</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>159,011</CAPITAL><INTERES>38,790</INTERES><TOTAL>197,801</TOTAL><SALDO_DIF>1,535,910</SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_RANGOS>
<LIM_INFERIOR>0</LIM_INFERIOR><LIM_SUPERIOR>20</LIM_SUPERIOR><VALOR_UNIDAD>1689.73</VALOR_UNIDAD><CONSUMO>20</CONSUMO><VAL_CONSUMO>33,794.60</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>21</LIM_INFERIOR><LIM_SUPERIOR>90000</LIM_SUPERIOR><VALOR_UNIDAD>1400</VALOR_UNIDAD><CONSUMO>44</CONSUMO><VAL_CONSUMO>61,600.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>90001</LIM_INFERIOR><LIM_SUPERIOR>180000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>180001</LIM_INFERIOR><LIM_SUPERIOR>280000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>280001</LIM_INFERIOR><LIM_SUPERIOR>1000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>1000001</LIM_INFERIOR><LIM_SUPERIOR>5000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>5000001</LIM_INFERIOR><LIM_SUPERIOR>MAS</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_COMPCOST>
<COMPCOST>Gm = $829 Tm = $206 Dm = $201.34 Cv = $0 Cc = $0 Cm = $3624.84</COMPCOST><VALORESREF>DES(h)=0 IPLI=100% IO=100% IRST=NO APLICA</VALORESREF><VALCALC>DES(h)=0 COMPENSACION($)=0</VALCALC>
</LDC_COMPCOST>
<LDC_CUPON>
<COD_BAR>(415)7707232377896(8020)0125322213(3900)0000244735(96)20260919</COD_BAR>
</LDC_CUPON>
<EXTRA_BARCODE_>
<CODE>415770723237789680200125322213È39000000244735È9620160919</CODE>
<IMAGE></IMAGE>
</EXTRA_BARCODE_>
</LDC_FACTURA>
';	MERGE INTO OPEN.ED_DOCUMENT A USING
    (SELECT 2017672810 as DOCUCODI, 66 as DOCUTIDO, 70914 as DOCUPEFA, TO_DATE('06/09/2016 09:09:08 p.m.','DD/MM/YYYY HH:MI:SS A.M.') as DOCUFERE, sbFactura2 DOCUDOCU
      FROM DUAL) B
    ON (A.DOCUCODI = B.DOCUCODI and A.DOCUTIDO = B.DOCUTIDO)
    WHEN NOT MATCHED THEN  INSERT (
      DOCUCODI, DOCUTIDO, DOCUPEFA, DOCUFERE, DOCUDOCU)
     VALUES (
      B.DOCUCODI, B.DOCUTIDO, B.DOCUPEFA, B.DOCUFERE, B.DOCUDOCU)
    WHEN MATCHED THEN
     UPDATE SET 
      A.DOCUPEFA = B.DOCUPEFA,
      A.DOCUFERE = B.DOCUFERE,
      A.DOCUDOCU = B.DOCUDOCU;
sbFactura3 := '<LDC_FACTURA>
<LDC_DATOS_CLIENTE><FACTURA>2016690615</FACTURA><FECH_FACT>05/AGO/2016</FECH_FACT><MES_FACT>JUL-2016</MES_FACT><PERIODO_FACT>JULIO      2016</PERIODO_FACT><PAGO_HASTA>18/08/2016</PAGO_HASTA><DIAS_CONSUMO>30</DIAS_CONSUMO><CONTRATO>66428471</CONTRATO><CUPON>124354608</CUPON><NOMBRE>DIANA PATRICIA QUINTANA</NOMBRE><DIRECCION_COBRO>CL 49 KR 10C - 17 PISO 1 APTO 2</DIRECCION_COBRO><LOCALIDAD>SOLEDAD - ATL</LOCALIDAD><CATEGORIA>RESIDENCIAL</CATEGORIA><ESTRATO>ESTRATO 2</ESTRATO><CICLO>1406</CICLO><RUTA>14065811150537400</RUTA><MESES_DEUDA>2</MESES_DEUDA><NUM_CONTROL>2911920937</NUM_CONTROL><PERIODO_CONSUMO>30/JUN - 29/JUL</PERIODO_CONSUMO><SALDO_FAVOR>0</SALDO_FAVOR><FECHA_SUSPENSION>19/08/2016</FECHA_SUSPENSION><VALOR_RECL>0</VALOR_RECL><TOTAL_FACTURA>92,884</TOTAL_FACTURA><PAGO_SIN_RECARGO>18/08/2016</PAGO_SIN_RECARGO><CUPO_BRILLA>0</CUPO_BRILLA>
</LDC_DATOS_CLIENTE>
<LDC_DATOS_LECTURA>
<NUM_MEDIDOR>K-3207284-15</NUM_MEDIDOR><LECTURA_ANTERIOR>11</LECTURA_ANTERIOR><LECTURA_ACTUAL>59.18</LECTURA_ACTUAL><OBS_LECTURA></OBS_LECTURA>
</LDC_DATOS_LECTURA>
<LDC_DATOS_CONSUMO>
<CONS_CORREG>3</CONS_CORREG><FACTOR_CORRECCION> 0.9906</FACTOR_CORRECCION><CONSUMO_MES_1>2</CONSUMO_MES_1><FECHA_CONS_MES_1>JUN-16</FECHA_CONS_MES_1><CONSUMO_MES_2>3</CONSUMO_MES_2><FECHA_CONS_MES_2>MAY-16</FECHA_CONS_MES_2><CONSUMO_MES_3>3</CONSUMO_MES_3><FECHA_CONS_MES_3>ABR-16</FECHA_CONS_MES_3><CONSUMO_MES_4>3</CONSUMO_MES_4><FECHA_CONS_MES_4>MAR-16</FECHA_CONS_MES_4><CONSUMO_MES_5>0</CONSUMO_MES_5><FECHA_CONS_MES_5>FEB-16</FECHA_CONS_MES_5><CONSUMO_MES_6>0</CONSUMO_MES_6><FECHA_CONS_MES_6>ENE-16</FECHA_CONS_MES_6><CONSUMO_PROMEDIO>2</CONSUMO_PROMEDIO><TEMPERATURA>77.8333</TEMPERATURA><PRESION>.33</PRESION><EQUIVAL_KWH>3 M3 Equivalen a 31.11kwh</EQUIVAL_KWH><CALCCONS>ESTIMADO</CALCCONS>
</LDC_DATOS_CONSUMO>
<LDC_DATOS_REVISION>
<TIPO_NOTI>0</TIPO_NOTI><MENS_NOTI>La Revision Periodica debe Realizarse con Organismos de Inspeccion Acreditados.</MENS_NOTI><FECH_MAXIMA></FECH_MAXIMA><FECH_SUSP></FECH_SUSP>
</LDC_DATOS_REVISION>
<LDC_TOTALES>
<TOTAL_1></TOTAL_1>
</LDC_TOTALES>
<LDC_CARGOS>
<ETIQUETA>31</ETIQUETA><DESC_CONCEP>SERV.GAS (Serv.Susc.51129253)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>Saldo Anterior</DESC_CONCEP><SALDO_ANT>45,950</SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSUMO DE GAS NATURAL</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>4,900</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>74</CAPITAL><INTERES>370</INTERES><TOTAL></TOTAL><SALDO_DIF>15,733</SALDO_DIF><CUOTAS>67</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA BIENES Y SERVICIOS</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>52</CAPITAL><INTERES>259</INTERES><TOTAL></TOTAL><SALDO_DIF>11,019</SALDO_DIF><CUOTAS>67</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CARGO POR CONEXIÓN</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>2,177</CAPITAL><INTERES>10,869</INTERES><TOTAL></TOTAL><SALDO_DIF>462,057</SALDO_DIF><CUOTAS>67</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSTRUCCION DE INSTALACION INTERNA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>4,633</CAPITAL><INTERES>23,130</INTERES><TOTAL></TOTAL><SALDO_DIF>983,328</SALDO_DIF><CUOTAS>67</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CERTIFICACIÓN DE INSTALACIÓN PREVIA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>324</CAPITAL><INTERES>1,620</INTERES><TOTAL></TOTAL><SALDO_DIF>68,886</SALDO_DIF><CUOTAS>67</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>SUBSIDIO LEY 142/94(Hasta 20M3 45.26% Cons.)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>-2,218</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>IVA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>631</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>INTERES DE MORA(Tasa 2.315%)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES>113</INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>33</ETIQUETA><DESC_CONCEP>Total Servicio:</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>10,573</CAPITAL><INTERES>36,361</INTERES><TOTAL>46,934</TOTAL><SALDO_DIF>1,541,023</SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_RANGOS>
<LIM_INFERIOR>0</LIM_INFERIOR><LIM_SUPERIOR>20</LIM_SUPERIOR><VALOR_UNIDAD>1633.23</VALOR_UNIDAD><CONSUMO>3</CONSUMO><VAL_CONSUMO>4,899.69</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>21</LIM_INFERIOR><LIM_SUPERIOR>90000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>90001</LIM_INFERIOR><LIM_SUPERIOR>180000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>180001</LIM_INFERIOR><LIM_SUPERIOR>280000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>280001</LIM_INFERIOR><LIM_SUPERIOR>1000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>1000001</LIM_INFERIOR><LIM_SUPERIOR>5000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>5000001</LIM_INFERIOR><LIM_SUPERIOR>MAS</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_COMPCOST>
<COMPCOST>Gm = $777 Tm = $214 Dm = $201.61 Cv = $0 Cc = $0 Cm = $3610.6</COMPCOST><VALORESREF>DES(h)=0 IPLI=100% IO=100% IRST=NO APLICA</VALORESREF><VALCALC>DES(h)=0 COMPENSACION($)=0</VALCALC>
</LDC_COMPCOST>
<LDC_CUPON>
<COD_BAR>(415)7707232377896(8020)0124354608(3900)0000092884(96)20260818</COD_BAR>
</LDC_CUPON>
<EXTRA_BARCODE_>
<CODE>415770723237789680200124354608È39000000092884È9620160818</CODE>
<IMAGE></IMAGE>
</EXTRA_BARCODE_>
</LDC_FACTURA>
';	MERGE INTO OPEN.ED_DOCUMENT A USING
    (SELECT 2016690615 as DOCUCODI, 66 as DOCUTIDO, 68735 as DOCUPEFA, TO_DATE('05/08/2016 08:20:09 p.m.','DD/MM/YYYY HH:MI:SS A.M.') as DOCUFERE, sbFactura3 DOCUDOCU
      FROM DUAL) B
    ON (A.DOCUCODI = B.DOCUCODI and A.DOCUTIDO = B.DOCUTIDO)
    WHEN NOT MATCHED THEN  INSERT (
      DOCUCODI, DOCUTIDO, DOCUPEFA, DOCUFERE, DOCUDOCU)
     VALUES (
      B.DOCUCODI, B.DOCUTIDO, B.DOCUPEFA, B.DOCUFERE, B.DOCUDOCU)
    WHEN MATCHED THEN
     UPDATE SET 
      A.DOCUPEFA = B.DOCUPEFA,
      A.DOCUFERE = B.DOCUFERE,
      A.DOCUDOCU = B.DOCUDOCU;
sbFactura4 := '<LDC_FACTURA>
<LDC_DATOS_CLIENTE><FACTURA>2014727335</FACTURA><FECH_FACT>07/JUN/2016</FECH_FACT><MES_FACT>MAY-2016</MES_FACT><PERIODO_FACT>MAYO       2016</PERIODO_FACT><PAGO_HASTA>20/06/2016</PAGO_HASTA><DIAS_CONSUMO>30</DIAS_CONSUMO><CONTRATO>66428471</CONTRATO><CUPON>122388774</CUPON><NOMBRE>DIANA PATRICIA QUINTANA</NOMBRE><DIRECCION_COBRO>CL 49 KR 10C - 17 PISO 1 APTO 2</DIRECCION_COBRO><LOCALIDAD>SOLEDAD - ATL</LOCALIDAD><CATEGORIA>RESIDENCIAL</CATEGORIA><ESTRATO>ESTRATO 2</ESTRATO><CICLO>1406</CICLO><RUTA>14065811150537400</RUTA><MESES_DEUDA>2</MESES_DEUDA><NUM_CONTROL>2909320331</NUM_CONTROL><PERIODO_CONSUMO>30/ABR - 29/MAY</PERIODO_CONSUMO><SALDO_FAVOR>0</SALDO_FAVOR><FECHA_SUSPENSION>21/06/2016</FECHA_SUSPENSION><VALOR_RECL>0</VALOR_RECL><TOTAL_FACTURA>94,126</TOTAL_FACTURA><PAGO_SIN_RECARGO>20/06/2016</PAGO_SIN_RECARGO><CUPO_BRILLA>0</CUPO_BRILLA>
</LDC_DATOS_CLIENTE>
<LDC_DATOS_LECTURA>
<NUM_MEDIDOR>K-3207284-15</NUM_MEDIDOR><LECTURA_ANTERIOR>6</LECTURA_ANTERIOR><LECTURA_ACTUAL>9</LECTURA_ACTUAL><OBS_LECTURA></OBS_LECTURA>
</LDC_DATOS_LECTURA>
<LDC_DATOS_CONSUMO>
<CONS_CORREG>3</CONS_CORREG><FACTOR_CORRECCION> 0.9910</FACTOR_CORRECCION><CONSUMO_MES_1>3</CONSUMO_MES_1><FECHA_CONS_MES_1>ABR-16</FECHA_CONS_MES_1><CONSUMO_MES_2>3</CONSUMO_MES_2><FECHA_CONS_MES_2>MAR-16</FECHA_CONS_MES_2><CONSUMO_MES_3>0</CONSUMO_MES_3><FECHA_CONS_MES_3>FEB-16</FECHA_CONS_MES_3><CONSUMO_MES_4>0</CONSUMO_MES_4><FECHA_CONS_MES_4>ENE-16</FECHA_CONS_MES_4><CONSUMO_MES_5>0</CONSUMO_MES_5><FECHA_CONS_MES_5>DIC-15</FECHA_CONS_MES_5><CONSUMO_MES_6>0</CONSUMO_MES_6><FECHA_CONS_MES_6>NOV-15</FECHA_CONS_MES_6><CONSUMO_PROMEDIO>1</CONSUMO_PROMEDIO><TEMPERATURA>79.2886</TEMPERATURA><PRESION>.33</PRESION><EQUIVAL_KWH>3 M3 Equivalen a 31.11kwh</EQUIVAL_KWH><CALCCONS>LEC.MEDIDOR</CALCCONS>
</LDC_DATOS_CONSUMO>
<LDC_DATOS_REVISION>
<TIPO_NOTI>0</TIPO_NOTI><MENS_NOTI>La Revision Periodica debe Realizarse con Organismos de Inspeccion Acreditados.</MENS_NOTI><FECH_MAXIMA></FECH_MAXIMA><FECH_SUSP></FECH_SUSP>
</LDC_DATOS_REVISION>
<LDC_TOTALES>
<TOTAL_1></TOTAL_1>
</LDC_TOTALES>
<LDC_CARGOS>
<ETIQUETA>31</ETIQUETA><DESC_CONCEP>SERV.GAS (Serv.Susc.51129253)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>Saldo Anterior</DESC_CONCEP><SALDO_ANT>46,198</SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSUMO DE GAS NATURAL</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>4,552</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>52</CAPITAL><INTERES>385</INTERES><TOTAL></TOTAL><SALDO_DIF>15,891</SALDO_DIF><CUOTAS>69</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA BIENES Y SERVICIOS</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>37</CAPITAL><INTERES>270</INTERES><TOTAL></TOTAL><SALDO_DIF>11,130</SALDO_DIF><CUOTAS>69</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CARGO POR CONEXIÓN</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>1,519</CAPITAL><INTERES>11,304</INTERES><TOTAL></TOTAL><SALDO_DIF>466,692</SALDO_DIF><CUOTAS>69</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSTRUCCION DE INSTALACION INTERNA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>3,233</CAPITAL><INTERES>24,056</INTERES><TOTAL></TOTAL><SALDO_DIF>993,191</SALDO_DIF><CUOTAS>69</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CERTIFICACIÓN DE INSTALACIÓN PREVIA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>226</CAPITAL><INTERES>1,685</INTERES><TOTAL></TOTAL><SALDO_DIF>69,576</SALDO_DIF><CUOTAS>69</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>COBRO DUPLICADO FACTURA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>1,400</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>SUBSIDIO LEY 142/94(Hasta 20M3 41.66% Cons.)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>-1,896</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>IVA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>882</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>INTERES DE MORA(Tasa 2.239%)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES>223</INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>33</ETIQUETA><DESC_CONCEP>Total Servicio:</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>10,005</CAPITAL><INTERES>37,923</INTERES><TOTAL>47,928</TOTAL><SALDO_DIF>1,556,480</SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_RANGOS>
<LIM_INFERIOR>0</LIM_INFERIOR><LIM_SUPERIOR>20</LIM_SUPERIOR><VALOR_UNIDAD>1517.39</VALOR_UNIDAD><CONSUMO>3</CONSUMO><VAL_CONSUMO>4,552.17</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>21</LIM_INFERIOR><LIM_SUPERIOR>90000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>90001</LIM_INFERIOR><LIM_SUPERIOR>180000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>180001</LIM_INFERIOR><LIM_SUPERIOR>280000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>280001</LIM_INFERIOR><LIM_SUPERIOR>1000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>1000001</LIM_INFERIOR><LIM_SUPERIOR>5000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>5000001</LIM_INFERIOR><LIM_SUPERIOR>MAS</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_COMPCOST>
<COMPCOST>Gm = $689 Tm = $198 Dm = $199.66 Cv = $0 Cc = $0 Cm = $3584.04</COMPCOST><VALORESREF>DES(h)=0 IPLI=100% IO=100% IRST=NO APLICA</VALORESREF><VALCALC>DES(h)=0 COMPENSACION($)=0</VALCALC>
</LDC_COMPCOST>
<LDC_CUPON>
<COD_BAR>(415)7707232377896(8020)0122388774(3900)0000094126(96)20260620</COD_BAR>
</LDC_CUPON>
<EXTRA_BARCODE_>
<CODE>415770723237789680200122388774È39000000094126È9620160620</CODE>
<IMAGE></IMAGE>
</EXTRA_BARCODE_>
</LDC_FACTURA>
';	MERGE INTO OPEN.ED_DOCUMENT A USING
    (SELECT 2014727335 as DOCUCODI, 66 as DOCUTIDO, 67916 as DOCUPEFA, TO_DATE('08/06/2016 12:08:46 a.m.','DD/MM/YYYY HH:MI:SS A.M.') as DOCUFERE, sbFactura4 DOCUDOCU
      FROM DUAL) B
    ON (A.DOCUCODI = B.DOCUCODI and A.DOCUTIDO = B.DOCUTIDO)
    WHEN NOT MATCHED THEN  INSERT (
      DOCUCODI, DOCUTIDO, DOCUPEFA, DOCUFERE, DOCUDOCU)
     VALUES (
      B.DOCUCODI, B.DOCUTIDO, B.DOCUPEFA, B.DOCUFERE, B.DOCUDOCU)
    WHEN MATCHED THEN
     UPDATE SET 
      A.DOCUPEFA = B.DOCUPEFA,
      A.DOCUFERE = B.DOCUFERE,
      A.DOCUDOCU = B.DOCUDOCU;
sbFactura5 := '<LDC_FACTURA>
<LDC_DATOS_CLIENTE><FACTURA>2015700916</FACTURA><FECH_FACT>06/JUL/2016</FECH_FACT><MES_FACT>JUN-2016</MES_FACT><PERIODO_FACT>JUNIO      2016</PERIODO_FACT><PAGO_HASTA>22/07/2016</PAGO_HASTA><DIAS_CONSUMO>31</DIAS_CONSUMO><CONTRATO>66428471</CONTRATO><CUPON>123355719</CUPON><NOMBRE>DIANA PATRICIA QUINTANA</NOMBRE><DIRECCION_COBRO>CL 49 KR 10C - 17 PISO 1 APTO 2</DIRECCION_COBRO><LOCALIDAD>SOLEDAD - ATL</LOCALIDAD><CATEGORIA>RESIDENCIAL</CATEGORIA><ESTRATO>ESTRATO 2</ESTRATO><CICLO>1406</CICLO><RUTA>14065811150537400</RUTA><MESES_DEUDA>1</MESES_DEUDA><NUM_CONTROL>2910614278</NUM_CONTROL><PERIODO_CONSUMO>30/MAY - 29/JUN</PERIODO_CONSUMO><SALDO_FAVOR>0</SALDO_FAVOR><FECHA_SUSPENSION></FECHA_SUSPENSION><VALOR_RECL>0</VALOR_RECL><TOTAL_FACTURA>45,950</TOTAL_FACTURA><PAGO_SIN_RECARGO>22/07/2016</PAGO_SIN_RECARGO><CUPO_BRILLA>0</CUPO_BRILLA>
</LDC_DATOS_CLIENTE>
<LDC_DATOS_LECTURA>
<NUM_MEDIDOR>K-3207284-15</NUM_MEDIDOR><LECTURA_ANTERIOR>9</LECTURA_ANTERIOR><LECTURA_ACTUAL>11</LECTURA_ACTUAL><OBS_LECTURA></OBS_LECTURA>
</LDC_DATOS_LECTURA>
<LDC_DATOS_CONSUMO>
<CONS_CORREG>2</CONS_CORREG><FACTOR_CORRECCION> 0.9892</FACTOR_CORRECCION><CONSUMO_MES_1>3</CONSUMO_MES_1><FECHA_CONS_MES_1>MAY-16</FECHA_CONS_MES_1><CONSUMO_MES_2>3</CONSUMO_MES_2><FECHA_CONS_MES_2>ABR-16</FECHA_CONS_MES_2><CONSUMO_MES_3>3</CONSUMO_MES_3><FECHA_CONS_MES_3>MAR-16</FECHA_CONS_MES_3><CONSUMO_MES_4>0</CONSUMO_MES_4><FECHA_CONS_MES_4>FEB-16</FECHA_CONS_MES_4><CONSUMO_MES_5>0</CONSUMO_MES_5><FECHA_CONS_MES_5>ENE-16</FECHA_CONS_MES_5><CONSUMO_MES_6>0</CONSUMO_MES_6><FECHA_CONS_MES_6>DIC-15</FECHA_CONS_MES_6><CONSUMO_PROMEDIO>2</CONSUMO_PROMEDIO><TEMPERATURA>78.5308</TEMPERATURA><PRESION>.33</PRESION><EQUIVAL_KWH>2 M3 Equivalen a 20.74kwh</EQUIVAL_KWH><CALCCONS>LEC.MEDIDOR</CALCCONS>
</LDC_DATOS_CONSUMO>
<LDC_DATOS_REVISION>
<TIPO_NOTI>0</TIPO_NOTI><MENS_NOTI>La Revision Periodica debe Realizarse con Organismos de Inspeccion Acreditados.</MENS_NOTI><FECH_MAXIMA></FECH_MAXIMA><FECH_SUSP></FECH_SUSP>
</LDC_DATOS_REVISION>
<LDC_TOTALES>
<TOTAL_1></TOTAL_1>
</LDC_TOTALES>
<LDC_CARGOS>
<ETIQUETA>31</ETIQUETA><DESC_CONCEP>SERV.GAS (Serv.Susc.51129253)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSUMO DE GAS NATURAL</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>3,417</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>84</CAPITAL><INTERES>360</INTERES><TOTAL></TOTAL><SALDO_DIF>15,807</SALDO_DIF><CUOTAS>68</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA BIENES Y SERVICIOS</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>59</CAPITAL><INTERES>252</INTERES><TOTAL></TOTAL><SALDO_DIF>11,071</SALDO_DIF><CUOTAS>68</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CARGO POR CONEXIÓN</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>2,458</CAPITAL><INTERES>10,562</INTERES><TOTAL></TOTAL><SALDO_DIF>464,234</SALDO_DIF><CUOTAS>68</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSTRUCCION DE INSTALACION INTERNA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>5,230</CAPITAL><INTERES>22,478</INTERES><TOTAL></TOTAL><SALDO_DIF>987,961</SALDO_DIF><CUOTAS>68</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CERTIFICACIÓN DE INSTALACIÓN PREVIA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>366</CAPITAL><INTERES>1,575</INTERES><TOTAL></TOTAL><SALDO_DIF>69,210</SALDO_DIF><CUOTAS>68</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>SUBSIDIO LEY 142/94(Hasta 20M3 47.92% Cons.)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>-1,637</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>IVA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>614</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>INTERES DE MORA(Tasa 2.2634%)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES>132</INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>33</ETIQUETA><DESC_CONCEP>Total Servicio:</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>10,591</CAPITAL><INTERES>35,359</INTERES><TOTAL>45,950</TOTAL><SALDO_DIF>1,548,283</SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_RANGOS>
<LIM_INFERIOR>0</LIM_INFERIOR><LIM_SUPERIOR>20</LIM_SUPERIOR><VALOR_UNIDAD>1708.34</VALOR_UNIDAD><CONSUMO>2</CONSUMO><VAL_CONSUMO>3,416.68</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>21</LIM_INFERIOR><LIM_SUPERIOR>90000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>90001</LIM_INFERIOR><LIM_SUPERIOR>180000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>180001</LIM_INFERIOR><LIM_SUPERIOR>280000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>280001</LIM_INFERIOR><LIM_SUPERIOR>1000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>1000001</LIM_INFERIOR><LIM_SUPERIOR>5000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>5000001</LIM_INFERIOR><LIM_SUPERIOR>MAS</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_COMPCOST>
<COMPCOST>Gm = $838 Tm = $227 Dm = $200.64 Cv = $0 Cc = $0 Cm = $3597.83</COMPCOST><VALORESREF>DES(h)=0 IPLI=100% IO=100% IRST=NO APLICA</VALORESREF><VALCALC>DES(h)=0 COMPENSACION($)=0</VALCALC>
</LDC_COMPCOST>
<LDC_CUPON>
<COD_BAR>(415)7707232377896(8020)0123355719(3900)0000045950(96)20260722</COD_BAR>
</LDC_CUPON>
<EXTRA_BARCODE_>
<CODE>415770723237789680200123355719È39000000045950È9620160722</CODE>
<IMAGE></IMAGE>
</EXTRA_BARCODE_>
</LDC_FACTURA>
';	MERGE INTO OPEN.ED_DOCUMENT A USING
    (SELECT 2015700916 as DOCUCODI, 66 as DOCUTIDO, 68406 as DOCUPEFA, TO_DATE('06/07/2016 11:32:16 p.m.','DD/MM/YYYY HH:MI:SS A.M.') as DOCUFERE, sbFactura5 DOCUDOCU
      FROM DUAL) B
    ON (A.DOCUCODI = B.DOCUCODI and A.DOCUTIDO = B.DOCUTIDO)
    WHEN NOT MATCHED THEN  INSERT (
      DOCUCODI, DOCUTIDO, DOCUPEFA, DOCUFERE, DOCUDOCU)
     VALUES (
      B.DOCUCODI, B.DOCUTIDO, B.DOCUPEFA, B.DOCUFERE, B.DOCUDOCU)
    WHEN MATCHED THEN
     UPDATE SET 
      A.DOCUPEFA = B.DOCUPEFA,
      A.DOCUFERE = B.DOCUFERE,
      A.DOCUDOCU = B.DOCUDOCU;

    COMMIT;
    dbms_output.put_line('Fin OSF-4160');
END;
/

select to_char(sysdate,'yyyy-mm-dd hh:mi:ss p.m.') fecha_fin from dual;
set serveroutput off
quit
/