column dt new_value vdt
column db new_value vdb
select to_char(sysdate,'yyyymmdd_hh24miss') dt, sys_context('userenv','db_name') db from dual;
set serveroutput on size unlimited
execute dbms_application_info.set_action('APLICANDO DATAFIX');
select to_char(sysdate,'yyyy-mm-dd hh:mi:ss p.m.') fecha_inicio from dual;

DECLARE
sbFactura1 CLOB;

BEGIN
    dbms_output.put_line('Inicia OSF-4160_2');
sbFactura1 := '<LDC_FACTURA>
<LDC_DATOS_CLIENTE><FACTURA>2018684005</FACTURA><FECH_FACT>07/OCT/2016</FECH_FACT><MES_FACT>SEP-2016</MES_FACT><PERIODO_FACT>SEPTIEMBRE 2016</PERIODO_FACT><PAGO_HASTA>21/10/2016</PAGO_HASTA><DIAS_CONSUMO>31</DIAS_CONSUMO><CONTRATO>66428471</CONTRATO><CUPON>126326198</CUPON><NOMBRE>DIANA PATRICIA QUINTANA</NOMBRE><DIRECCION_COBRO>CL 49 KR 10C - 17 PISO 1 APTO 2</DIRECCION_COBRO><LOCALIDAD>SOLEDAD - ATL</LOCALIDAD><CATEGORIA>RESIDENCIAL</CATEGORIA><ESTRATO>ESTRATO 2</ESTRATO><CICLO>1406</CICLO><RUTA>14065811150537400</RUTA><MESES_DEUDA>2</MESES_DEUDA><NUM_CONTROL>2914577147</NUM_CONTROL><PERIODO_CONSUMO>30/AGO - 29/SEP</PERIODO_CONSUMO><SALDO_FAVOR>0</SALDO_FAVOR><FECHA_SUSPENSION>22/10/2016</FECHA_SUSPENSION><VALOR_RECL>0</VALOR_RECL><TOTAL_FACTURA>257,336</TOTAL_FACTURA><PAGO_SIN_RECARGO>21/10/2016</PAGO_SIN_RECARGO><CUPO_BRILLA>0</CUPO_BRILLA>
</LDC_DATOS_CLIENTE>
<LDC_DATOS_LECTURA>
<NUM_MEDIDOR>K-3207284-15</NUM_MEDIDOR><LECTURA_ANTERIOR>138.72</LECTURA_ANTERIOR><LECTURA_ACTUAL>188</LECTURA_ACTUAL><OBS_LECTURA></OBS_LECTURA>
</LDC_DATOS_LECTURA>
<LDC_DATOS_CONSUMO>
<CONS_CORREG>49</CONS_CORREG><FACTOR_CORRECCION> 0.9910</FACTOR_CORRECCION><CONSUMO_MES_1>64</CONSUMO_MES_1><FECHA_CONS_MES_1>AGO-16</FECHA_CONS_MES_1><CONSUMO_MES_2>62</CONSUMO_MES_2><FECHA_CONS_MES_2>JUL-16</FECHA_CONS_MES_2><CONSUMO_MES_3>2</CONSUMO_MES_3><FECHA_CONS_MES_3>JUN-16</FECHA_CONS_MES_3><CONSUMO_MES_4>3</CONSUMO_MES_4><FECHA_CONS_MES_4>MAY-16</FECHA_CONS_MES_4><CONSUMO_MES_5>3</CONSUMO_MES_5><FECHA_CONS_MES_5>ABR-16</FECHA_CONS_MES_5><CONSUMO_MES_6>3</CONSUMO_MES_6><FECHA_CONS_MES_6>MAR-16</FECHA_CONS_MES_6><CONSUMO_PROMEDIO>23</CONSUMO_PROMEDIO><TEMPERATURA>77.79</TEMPERATURA><PRESION>.33</PRESION><EQUIVAL_KWH>49 M3 Equivalen a 508.13kwh</EQUIVAL_KWH><CALCCONS>LEC.MEDIDOR</CALCCONS>
</LDC_DATOS_CONSUMO>
<LDC_DATOS_REVISION>
<TIPO_NOTI>0</TIPO_NOTI><MENS_NOTI>La Revision Periodica debe Realizarse con Organismos de Inspeccion Acreditados.</MENS_NOTI><FECH_MAXIMA></FECH_MAXIMA><FECH_SUSP></FECH_SUSP>
</LDC_DATOS_REVISION>
<LDC_TOTALES>
<TOTAL_1></TOTAL_1>
</LDC_TOTALES>
<LDC_CARGOS>
<ETIQUETA></ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSTRUCCION DE INSTALACION INTERNA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>3,995</CAPITAL><INTERES>24,349</INTERES><TOTAL></TOTAL><SALDO_DIF>976,071</SALDO_DIF><CUOTAS>65</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CERTIFICACIÃ“N DE INSTALACIÃ“N PREVIA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>280</CAPITAL><INTERES>1,706</INTERES><TOTAL></TOTAL><SALDO_DIF>68,378</SALDO_DIF><CUOTAS>65</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>IVA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>670</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>33</ETIQUETA><DESC_CONCEP>Total Servicio:</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>67,855</CAPITAL><INTERES>40,562</INTERES><TOTAL>108,417</TOTAL><SALDO_DIF>1,529,649</SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>IVA COBRO DUPLICADO</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>448</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CARGO POR CONEXIÃ“N</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>1,877</CAPITAL><INTERES>11,442</INTERES><TOTAL></TOTAL><SALDO_DIF>458,647</SALDO_DIF><CUOTAS>65</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>COBRO DUPLICADO FACTURA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>2,800</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>31</ETIQUETA><DESC_CONCEP>SERV.GAS (Serv.Susc.51129253)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>CONSUMO DE GAS NATURAL</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>72,743</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>SUBSIDIO LEY 142/94(Hasta 20M3 45.68% Cons.)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>-15,067</CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>INTERES DE MORA(Tasa 2.377%)</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES>2,402</INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>64</CAPITAL><INTERES>390</INTERES><TOTAL></TOTAL><SALDO_DIF>15,616</SALDO_DIF><CUOTAS>65</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>Saldo Anterior</DESC_CONCEP><SALDO_ANT>148,919</SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>32</ETIQUETA><DESC_CONCEP>FINANCIACION GRAVADA BIENES Y SERVICIOS</DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL>45</CAPITAL><INTERES>273</INTERES><TOTAL></TOTAL><SALDO_DIF>10,937</SALDO_DIF><CUOTAS>65</CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_CARGOS>
<ETIQUETA>34</ETIQUETA><DESC_CONCEP></DESC_CONCEP><SALDO_ANT></SALDO_ANT><CAPITAL></CAPITAL><INTERES></INTERES><TOTAL></TOTAL><SALDO_DIF></SALDO_DIF><CUOTAS></CUOTAS>
</LDC_CARGOS>
<LDC_RANGOS>
<LIM_INFERIOR>0</LIM_INFERIOR><LIM_SUPERIOR>20</LIM_SUPERIOR><VALOR_UNIDAD>1649.22</VALOR_UNIDAD><CONSUMO>20</CONSUMO><VAL_CONSUMO>32,984.40</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>21</LIM_INFERIOR><LIM_SUPERIOR>90000</LIM_SUPERIOR><VALOR_UNIDAD>1371</VALOR_UNIDAD><CONSUMO>29</CONSUMO><VAL_CONSUMO>39,759.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>90001</LIM_INFERIOR><LIM_SUPERIOR>180000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>180001</LIM_INFERIOR><LIM_SUPERIOR>280000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>280001</LIM_INFERIOR><LIM_SUPERIOR>1000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>1000001</LIM_INFERIOR><LIM_SUPERIOR>5000000</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_RANGOS>
<LIM_INFERIOR>5000001</LIM_INFERIOR><LIM_SUPERIOR>MAS</LIM_SUPERIOR><VALOR_UNIDAD>0</VALOR_UNIDAD><CONSUMO>0</CONSUMO><VAL_CONSUMO>0.00</VAL_CONSUMO>
</LDC_RANGOS>
<LDC_COMPCOST>
<COMPCOST>Gm = $766 Tm = $244 Dm = $198.96 Cv = $0 Cc = $0 Cm = $3608.73</COMPCOST><VALORESREF>DES(h)=0 IPLI=100% IO=100% IRST=NO APLICA</VALORESREF><VALCALC>DES(h)=0 COMPENSACION($)=0</VALCALC>
</LDC_COMPCOST>
<LDC_CUPON>
<COD_BAR>(415)7707232377896(8020)0126326198(3900)0000257336(96)20261021</COD_BAR>
</LDC_CUPON>
<EXTRA_BARCODE_>
<CODE>415770723237789680200126326198Ãˆ39000000257336Ãˆ9620161021</CODE>
<IMAGE></IMAGE>
</EXTRA_BARCODE_>
</LDC_FACTURA>
';	MERGE INTO OPEN.ED_DOCUMENT A USING
    (SELECT 2018684005 as DOCUCODI, 66 as DOCUTIDO, 71244 as DOCUPEFA, 
    TO_DATE('07/10/2016 08:51:21 p.m.','DD/MM/YYYY HH:MI:SS A.M.') as DOCUFERE, sbFactura1 DOCUDOCU
      FROM DUAL) B
    ON (A.DOCUCODI = B.DOCUCODI and A.DOCUTIDO = B.DOCUTIDO)
    WHEN NOT MATCHED THEN  INSERT (
      DOCUCODI, DOCUTIDO, DOCUPEFA, DOCUFERE, DOCUDOCU)
     VALUES (
      B.DOCUCODI, B.DOCUTIDO, B.DOCUPEFA, B.DOCUFERE, B.DOCUDOCU)
    WHEN MATCHED THEN
     UPDATE SET 
      A.DOCUPEFA = B.DOCUPEFA,
      A.DOCUFERE = B.DOCUFERE,
      A.DOCUDOCU = B.DOCUDOCU;

    COMMIT;
    dbms_output.put_line('Fin OSF-4160_2');
END;
/

select to_char(sysdate,'yyyy-mm-dd hh:mi:ss p.m.') fecha_fin from dual;
set serveroutput off
quit
/