
declare
 nuConta  NUMBER;
 
 CURSOR cuExiste IS
  SELECT COUNT(1)
  FROM SA_TAB
  WHERE APLICA_EXECUTABLE = 'CTCCO' AND PROCESS_NAME = 'PBCOEM'; 
  
BEGIN

OPEN cuExiste; 
FETCH cuExiste INTO nuConta; 
CLOSE cuExiste; 

IF nuConta = 0 THEN	

INSERT INTO SA_TAB VALUES(SEQ_SA_TAB.NEXTVAL,'CT_FW_CONTRATISTA','PBCOEM','CTCCO',NULL,NULL,0,NULL,NULL); 

END IF;

COMMIT;

END;
/