MERGE INTO OPEN.LD_PARAMETER A USING
 (SELECT
  'MAR_PROD_FNUASIGNAAUTORECOREV' as "PARAMETER_ID",
  NULL as "NUMERIC_VALUE",
  '101,103' as "VALUE_CHAIN",
  'MARCA PRODUCTO VALIDADO EN EL SERVICIO FNUASIGNAAUTORECOREV PARA AUTORECONECTADOS OSF-2443' as "DESCRIPTION"
  FROM DUAL) B
ON (A.PARAMETER_ID = B.PARAMETER_ID)
WHEN NOT MATCHED THEN 
INSERT (
  PARAMETER_ID, NUMERIC_VALUE, VALUE_CHAIN, DESCRIPTION)
VALUES (
  B.PARAMETER_ID, B.NUMERIC_VALUE, B.VALUE_CHAIN, B.DESCRIPTION)
WHEN MATCHED THEN
UPDATE SET 
  A.NUMERIC_VALUE = B.NUMERIC_VALUE,
  A.VALUE_CHAIN = B.VALUE_CHAIN,
  A.DESCRIPTION = B.DESCRIPTION;
/
COMMIT;
/