CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_LDC_COTIZ_COMERCIAL AFTER INSERT OR UPDATE OR DELETE ON LDC_COTIZACION_COMERCIAL
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

ID_COT_COMERCIAL NUMBER(15);
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  ID_COT_COMERCIAL := :new.ID_COT_COMERCIAL;
  OPERATION := 'I';
ELSIF UPDATING THEN
  ID_COT_COMERCIAL := :new.ID_COT_COMERCIAL;
  OPERATION := 'U';
ELSE
  ID_COT_COMERCIAL := :old.ID_COT_COMERCIAL;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_LDC_COTIZACION_COMERCIAL (
  ID_COT_COMERCIAL,
  OPERATION
)
VALUES (
  ID_COT_COMERCIAL,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20000,
                            'Error en TRG_BI_LDC_COTIZ_COMERCIAL por -->' || sqlcode ||
                            chr(13) || sqlerrm);
END;
/
