GRANT execute on PERSONALIZACIONES.LDC_Email to ROLE_DESARROLLOOSF;
/
GRANT execute on PERSONALIZACIONES.LDC_Email to PERSONALIZACIONES;
/
GRANT execute on PERSONALIZACIONES.LDC_Email to SYSTEM_OBJ_PRIVS_ROLE;
/
GRANT execute on PERSONALIZACIONES.LDC_PRNOT_CXC_SIN_LEGALIZAR to ROLE_DESARROLLOOSF;
/
GRANT execute on PERSONALIZACIONES.LDC_PRNOT_CXC_SIN_LEGALIZAR to PERSONALIZACIONES;
/
GRANT execute on PERSONALIZACIONES.LDC_PRNOT_CXC_SIN_LEGALIZAR to SYSTEM_OBJ_PRIVS_ROLE;
/
GRANT execute on OPEN.LDC_ENVIAMAIL to ROLE_DESARROLLOOSF;
/
GRANT execute on OPEN.LDC_ENVIAMAIL to PERSONALIZACIONES;
/
GRANT SELECT, INSERT, DELETE, UPDATE ON PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG to ROLE_DESARROLLOOSF;
/
GRANT SELECT, INSERT, DELETE, UPDATE ON PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG to PERSONALIZACIONES;
/
GRANT SELECT, INSERT, DELETE, UPDATE ON PERSONALIZACIONES.LDC_LOG_CXC_SIN_LEG to SYSTEM_OBJ_PRIVS_ROLE;
/
