CREATE OR REPLACE PACKAGE DAGE_ITEMS_DOCUMENTO IS
   CURSOR CURECORD( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE ) IS
SELECT GE_items_documento.*,GE_items_documento.rowid
		FROM GE_items_documento
		WHERE 
		    Id_Items_Documento = inuId_Items_Documento;
   CURSOR CURECORDBYROWID( IRIROWID IN VARCHAR2 ) IS
SELECT GE_items_documento.*,GE_items_documento.rowid
		FROM GE_items_documento
		WHERE 
			rowId = irirowid;
   SUBTYPE STYGE_ITEMS_DOCUMENTO IS CURECORD%ROWTYPE;
   TYPE TYREFCURSOR IS REF CURSOR;
   TYPE TYTBGE_ITEMS_DOCUMENTO IS TABLE OF STYGE_ITEMS_DOCUMENTO INDEX BY BINARY_INTEGER;
   TYPE TYRFRECORDS IS REF CURSOR
    RETURN STYGE_ITEMS_DOCUMENTO;
   TYPE TYTBID_ITEMS_DOCUMENTO IS TABLE OF GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBDOCUMENT_TYPE_ID IS TABLE OF GE_ITEMS_DOCUMENTO.DOCUMENT_TYPE_ID%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBDOCUMENTO_EXTERNO IS TABLE OF GE_ITEMS_DOCUMENTO.DOCUMENTO_EXTERNO%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBFECHA IS TABLE OF GE_ITEMS_DOCUMENTO.FECHA%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBESTADO IS TABLE OF GE_ITEMS_DOCUMENTO.ESTADO%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBOPERATING_UNIT_ID IS TABLE OF GE_ITEMS_DOCUMENTO.OPERATING_UNIT_ID%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBDESTINO_OPER_UNI_ID IS TABLE OF GE_ITEMS_DOCUMENTO.DESTINO_OPER_UNI_ID%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBTERMINAL_ID IS TABLE OF GE_ITEMS_DOCUMENTO.TERMINAL_ID%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBUSER_ID IS TABLE OF GE_ITEMS_DOCUMENTO.USER_ID%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBCOMENTARIO IS TABLE OF GE_ITEMS_DOCUMENTO.COMENTARIO%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBCAUSAL_ID IS TABLE OF GE_ITEMS_DOCUMENTO.CAUSAL_ID%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBDELIVERY_DATE IS TABLE OF GE_ITEMS_DOCUMENTO.DELIVERY_DATE%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBPACKAGE_ID IS TABLE OF GE_ITEMS_DOCUMENTO.PACKAGE_ID%TYPE INDEX BY BINARY_INTEGER;
   TYPE TYTBROWID IS TABLE OF ROWID INDEX BY BINARY_INTEGER;
   TYPE TYRCGE_ITEMS_DOCUMENTO IS RECORD
    (
      ID_ITEMS_DOCUMENTO TYTBID_ITEMS_DOCUMENTO,
      DOCUMENT_TYPE_ID TYTBDOCUMENT_TYPE_ID,
      DOCUMENTO_EXTERNO TYTBDOCUMENTO_EXTERNO,
      FECHA TYTBFECHA,
      ESTADO TYTBESTADO,
      OPERATING_UNIT_ID TYTBOPERATING_UNIT_ID,
      DESTINO_OPER_UNI_ID TYTBDESTINO_OPER_UNI_ID,
      TERMINAL_ID TYTBTERMINAL_ID,
      USER_ID TYTBUSER_ID,
      COMENTARIO TYTBCOMENTARIO,
      CAUSAL_ID TYTBCAUSAL_ID,
      DELIVERY_DATE TYTBDELIVERY_DATE,
      PACKAGE_ID TYTBPACKAGE_ID,
      ROW_ID TYTBROWID
    );
   FUNCTION FSBVERSION
    RETURN VARCHAR2;
   FUNCTION FSBGETMESSAGEDESCRIPTION
    RETURN VARCHAR2;
   PROCEDURE CLEARMEMORY;
   FUNCTION FBLEXIST( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE )
    RETURN BOOLEAN;
   PROCEDURE ACCKEY( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE );
   PROCEDURE ACCKEYBYROWID( IRIROWID IN ROWID );
   PROCEDURE VALDUPLICATE( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE );
   PROCEDURE GETRECORD( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, ORCRECORD OUT NOCOPY STYGE_ITEMS_DOCUMENTO );
   FUNCTION FRCGETRCDATA( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE )
    RETURN STYGE_ITEMS_DOCUMENTO;
   FUNCTION FRCGETRCDATA
    RETURN STYGE_ITEMS_DOCUMENTO;
   FUNCTION FRCGETRECORD( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE )
    RETURN STYGE_ITEMS_DOCUMENTO;
   PROCEDURE GETRECORDS( ISBQUERY IN VARCHAR2, OTBRESULT OUT NOCOPY TYTBGE_ITEMS_DOCUMENTO );
   FUNCTION FRFGETRECORDS( ISBCRITERIA IN VARCHAR2 := NULL, IBLLOCK IN BOOLEAN := FALSE )
    RETURN TYREFCURSOR;
   PROCEDURE INSRECORD( IRCGE_ITEMS_DOCUMENTO IN STYGE_ITEMS_DOCUMENTO );
   PROCEDURE INSRECORD( IRCGE_ITEMS_DOCUMENTO IN STYGE_ITEMS_DOCUMENTO, ORIROWID OUT VARCHAR2 );
   PROCEDURE INSRECORDS( IOTBGE_ITEMS_DOCUMENTO IN OUT NOCOPY TYTBGE_ITEMS_DOCUMENTO );
   PROCEDURE DELRECORD( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INULOCK IN NUMBER := 1 );
   PROCEDURE DELBYROWID( IRIROWID IN ROWID, INULOCK IN NUMBER := 1 );
   PROCEDURE DELRECORDS( IOTBGE_ITEMS_DOCUMENTO IN OUT NOCOPY TYTBGE_ITEMS_DOCUMENTO, INULOCK IN NUMBER := 1 );
   PROCEDURE UPDRECORD( IRCGE_ITEMS_DOCUMENTO IN STYGE_ITEMS_DOCUMENTO, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDRECORDS( IOTBGE_ITEMS_DOCUMENTO IN OUT NOCOPY TYTBGE_ITEMS_DOCUMENTO, INULOCK IN NUMBER := 1 );
   PROCEDURE UPDDOCUMENT_TYPE_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INUDOCUMENT_TYPE_ID$ IN GE_ITEMS_DOCUMENTO.DOCUMENT_TYPE_ID%TYPE, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDDOCUMENTO_EXTERNO( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, ISBDOCUMENTO_EXTERNO$ IN GE_ITEMS_DOCUMENTO.DOCUMENTO_EXTERNO%TYPE, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDFECHA( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, IDTFECHA$ IN GE_ITEMS_DOCUMENTO.FECHA%TYPE, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDESTADO( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, ISBESTADO$ IN GE_ITEMS_DOCUMENTO.ESTADO%TYPE, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDOPERATING_UNIT_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INUOPERATING_UNIT_ID$ IN GE_ITEMS_DOCUMENTO.OPERATING_UNIT_ID%TYPE, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDDESTINO_OPER_UNI_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INUDESTINO_OPER_UNI_ID$ IN GE_ITEMS_DOCUMENTO.DESTINO_OPER_UNI_ID%TYPE, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDTERMINAL_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, ISBTERMINAL_ID$ IN GE_ITEMS_DOCUMENTO.TERMINAL_ID%TYPE, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDUSER_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INUUSER_ID$ IN GE_ITEMS_DOCUMENTO.USER_ID%TYPE, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDCOMENTARIO( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, ISBCOMENTARIO$ IN GE_ITEMS_DOCUMENTO.COMENTARIO%TYPE, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDCAUSAL_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INUCAUSAL_ID$ IN GE_ITEMS_DOCUMENTO.CAUSAL_ID%TYPE, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDDELIVERY_DATE( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, IDTDELIVERY_DATE$ IN GE_ITEMS_DOCUMENTO.DELIVERY_DATE%TYPE, INULOCK IN NUMBER := 0 );
   PROCEDURE UPDPACKAGE_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INUPACKAGE_ID$ IN GE_ITEMS_DOCUMENTO.PACKAGE_ID%TYPE, INULOCK IN NUMBER := 0 );
   FUNCTION FNUGETID_ITEMS_DOCUMENTO( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE;
   FUNCTION FNUGETDOCUMENT_TYPE_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.DOCUMENT_TYPE_ID%TYPE;
   FUNCTION FSBGETDOCUMENTO_EXTERNO( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.DOCUMENTO_EXTERNO%TYPE;
   FUNCTION FDTGETFECHA( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.FECHA%TYPE;
   FUNCTION FSBGETESTADO( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.ESTADO%TYPE;
   FUNCTION FNUGETOPERATING_UNIT_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.OPERATING_UNIT_ID%TYPE;
   FUNCTION FNUGETDESTINO_OPER_UNI_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.DESTINO_OPER_UNI_ID%TYPE;
   FUNCTION FSBGETTERMINAL_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.TERMINAL_ID%TYPE;
   FUNCTION FNUGETUSER_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.USER_ID%TYPE;
   FUNCTION FSBGETCOMENTARIO( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.COMENTARIO%TYPE;
   FUNCTION FNUGETCAUSAL_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.CAUSAL_ID%TYPE;
   FUNCTION FDTGETDELIVERY_DATE( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.DELIVERY_DATE%TYPE;
   FUNCTION FNUGETPACKAGE_ID( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, INURAISEERROR IN NUMBER := 1 )
    RETURN GE_ITEMS_DOCUMENTO.PACKAGE_ID%TYPE;
   PROCEDURE LOCKBYPK( INUID_ITEMS_DOCUMENTO IN GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE, ORCGE_ITEMS_DOCUMENTO OUT STYGE_ITEMS_DOCUMENTO );
   PROCEDURE LOCKBYROWID( IRIROWID IN VARCHAR2, ORCGE_ITEMS_DOCUMENTO OUT STYGE_ITEMS_DOCUMENTO );
   PROCEDURE SETUSECACHE( IBLUSECACHE IN BOOLEAN );
END DAGE_ITEMS_DOCUMENTO;
/


