CREATE OR REPLACE PACKAGE BODY OR_BOFWORDERRELATED IS
   CSBVERSION CONSTANT VARCHAR2( 20 ) := 'SAO182536';
   CNURELATEDRDERTYPE CONSTANT OR_RELATED_ORDER.RELA_ORDER_TYPE_ID%TYPE := 13;
   FUNCTION FSBVERSION
    RETURN VARCHAR2
    IS
    BEGIN
      RETURN CSBVERSION;
   END;
   PROCEDURE VALIDATEORDERSTATUSRELATED
    IS
      NUORDERID OR_ORDER.ORDER_ID%TYPE;
      RCORDER DAOR_ORDER.STYOR_ORDER;
    BEGIN
      GE_BOINSTANCECONTROL.GETATTRIBUTENEWVALUE( GE_BOINSTANCECONSTANTS.CSBWORK_INSTANCE, NULL, 'OR_ORDER', 'ORDER_ID', NUORDERID );
      IF NUORDERID IS NOT NULL THEN
         RCORDER := DAOR_ORDER.FRCGETRECORD( NUORDERID );
         IF NOT OR_BOPROCESSORDER.FBLISORDERALTERABLEBYRELATED( RCORDER ) THEN
            GE_BOERRORS.SETERRORCODE( OR_BOCONSTANTS.CNUERR_122462 );
         END IF;
       ELSE
         GE_BOERRORS.SETERRORCODE( OR_BOCONSTANTS.CNUERR_122462 );
      END IF;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END VALIDATEORDERSTATUSRELATED;
   FUNCTION FNUGETRELATEDORDERTYPE
    RETURN OR_RELATED_ORDER.RELA_ORDER_TYPE_ID%TYPE
    IS
    BEGIN
      RETURN CNURELATEDRDERTYPE;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FNUGETRELATEDORDERTYPE;
   FUNCTION FNUGETACTIVITYTORELATED
    RETURN GE_ITEMS.ITEMS_ID%TYPE
    IS
      SBINSTANCE GE_BOINSTANCECONTROL.STYSBNAME;
      SBITEMS_ID GE_BOINSTANCECONTROL.STYSBVALUE;
      NUITEMS_ID GE_ITEMS.ITEMS_ID%TYPE;
      SBIDINDEX VARCHAR2( 1000 );
    BEGIN
      UT_TRACE.TRACE( 'INICIO OR_BOFWORDERRELATED.fnuGETACTIVITYTORELATED', 5 );
      GE_BOINSTANCECONTROL.GETCURRENTINSTANCE( SBINSTANCE );
      IF ( GE_BOINSTANCECONTROL.FBLACCKEYATTRIBUTESTACK( SBINSTANCE, NULL, 'GE_ITEMS', 'ITEMS_ID', SBIDINDEX ) = GE_BOCONSTANTS.GETTRUE ) THEN
         SBITEMS_ID := GE_BOINSTANCECONTROL.FSBGETFIELDVALUE( 'GE_ITEMS', 'ITEMS_ID' );
       ELSE
         IF ( GE_BOINSTANCECONTROL.FBLACCKEYATTRIBUTESTACK( GE_BOINSTANCECONSTANTS.CSBWORK_INSTANCE, NULL, 'GE_ITEMS', 'ITEMS_ID', SBIDINDEX ) = GE_BOCONSTANTS.GETTRUE ) THEN
            GE_BOINSTANCECONTROL.GETATTRIBUTENEWVALUE( GE_BOINSTANCECONSTANTS.CSBWORK_INSTANCE, NULL, 'GE_ITEMS', 'ITEMS_ID', SBITEMS_ID );
         END IF;
      END IF;
      IF ( SBITEMS_ID IS NOT NULL ) THEN
         NUITEMS_ID := UT_CONVERT.FNUCHARTONUMBER( SBITEMS_ID );
      END IF;
      UT_TRACE.TRACE( 'Valor Retornado  nuITEMS_ID ==>' || NUITEMS_ID, 5 );
      RETURN NUITEMS_ID;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FNUGETACTIVITYTORELATED;
END OR_BOFWORDERRELATED;
/


