PROMPT Crea Sinonimo a tabla LDC_CANT_VISITA_FALLIDA para LDC_PRVISITAFALLLIDA
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.LDC_CANT_VISITA_FALLIDA FOR LDC_CANT_VISITA_FALLIDA';
END;
/