PROMPT Crea sinonimo objeto dependiente LDC_ITEMSCOTIVALFIJOS_ADIC
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.LDC_ITEMSCOTIVALFIJOS_ADIC FOR LDC_ITEMSCOTIVALFIJOS_ADIC';
END;
/
