declare

vsbval ldci_carasewe.casevalo%type;

begin
  --
  vsbval := '596'; -- Clasificador CREDITO AFIANZADO
  --  
	BEGIN
	MERGE INTO LDCI_CARASEWE A
	USING (SELECT 'EXCLUYE_CLASIF_CON_CAUSAL_19' as CASECODI,
				  'EXCLUYE CLASIFICADORES CON CAUSAL 19' as CASEDESC,
				  vsbval as CASEVALO,
				  'WS_INTER_CONTABLE' AS CASEDESE
			 FROM DUAL) B
	ON (A.CASECODI = B.CASECODI)
	WHEN NOT MATCHED THEN
	  INSERT
		(CASECODI, CASEDESC, CASEVALO, CASEDESE)
	  VALUES
		(B.CASECODI, B.CASEDESC, B.CASEVALO, B.CASEDESE)
	 WHEN MATCHED THEN
		UPDATE set CASEVALO=B.CASEVALO;

	COMMIT;

	END;
  
end;
/