PROMPT Crea Sinonimo a tabla LDC_TEMP_PLANFACA_SGE para la funcion PRFECHAANTERIORPERI
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.LDC_TEMP_PLANFACA_SGE FOR LDC_TEMP_PLANFACA_SGE';
END;
/