PROMPT Crea sinonimo objeto dependiente LDC_PROLIBERAELEMENTOMEDICION
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM LDC_PROLIBERAELEMENTOMEDICION FOR ADM_PERSON.LDC_PROLIBERAELEMENTOMEDICION';
END;
/
