BEGIN
setsystemenviroment;
END;
/


BEGIN
sa_bocreatePackages.CreatePackage('LDC_CM_LECTESP_',
'CREATE OR REPLACE PACKAGE LDC_CM_LECTESP_ IS ' || chr(10) ||
'blProcessStatus boolean := true; ' || chr(10) ||
'type tyGE_ENTITYRowId is table of rowid index by varchar2(100); ' || chr(10) ||
'tbGE_ENTITYRowId tyGE_ENTITYRowId;type tyGE_ENTITY_ADITIONALRowId is table of rowid index by varchar2(100); ' || chr(10) ||
'tbGE_ENTITY_ADITIONALRowId tyGE_ENTITY_ADITIONALRowId;type tyGE_ENTITY_ATTRIBUTESRowId is table of rowid index by varchar2(100); ' || chr(10) ||
'tbGE_ENTITY_ATTRIBUTESRowId tyGE_ENTITY_ATTRIBUTESRowId;type tyGE_ATTR_ALLOWED_VALUESRowId is table of rowid index by varchar2(100); ' || chr(10) ||
'tbGE_ATTR_ALLOWED_VALUESRowId tyGE_ATTR_ALLOWED_VALUESRowId;type tyGE_ATTR_VAL_EXPRESSRowId is table of rowid index by varchar2(100); ' || chr(10) ||
'tbGE_ATTR_VAL_EXPRESSRowId tyGE_ATTR_VAL_EXPRESSRowId;type tyGR_CONFIG_EXPRESSIONRowId is table of rowid index by varchar2(100); ' || chr(10) ||
'tbGR_CONFIG_EXPRESSIONRowId tyGR_CONFIG_EXPRESSIONRowId;type ty0_0 is table of GE_ENTITY.NAME_%type index by binary_integer; ' || chr(10) ||
'old_tb0_0 ty0_0; ' || chr(10) ||
'tb0_0 ty0_0;type ty0_1 is table of GE_ENTITY.ENTITY_ID%type index by binary_integer; ' || chr(10) ||
'old_tb0_1 ty0_1; ' || chr(10) ||
'tb0_1 ty0_1;type ty1_0 is table of GE_ENTITY_ADITIONAL.ENTITY_ID%type index by binary_integer; ' || chr(10) ||
'old_tb1_0 ty1_0; ' || chr(10) ||
'tb1_0 ty1_0;type ty2_0 is table of GE_ENTITY_ATTRIBUTES.ENTITY_ID%type index by binary_integer; ' || chr(10) ||
'old_tb2_0 ty2_0; ' || chr(10) ||
'tb2_0 ty2_0;type ty2_1 is table of GE_ENTITY_ATTRIBUTES.ENTITY_ATTRIBUTE_ID%type index by binary_integer; ' || chr(10) ||
'old_tb2_1 ty2_1; ' || chr(10) ||
'tb2_1 ty2_1;type ty2_2 is table of GE_ENTITY_ATTRIBUTES.INIT_EXPRESSION_ID%type index by binary_integer; ' || chr(10) ||
'old_tb2_2 ty2_2; ' || chr(10) ||
'tb2_2 ty2_2;type ty2_3 is table of GE_ENTITY_ATTRIBUTES.VALID_EXPRESSION_ID%type index by binary_integer; ' || chr(10) ||
'old_tb2_3 ty2_3; ' || chr(10) ||
'tb2_3 ty2_3; ' || chr(10) ||
'  type tyCatalogTagName is table of ge_catalog.tag_name%type index by varchar2(200); ' || chr(10) ||
'  tbEntityAttributeName tyCatalogTagName; ' || chr(10) ||
' ' || chr(10) ||
'END LDC_CM_LECTESP_;');
END;
/


BEGIN ut_trace.trace('********************Comenzar proceso de objeto:LDC_CM_LECTESP_******************************'); END;
/

DECLARE
    nuConfigExpresionId     GR_CONFIG_EXPRESSION.CONFIG_EXPRESSION_ID%type;
    sbObjectName            USER_OBJECTS.OBJECT_NAME%type;
    sbObjectType            USER_OBJECTS.OBJECT_TYPE%type;
    sbCode                  GR_CONFIG_EXPRESSION.CODE%type;

    CURSOR  cuConfigExpression IS
        SELECT  GR_CONFIG_EXPRESSION.CONFIG_EXPRESSION_ID,
                USER_OBJECTS.OBJECT_NAME,
                USER_OBJECTS.OBJECT_TYPE,
                GR_CONFIG_EXPRESSION.CODE
        FROM    GR_CONFIG_EXPRESSION,
                USER_OBJECTS
        WHERE   GR_CONFIG_EXPRESSION.CONFIG_EXPRESSION_ID IN (
            SELECT  VALID_EXPRESSION_ID
            FROM    GE_ENTITY_ATTRIBUTES
            WHERE   ENTITY_ID in (SELECT ENTITY_ID FROM GE_ENTITY WHERE NAME_='LDC_CM_LECTESP')
            UNION
            SELECT  INIT_EXPRESSION_ID
            FROM    GE_ENTITY_ATTRIBUTES
            WHERE   ENTITY_ID in (SELECT ENTITY_ID FROM GE_ENTITY WHERE NAME_='LDC_CM_LECTESP')
        )
        AND     USER_OBJECTS.object_name(+) = GR_CONFIG_EXPRESSION.OBJECT_NAME;
BEGIN
    ut_trace.trace('Referencias asociadas a atributos borrados', 1);
    
if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

    if (cuConfigExpression%ISOPEN) then
        CLOSE cuConfigExpression;
    end if;
    
    DELETE FROM GE_ATTR_VAL_EXPRESS WHERE (ENTITY_ATTRIBUTE_ID) in (SELECT ENTITY_ATTRIBUTE_ID FROM GE_ENTITY_ATTRIBUTES WHERE (ENTITY_ID) in (SELECT ENTITY_ID FROM GE_ENTITY WHERE NAME_='LDC_CM_LECTESP'));
    DELETE FROM GE_ATTR_ALLOWED_VALUES WHERE (ENTITY_ATTRIBUTE_ID) in (SELECT ENTITY_ATTRIBUTE_ID FROM GE_ENTITY_ATTRIBUTES WHERE (ENTITY_ID) in (SELECT ENTITY_ID FROM GE_ENTITY WHERE NAME_='LDC_CM_LECTESP'));
    
    OPEN    cuConfigExpression;
    
    UPDATE  GE_ENTITY_ATTRIBUTES
    SET     INIT_EXPRESSION_ID = NULL, VALID_EXPRESSION_ID = NULL
    WHERE   ENTITY_ID in (SELECT ENTITY_ID FROM GE_ENTITY WHERE NAME_='LDC_CM_LECTESP');

    loop
        FETCH cuConfigExpression INTO nuConfigExpresionId, sbObjectName, sbObjectType, sbCode;
        EXIT WHEN cuConfigExpression%NOTFOUND;
        DELETE FROM GR_CONFIG_EXPRESSION WHERE (CONFIG_EXPRESSION_ID)  = nuConfigExpresionId;
        if (sbObjectName IS NOT NULL) then
            execute immediate 'DROP ' || sbObjectType || ' ' || sbObjectName;
        end if;
    end loop;
    
    if (cuConfigExpression%ISOPEN) then
        CLOSE cuConfigExpression;
    end if;

    EXCEPTION
        when others then
            rollback;
            if (cuConfigExpression%ISOPEN) then
                CLOSE cuConfigExpression;
            end if;
            OPEN    cuConfigExpression;
            loop
                FETCH cuConfigExpression INTO nuConfigExpresionId, sbObjectName, sbObjectType, sbCode;
                EXIT WHEN cuConfigExpression%NOTFOUND;
                execute immediate sbCode;
            end loop;
            CLOSE cuConfigExpression;
            ut_trace.trace('**ERROR:'||sqlerrm);
            raise;
END;
/


BEGIN 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132973) := 'LDC_CM_LECTESP@ORDER_ID'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132974) := 'LDC_CM_LECTESP@SESUNUSE'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132975) := 'LDC_CM_LECTESP@CONSEC_EXT'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132976) := 'LDC_CM_LECTESP@PEFACODI'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132970) := 'LDC_CM_LECTESP@PECSCONS'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132977) := 'LDC_CM_LECTESP@FELECTURA'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132978) := 'LDC_CM_LECTESP@FEREGISTRO'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132979) := 'LDC_CM_LECTESP@LECTURA'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132980) := 'LDC_CM_LECTESP@TEMPERATURA'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132971) := 'LDC_CM_LECTESP@PRES'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132981) := 'LDC_CM_LECTESP@PRESALT'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132982) := 'LDC_CM_LECTESP@PRESBJ'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132983) := 'LDC_CM_LECTESP@VOLCORR'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132984) := 'LDC_CM_LECTESP@VOLNCORR'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132985) := 'LDC_CM_LECTESP@LECT_EAGLE'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132986) := 'LDC_CM_LECTESP@VOLTBAT'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132987) := 'LDC_CM_LECTESP@USOCONS'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132972) := 'LDC_CM_LECTESP@PROCESADO'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90147401) := 'LDC_CM_LECTESP@SUBSCRIBER_ID'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132988) := 'LDC_CM_LECTESP@CLIENTE'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132989) := 'LDC_CM_LECTESP@MEDIDOR'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90132990) := 'LDC_CM_LECTESP@CONTRATO'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90141326) := 'LDC_CM_LECTESP@CAUSAL'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90141327) := 'LDC_CM_LECTESP@CAUSAL_OBS'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90147402) := 'LDC_CM_LECTESP@ADDRESS_ID'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90147403) := 'LDC_CM_LECTESP@LOCALIDAD'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90147404) := 'LDC_CM_LECTESP@DPTO'; 
  LDC_CM_LECTESP_.tbEntityAttributeName(90199398) := 'LDC_CM_LECTESP@OBSERVACION'; 
END;
/

BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.old_tb0_0(0):='LDC_CM_LECTESP'
;
LDC_CM_LECTESP_.tb0_0(0):='LDC_CM_LECTESP';
LDC_CM_LECTESP_.old_tb0_1(0):=3831;
LDC_CM_LECTESP_.tb0_1(0):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.tb0_0(0), 'ENTITY', 'GE_BOSEQUENCE.NEXTGE_ENTITY');
LDC_CM_LECTESP_.tb0_1(0):=LDC_CM_LECTESP_.tb0_1(0);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY fila (0)',1);
UPDATE GE_ENTITY SET NAME_=LDC_CM_LECTESP_.tb0_0(0),
ENTITY_ID=LDC_CM_LECTESP_.tb0_1(0),
MODULE_ID=80,
SELEC_TYPE_OBJECT_ID=null,
INS_SEQ=null,
IN_PERSIST='Y'
,
DESCRIPTION='LISTADO LECTURAS DE CLIENTES ESPECIALES'
,
DISPLAY_NAME='Lecturas de Clientes Especiales'
,
LOAD_CARTRIDGE='N'
,
TABLESPACE='TSD_DEFAULT'
,
CREATION_DATE=to_date('10-05-2016 16:48:48','DD-MM-YYYY HH24:MI:SS'),
LAST_MODIFY_DATE=to_date('10-05-2016 17:22:29','DD-MM-YYYY HH24:MI:SS'),
STATUS='G'
,
ALLOWED_FULL_SCAN='N'

 WHERE ENTITY_ID = LDC_CM_LECTESP_.tb0_1(0);
if not (sql%found) then
INSERT INTO GE_ENTITY(NAME_,ENTITY_ID,MODULE_ID,SELEC_TYPE_OBJECT_ID,INS_SEQ,IN_PERSIST,DESCRIPTION,DISPLAY_NAME,LOAD_CARTRIDGE,TABLESPACE,CREATION_DATE,LAST_MODIFY_DATE,STATUS,ALLOWED_FULL_SCAN) 
VALUES (LDC_CM_LECTESP_.tb0_0(0),
LDC_CM_LECTESP_.tb0_1(0),
80,
null,
null,
'Y'
,
'LISTADO LECTURAS DE CLIENTES ESPECIALES'
,
'Lecturas de Clientes Especiales'
,
'N'
,
'TSD_DEFAULT'
,
to_date('10-05-2016 16:48:48','DD-MM-YYYY HH24:MI:SS'),
to_date('10-05-2016 17:22:29','DD-MM-YYYY HH24:MI:SS'),
'G'
,
'N'
);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb1_0(0):=LDC_CM_LECTESP_.tb0_1(0);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ADITIONAL fila (0)',1);
UPDATE GE_ENTITY_ADITIONAL SET ENTITY_ID=LDC_CM_LECTESP_.tb1_0(0),
STATEMENT_ID=null,
QUERY_SERVICE_NAME=null,
PROCESS_SERVICE_NAME=null,
BASE_ENTITY_NAME=null,
BASE_ID_NAME=null,
PRIMARY_KEY_ATTRIBUTE='-1'
,
FOREING_KEY_ATTRIBUTE='-1'
,
ICON=null,
IS_SEARCH='N'
,
SEARCH_SERVICE_NAME=null,
CONTEXT_MENU_SERVICE=null,
HEADER_TITLES='<?xml version="1.0" encoding="utf-16"?><OpenQueryHeaderTitle xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><Title /><Subtitle1 /><Subtitle2 /></OpenQueryHeaderTitle>'
,
WINDOWS_TITLE=null,
BATCH_SERVICE_NAME=null,
TIME_EXECUTE_BATCH=null,
EXECUTABLE_NAME_EXECUTE=null,
IS_CUSTOM_ENTITY='Y'

 WHERE ENTITY_ID = LDC_CM_LECTESP_.tb1_0(0);
if not (sql%found) then
INSERT INTO GE_ENTITY_ADITIONAL(ENTITY_ID,STATEMENT_ID,QUERY_SERVICE_NAME,PROCESS_SERVICE_NAME,BASE_ENTITY_NAME,BASE_ID_NAME,PRIMARY_KEY_ATTRIBUTE,FOREING_KEY_ATTRIBUTE,ICON,IS_SEARCH,SEARCH_SERVICE_NAME,CONTEXT_MENU_SERVICE,HEADER_TITLES,WINDOWS_TITLE,BATCH_SERVICE_NAME,TIME_EXECUTE_BATCH,EXECUTABLE_NAME_EXECUTE,IS_CUSTOM_ENTITY) 
VALUES (LDC_CM_LECTESP_.tb1_0(0),
null,
null,
null,
null,
null,
'-1'
,
'-1'
,
null,
'N'
,
null,
null,
'<?xml version="1.0" encoding="utf-16"?><OpenQueryHeaderTitle xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><Title /><Subtitle1 /><Subtitle2 /></OpenQueryHeaderTitle>'
,
null,
null,
null,
null,
'Y'
);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(0):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(0):=90147402;
LDC_CM_LECTESP_.tb2_1(0):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(0)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(0):=LDC_CM_LECTESP_.tb2_1(0);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (0)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(0),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(0),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='ADDRESS_ID'
,
SECUENCE_=24,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Identificador de Direccion'
,
VIEWER_DISPLAY='Y'
,
PRECISION=15,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=15,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(0);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(0),
LDC_CM_LECTESP_.tb2_1(0),
null,
null,
null,
null,
null,
1,
'ADDRESS_ID'
,
24,
'N'
,
'Y'
,
'Identificador de Direccion'
,
'Y'
,
15,
null,
0,
15,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(1):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(1):=90141326;
LDC_CM_LECTESP_.tb2_1(1):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(1)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(1):=LDC_CM_LECTESP_.tb2_1(1);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (1)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(1),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(1),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='CAUSAL'
,
SECUENCE_=22,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Causal de No Lectura Presion'
,
VIEWER_DISPLAY='Y'
,
PRECISION=6,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=6,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(1);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(1),
LDC_CM_LECTESP_.tb2_1(1),
null,
null,
null,
null,
null,
1,
'CAUSAL'
,
22,
'N'
,
'Y'
,
'Causal de No Lectura Presion'
,
'Y'
,
6,
null,
0,
6,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(2):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(2):=90141327;
LDC_CM_LECTESP_.tb2_1(2):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(2)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(2):=LDC_CM_LECTESP_.tb2_1(2);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (2)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(2),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(2),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=2,
TECHNICAL_NAME='CAUSAL_OBS'
,
SECUENCE_=23,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Obs. No Lectura Presion'
,
VIEWER_DISPLAY='Y'
,
PRECISION=null,
DEFAULT_VALUE=null,
SCALE=null,
LENGTH=4000,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(2);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(2),
LDC_CM_LECTESP_.tb2_1(2),
null,
null,
null,
null,
null,
2,
'CAUSAL_OBS'
,
23,
'N'
,
'Y'
,
'Obs. No Lectura Presion'
,
'Y'
,
null,
null,
null,
4000,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(3):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(3):=90132988;
LDC_CM_LECTESP_.tb2_1(3):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(3)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(3):=LDC_CM_LECTESP_.tb2_1(3);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (3)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(3),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(3),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=2,
TECHNICAL_NAME='CLIENTE'
,
SECUENCE_=19,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Nombre del Cliente'
,
VIEWER_DISPLAY='Y'
,
PRECISION=null,
DEFAULT_VALUE=null,
SCALE=null,
LENGTH=200,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(3);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(3),
LDC_CM_LECTESP_.tb2_1(3),
null,
null,
null,
null,
null,
2,
'CLIENTE'
,
19,
'N'
,
'Y'
,
'Nombre del Cliente'
,
'Y'
,
null,
null,
null,
200,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(4):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(4):=90132975;
LDC_CM_LECTESP_.tb2_1(4):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(4)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(4):=LDC_CM_LECTESP_.tb2_1(4);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (4)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(4),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(4),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='CONSEC_EXT'
,
SECUENCE_=2,
KEY_='N'
,
IS_NULL='N'
,
DISPLAY_NAME='Consec. Externo'
,
VIEWER_DISPLAY='Y'
,
PRECISION=15,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=15,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(4);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(4),
LDC_CM_LECTESP_.tb2_1(4),
null,
null,
null,
null,
null,
1,
'CONSEC_EXT'
,
2,
'N'
,
'N'
,
'Consec. Externo'
,
'Y'
,
15,
null,
0,
15,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(5):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(5):=90132990;
LDC_CM_LECTESP_.tb2_1(5):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(5)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(5):=LDC_CM_LECTESP_.tb2_1(5);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (5)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(5),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(5),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='CONTRATO'
,
SECUENCE_=21,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Contrato'
,
VIEWER_DISPLAY='Y'
,
PRECISION=15,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=15,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(5);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(5),
LDC_CM_LECTESP_.tb2_1(5),
null,
null,
null,
null,
null,
1,
'CONTRATO'
,
21,
'N'
,
'Y'
,
'Contrato'
,
'Y'
,
15,
null,
0,
15,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(6):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(6):=90147404;
LDC_CM_LECTESP_.tb2_1(6):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(6)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(6):=LDC_CM_LECTESP_.tb2_1(6);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (6)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(6),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(6),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='DPTO'
,
SECUENCE_=26,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Id Departamento'
,
VIEWER_DISPLAY='Y'
,
PRECISION=15,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=15,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(6);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(6),
LDC_CM_LECTESP_.tb2_1(6),
null,
null,
null,
null,
null,
1,
'DPTO'
,
26,
'N'
,
'Y'
,
'Id Departamento'
,
'Y'
,
15,
null,
0,
15,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(7):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(7):=90132977;
LDC_CM_LECTESP_.tb2_1(7):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(7)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(7):=LDC_CM_LECTESP_.tb2_1(7);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (7)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(7),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(7),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=3,
TECHNICAL_NAME='FELECTURA'
,
SECUENCE_=5,
KEY_='N'
,
IS_NULL='N'
,
DISPLAY_NAME='Fecha Lectura'
,
VIEWER_DISPLAY='Y'
,
PRECISION=null,
DEFAULT_VALUE=null,
SCALE=null,
LENGTH=7,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(7);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(7),
LDC_CM_LECTESP_.tb2_1(7),
null,
null,
null,
null,
null,
3,
'FELECTURA'
,
5,
'N'
,
'N'
,
'Fecha Lectura'
,
'Y'
,
null,
null,
null,
7,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(8):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(8):=90132978;
LDC_CM_LECTESP_.tb2_1(8):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(8)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(8):=LDC_CM_LECTESP_.tb2_1(8);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (8)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(8),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(8),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=3,
TECHNICAL_NAME='FEREGISTRO'
,
SECUENCE_=6,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Fecha Registro'
,
VIEWER_DISPLAY='Y'
,
PRECISION=null,
DEFAULT_VALUE=null,
SCALE=null,
LENGTH=7,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(8);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(8),
LDC_CM_LECTESP_.tb2_1(8),
null,
null,
null,
null,
null,
3,
'FEREGISTRO'
,
6,
'N'
,
'Y'
,
'Fecha Registro'
,
'Y'
,
null,
null,
null,
7,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(9):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(9):=90132979;
LDC_CM_LECTESP_.tb2_1(9):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(9)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(9):=LDC_CM_LECTESP_.tb2_1(9);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (9)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(9),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(9),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='LECTURA'
,
SECUENCE_=7,
KEY_='N'
,
IS_NULL='N'
,
DISPLAY_NAME='Lectura'
,
VIEWER_DISPLAY='Y'
,
PRECISION=14,
DEFAULT_VALUE=null,
SCALE=4,
LENGTH=14,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(9);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(9),
LDC_CM_LECTESP_.tb2_1(9),
null,
null,
null,
null,
null,
1,
'LECTURA'
,
7,
'N'
,
'N'
,
'Lectura'
,
'Y'
,
14,
null,
4,
14,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(10):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(10):=90132985;
LDC_CM_LECTESP_.tb2_1(10):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(10)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(10):=LDC_CM_LECTESP_.tb2_1(10);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (10)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(10),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(10),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='LECT_EAGLE'
,
SECUENCE_=14,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Lectura Eagle'
,
VIEWER_DISPLAY='Y'
,
PRECISION=14,
DEFAULT_VALUE=null,
SCALE=4,
LENGTH=14,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(10);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(10),
LDC_CM_LECTESP_.tb2_1(10),
null,
null,
null,
null,
null,
1,
'LECT_EAGLE'
,
14,
'N'
,
'Y'
,
'Lectura Eagle'
,
'Y'
,
14,
null,
4,
14,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(11):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(11):=90147403;
LDC_CM_LECTESP_.tb2_1(11):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(11)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(11):=LDC_CM_LECTESP_.tb2_1(11);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (11)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(11),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(11),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='LOCALIDAD'
,
SECUENCE_=25,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Id Localidad'
,
VIEWER_DISPLAY='Y'
,
PRECISION=15,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=15,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(11);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(11),
LDC_CM_LECTESP_.tb2_1(11),
null,
null,
null,
null,
null,
1,
'LOCALIDAD'
,
25,
'N'
,
'Y'
,
'Id Localidad'
,
'Y'
,
15,
null,
0,
15,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(12):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(12):=90132989;
LDC_CM_LECTESP_.tb2_1(12):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(12)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(12):=LDC_CM_LECTESP_.tb2_1(12);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (12)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(12),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(12),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=2,
TECHNICAL_NAME='MEDIDOR'
,
SECUENCE_=20,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Medidor'
,
VIEWER_DISPLAY='Y'
,
PRECISION=null,
DEFAULT_VALUE=null,
SCALE=null,
LENGTH=50,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(12);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(12),
LDC_CM_LECTESP_.tb2_1(12),
null,
null,
null,
null,
null,
2,
'MEDIDOR'
,
20,
'N'
,
'Y'
,
'Medidor'
,
'Y'
,
null,
null,
null,
50,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(13):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(13):=90199398;
LDC_CM_LECTESP_.tb2_1(13):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(13)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(13):=LDC_CM_LECTESP_.tb2_1(13);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (13)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(13),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(13),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='OBSERVACION'
,
SECUENCE_=27,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Código Observación de no lectura'
,
VIEWER_DISPLAY='Y'
,
PRECISION=4,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=4,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(13);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(13),
LDC_CM_LECTESP_.tb2_1(13),
null,
null,
null,
null,
null,
1,
'OBSERVACION'
,
27,
'N'
,
'Y'
,
'Código Observación de no lectura'
,
'Y'
,
4,
null,
0,
4,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(14):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(14):=90132973;
LDC_CM_LECTESP_.tb2_1(14):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(14)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(14):=LDC_CM_LECTESP_.tb2_1(14);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (14)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(14),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(14),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='ORDER_ID'
,
SECUENCE_=0,
KEY_='N'
,
IS_NULL='N'
,
DISPLAY_NAME='Orden'
,
VIEWER_DISPLAY='Y'
,
PRECISION=15,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=15,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(14);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(14),
LDC_CM_LECTESP_.tb2_1(14),
null,
null,
null,
null,
null,
1,
'ORDER_ID'
,
0,
'N'
,
'N'
,
'Orden'
,
'Y'
,
15,
null,
0,
15,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(15):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(15):=90132970;
LDC_CM_LECTESP_.tb2_1(15):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(15)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(15):=LDC_CM_LECTESP_.tb2_1(15);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (15)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(15),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(15),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='PECSCONS'
,
SECUENCE_=4,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Periodo Cons.'
,
VIEWER_DISPLAY='Y'
,
PRECISION=15,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=15,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(15);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(15),
LDC_CM_LECTESP_.tb2_1(15),
null,
null,
null,
null,
null,
1,
'PECSCONS'
,
4,
'N'
,
'Y'
,
'Periodo Cons.'
,
'Y'
,
15,
null,
0,
15,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(16):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(16):=90132976;
LDC_CM_LECTESP_.tb2_1(16):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(16)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(16):=LDC_CM_LECTESP_.tb2_1(16);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (16)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(16),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(16),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='PEFACODI'
,
SECUENCE_=3,
KEY_='N'
,
IS_NULL='N'
,
DISPLAY_NAME='Periodo Fact.'
,
VIEWER_DISPLAY='Y'
,
PRECISION=6,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=6,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(16);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(16),
LDC_CM_LECTESP_.tb2_1(16),
null,
null,
null,
null,
null,
1,
'PEFACODI'
,
3,
'N'
,
'N'
,
'Periodo Fact.'
,
'Y'
,
6,
null,
0,
6,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(17):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(17):=90132971;
LDC_CM_LECTESP_.tb2_1(17):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(17)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(17):=LDC_CM_LECTESP_.tb2_1(17);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (17)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(17),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(17),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='PRES'
,
SECUENCE_=9,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Presion'
,
VIEWER_DISPLAY='Y'
,
PRECISION=14,
DEFAULT_VALUE=null,
SCALE=4,
LENGTH=14,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(17);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(17),
LDC_CM_LECTESP_.tb2_1(17),
null,
null,
null,
null,
null,
1,
'PRES'
,
9,
'N'
,
'Y'
,
'Presion'
,
'Y'
,
14,
null,
4,
14,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(18):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(18):=90132981;
LDC_CM_LECTESP_.tb2_1(18):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(18)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(18):=LDC_CM_LECTESP_.tb2_1(18);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (18)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(18),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(18),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='PRESALT'
,
SECUENCE_=10,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Presion Alta'
,
VIEWER_DISPLAY='Y'
,
PRECISION=14,
DEFAULT_VALUE=null,
SCALE=4,
LENGTH=14,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(18);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(18),
LDC_CM_LECTESP_.tb2_1(18),
null,
null,
null,
null,
null,
1,
'PRESALT'
,
10,
'N'
,
'Y'
,
'Presion Alta'
,
'Y'
,
14,
null,
4,
14,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(19):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(19):=90132982;
LDC_CM_LECTESP_.tb2_1(19):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(19)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(19):=LDC_CM_LECTESP_.tb2_1(19);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (19)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(19),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(19),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='PRESBJ'
,
SECUENCE_=11,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Presion Baja'
,
VIEWER_DISPLAY='Y'
,
PRECISION=14,
DEFAULT_VALUE=null,
SCALE=4,
LENGTH=14,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(19);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(19),
LDC_CM_LECTESP_.tb2_1(19),
null,
null,
null,
null,
null,
1,
'PRESBJ'
,
11,
'N'
,
'Y'
,
'Presion Baja'
,
'Y'
,
14,
null,
4,
14,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(20):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(20):=90132972;
LDC_CM_LECTESP_.tb2_1(20):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(20)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(20):=LDC_CM_LECTESP_.tb2_1(20);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (20)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(20),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(20),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=2,
TECHNICAL_NAME='PROCESADO'
,
SECUENCE_=17,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Procesado'
,
VIEWER_DISPLAY='Y'
,
PRECISION=null,
DEFAULT_VALUE=null,
SCALE=null,
LENGTH=1,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(20);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(20),
LDC_CM_LECTESP_.tb2_1(20),
null,
null,
null,
null,
null,
2,
'PROCESADO'
,
17,
'N'
,
'Y'
,
'Procesado'
,
'Y'
,
null,
null,
null,
1,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(21):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(21):=90132974;
LDC_CM_LECTESP_.tb2_1(21):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(21)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(21):=LDC_CM_LECTESP_.tb2_1(21);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (21)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(21),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(21),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='SESUNUSE'
,
SECUENCE_=1,
KEY_='N'
,
IS_NULL='N'
,
DISPLAY_NAME='Producto'
,
VIEWER_DISPLAY='Y'
,
PRECISION=15,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=15,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(21);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(21),
LDC_CM_LECTESP_.tb2_1(21),
null,
null,
null,
null,
null,
1,
'SESUNUSE'
,
1,
'N'
,
'N'
,
'Producto'
,
'Y'
,
15,
null,
0,
15,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(22):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(22):=90147401;
LDC_CM_LECTESP_.tb2_1(22):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(22)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(22):=LDC_CM_LECTESP_.tb2_1(22);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (22)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(22),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(22),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='SUBSCRIBER_ID'
,
SECUENCE_=18,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Cliente'
,
VIEWER_DISPLAY='Y'
,
PRECISION=15,
DEFAULT_VALUE=null,
SCALE=0,
LENGTH=15,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(22);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(22),
LDC_CM_LECTESP_.tb2_1(22),
null,
null,
null,
null,
null,
1,
'SUBSCRIBER_ID'
,
18,
'N'
,
'Y'
,
'Cliente'
,
'Y'
,
15,
null,
0,
15,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(23):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(23):=90132980;
LDC_CM_LECTESP_.tb2_1(23):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(23)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(23):=LDC_CM_LECTESP_.tb2_1(23);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (23)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(23),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(23),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='TEMPERATURA'
,
SECUENCE_=8,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Temperatura'
,
VIEWER_DISPLAY='Y'
,
PRECISION=14,
DEFAULT_VALUE=null,
SCALE=4,
LENGTH=14,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(23);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(23),
LDC_CM_LECTESP_.tb2_1(23),
null,
null,
null,
null,
null,
1,
'TEMPERATURA'
,
8,
'N'
,
'Y'
,
'Temperatura'
,
'Y'
,
14,
null,
4,
14,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(24):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(24):=90132987;
LDC_CM_LECTESP_.tb2_1(24):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(24)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(24):=LDC_CM_LECTESP_.tb2_1(24);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (24)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(24),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(24),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=2,
TECHNICAL_NAME='USOCONS'
,
SECUENCE_=16,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Uso Consumo'
,
VIEWER_DISPLAY='Y'
,
PRECISION=null,
DEFAULT_VALUE=null,
SCALE=null,
LENGTH=1,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(24);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(24),
LDC_CM_LECTESP_.tb2_1(24),
null,
null,
null,
null,
null,
2,
'USOCONS'
,
16,
'N'
,
'Y'
,
'Uso Consumo'
,
'Y'
,
null,
null,
null,
1,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(25):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(25):=90132983;
LDC_CM_LECTESP_.tb2_1(25):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(25)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(25):=LDC_CM_LECTESP_.tb2_1(25);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (25)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(25),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(25),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='VOLCORR'
,
SECUENCE_=12,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Vol. Corregido'
,
VIEWER_DISPLAY='Y'
,
PRECISION=14,
DEFAULT_VALUE=null,
SCALE=4,
LENGTH=14,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(25);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(25),
LDC_CM_LECTESP_.tb2_1(25),
null,
null,
null,
null,
null,
1,
'VOLCORR'
,
12,
'N'
,
'Y'
,
'Vol. Corregido'
,
'Y'
,
14,
null,
4,
14,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(26):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(26):=90132984;
LDC_CM_LECTESP_.tb2_1(26):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(26)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(26):=LDC_CM_LECTESP_.tb2_1(26);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (26)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(26),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(26),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='VOLNCORR'
,
SECUENCE_=13,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Vol. No Corregido'
,
VIEWER_DISPLAY='Y'
,
PRECISION=14,
DEFAULT_VALUE=null,
SCALE=4,
LENGTH=14,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(26);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(26),
LDC_CM_LECTESP_.tb2_1(26),
null,
null,
null,
null,
null,
1,
'VOLNCORR'
,
13,
'N'
,
'Y'
,
'Vol. No Corregido'
,
'Y'
,
14,
null,
4,
14,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;

LDC_CM_LECTESP_.tb2_0(27):=LDC_CM_LECTESP_.tb0_1(0);
LDC_CM_LECTESP_.old_tb2_1(27):=90132986;
LDC_CM_LECTESP_.tb2_1(27):=GE_BOCATALOG.FNUGETIDSEQFROMCATALOG(LDC_CM_LECTESP_.TBENTITYATTRIBUTENAME(LDC_CM_LECTESP_.old_tb2_1(27)), 'ATTRIBUTE', GE_BOSEQUENCE.NEXTGE_ENTITY_ATTRIBUTES);
LDC_CM_LECTESP_.tb2_1(27):=LDC_CM_LECTESP_.tb2_1(27);
ut_trace.trace('Actualizar o insertar tabla: GE_ENTITY_ATTRIBUTES fila (27)',1);
UPDATE GE_ENTITY_ATTRIBUTES SET ENTITY_ID=LDC_CM_LECTESP_.tb2_0(27),
ENTITY_ATTRIBUTE_ID=LDC_CM_LECTESP_.tb2_1(27),
INIT_EXPRESSION_ID=null,
VALID_EXPRESSION_ID=null,
GI_COMPONENT_ID=null,
MASK_ID=null,
REFERENCE=null,
ATTRIBUTE_TYPE_ID=1,
TECHNICAL_NAME='VOLTBAT'
,
SECUENCE_=15,
KEY_='N'
,
IS_NULL='Y'
,
DISPLAY_NAME='Volt. Bateria'
,
VIEWER_DISPLAY='Y'
,
PRECISION=14,
DEFAULT_VALUE=null,
SCALE=4,
LENGTH=14,
COMMENT_=null,
TAG_ELEMENT=null,
STATUS='G'
,
IS_DESCRIPTION='N'
,
IS_LOV_DESCRIPTION='N'
,
IS_CHECK_BOX='N'
,
CHECKED_VALUE=null,
UNCHECKED_VALUE=null,
PROTECTOR_TEXT=null
 WHERE ENTITY_ATTRIBUTE_ID = LDC_CM_LECTESP_.tb2_1(27);
if not (sql%found) then
INSERT INTO GE_ENTITY_ATTRIBUTES(ENTITY_ID,ENTITY_ATTRIBUTE_ID,INIT_EXPRESSION_ID,VALID_EXPRESSION_ID,GI_COMPONENT_ID,MASK_ID,REFERENCE,ATTRIBUTE_TYPE_ID,TECHNICAL_NAME,SECUENCE_,KEY_,IS_NULL,DISPLAY_NAME,VIEWER_DISPLAY,PRECISION,DEFAULT_VALUE,SCALE,LENGTH,COMMENT_,TAG_ELEMENT,STATUS,IS_DESCRIPTION,IS_LOV_DESCRIPTION,IS_CHECK_BOX,CHECKED_VALUE,UNCHECKED_VALUE,PROTECTOR_TEXT) 
VALUES (LDC_CM_LECTESP_.tb2_0(27),
LDC_CM_LECTESP_.tb2_1(27),
null,
null,
null,
null,
null,
1,
'VOLTBAT'
,
15,
'N'
,
'Y'
,
'Volt. Bateria'
,
'Y'
,
14,
null,
4,
14,
null,
null,
'G'
,
'N'
,
'N'
,
'N'
,
null,
null,
null);
end if;

exception when others then
LDC_CM_LECTESP_.blProcessStatus := false;
rollback;
ut_trace.trace('**ERROR:'||sqlerrm);
raise;
END;
/
DECLARE
  nuerr number;
  sberr varchar2(4000);
BEGIN

if (not LDC_CM_LECTESP_.blProcessStatus) then
 return;
end if;
  commit;
  gi_boframeworkentityattribute.UpdateEntityReferences('LDC_CM_LECTESP');
EXCEPTION
  when ex.CONTROLLED_ERROR then
     Errors.GetError(nuerr, sberr);
     ut_trace.trace('Error en actualización de referencias ' || nuerr || '-' || sberr);
  when others then
     Errors.setError;
     Errors.GetError(nuerr, sberr);
     ut_trace.trace('Error en actualización de referencias ' || nuerr || '-' || sberr);
END;
/


COMMIT
/

begin
SA_BOCreatePackages.DropPackage('LDC_CM_LECTESP_');
end;
/

BEGIN ut_trace.trace('********************FIN  proceso de objeto:LDC_CM_LECTESP_******************************'); end;
/

