PROMPT Crea Sinonimo a función LDCBI_ASSIGN_IOT_METER_READING
BEGIN
	EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM LDCBI_ASSIGN_IOT_METER_READING FOR ADM_PERSON.LDCBI_ASSIGN_IOT_METER_READING';
END;
/
