DECLARE
  nuConta NUMBER;
BEGIN
  SELECT COUNT(1) INTO nuConta
  FROM DBA_SYNONYMS
  WHERE SYNONYM_NAME = 'API_LEGALIZEORDERS'
   AND OWNER = 'PERSONALIZACIONES';

  IF nuConta = 0 THEN
      EXECUTE IMMEDIATE 'CREATE SYNONYM PERSONALIZACIONES.API_LEGALIZEORDERS FOR ADM_PERSON.API_LEGALIZEORDERS';
  END IF;
END;
/

DECLARE
  nuConta NUMBER;
BEGIN
  SELECT COUNT(1) INTO nuConta
  FROM DBA_SYNONYMS
  WHERE SYNONYM_NAME = 'API_LEGALIZEORDERS'
   AND OWNER = 'OPEN';

  IF nuConta = 0 THEN
      EXECUTE IMMEDIATE 'CREATE SYNONYM OPEN.API_LEGALIZEORDERS FOR ADM_PERSON.API_LEGALIZEORDERS';
  END IF;
END;
/

DECLARE
  nuConta NUMBER;
BEGIN
  SELECT COUNT(1) INTO nuConta
  FROM DBA_SYNONYMS
  WHERE SYNONYM_NAME = 'API_LEGALIZEORDERS'
   AND OWNER = 'INNOVACION';

  IF nuConta = 0 THEN
      EXECUTE IMMEDIATE 'CREATE SYNONYM INNOVACION.API_LEGALIZEORDERS FOR ADM_PERSON.API_LEGALIZEORDERS';
  END IF;
END;
/