CREATE OR REPLACE TRIGGER OPEN.TRG_DO_PAGARE
    AFTER INSERT OR UPDATE OR DELETE
    ON OPEN.PAGARE
    REFERENCING OLD AS OLD NEW AS NEW
    FOR EACH ROW
BEGIN
    DECLARE
        PAGACODI  NUMBER(15);
        OPERATION VARCHAR2(1);
    BEGIN
        IF INSERTING THEN
            PAGACODI := :new.PAGACODI;
            OPERATION := 'I';
        ELSIF UPDATING THEN
            PAGACODI := :old.PAGACODI;
            OPERATION := 'U';
        ELSE
            PAGACODI := :old.PAGACODI;
            OPERATION := 'D';
        END IF;
        INSERT INTO OPEN.LDCBI_PAGARE(PAGACODI, OPERATION) VALUES (PAGACODI, OPERATION);
    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20000, 'Error en TRG_DO_PAGARE por -->' || sqlcode || chr(13) || sqlerrm);
    END;
END;
/