CREATE OR REPLACE FUNCTION FABSCT93E121402624
RETURN NUMBER IS
-- Generated by Code Generator (PVCS Version 1.5)
 -- Open Systems Ltd, Copyright 2003.
V0 NUMBER;
promotion_id NUMBER;
subscriber_id NUMBER;
location_id NUMBER;
category NUMBER;
subcategory NUMBER;
V1 NUMBER;
V2 NUMBER;
nuSubsidyValue NUMBER;

BEGIN
SubsidyInitData(promotion_id, subscriber_id, location_id, category, subcategory);
V0:= 0;
V2 := 2;
V1:=LD_BOSubsidy.FnuGetMaxSubValue(promotion_id, subscriber_id, location_id, category, subcategory, V2);
nuSubsidyValue:=V1;
RETURN V1;
END;
/
