select * 
from personalizaciones.parametros  p
where p.codigo in ( 'CICLO_FACTELECT' , 'CONS_NUMEAUTO_FACTELECT' ,'ESTADO_ACTU_FACTELECT' ,
 'ESTADO_REENVIO_FACELE', 'PASSWORD_FACTELECT' , 'PLANTILLA_FACTELECT' , 'TOKEN_FACTELECT' , 'USUARIO_FACTELECT', 'PREFIJO_FACTELECT', 'COD_EMPRESA_FACTELECT' )