PROMPT Crea sinonimo objeto dependiente SEQ_CC_GRACE_PERI_D_185489
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.SEQ_CC_GRACE_PERI_D_185489 FOR SEQ_CC_GRACE_PERI_D_185489';
END;
/
