
CREATE OR REPLACE PROCEDURE OS_GET_REQUESTS_REG( INUOPEUNITERP_ID IN OR_OPERATING_UNIT.OPERATING_UNIT_ID%TYPE, OSBREQUESTSREGS IN OUT CLOB, ONUERRORCODE OUT NUMBER, OSBERRORMESSAGE OUT VARCHAR2 )
 IS
 BEGIN
   GE_BSITEMSREQUEST.GETREGISTEREDREQUESTS( INUOPEUNITERP_ID, OSBREQUESTSREGS, ONUERRORCODE, OSBERRORMESSAGE );
 EXCEPTION
   WHEN EX.CONTROLLED_ERROR THEN
      ERRORS.GETERROR( ONUERRORCODE, OSBERRORMESSAGE );
   WHEN OTHERS THEN
      ERRORS.SETERROR;
      ERRORS.GETERROR( ONUERRORCODE, OSBERRORMESSAGE );
END OS_GET_REQUESTS_REG;
/


