CREATE OR REPLACE PROCEDURE OS_RELATED_ORDER( INUORDERID IN OR_ORDER.ORDER_ID%TYPE, INUORDERIDTORELATE IN OR_ORDER.ORDER_ID%TYPE, ONUERRORCODE OUT GE_ERROR_LOG.ERROR_LOG_ID%TYPE, OSBERRORMESSAGE OUT GE_ERROR_LOG.DESCRIPTION%TYPE )
 IS
 BEGIN
   OR_BSORDER.RELATEDORDER( INUORDERID, INUORDERIDTORELATE, ONUERRORCODE, OSBERRORMESSAGE );
 EXCEPTION
   WHEN EX.CONTROLLED_ERROR THEN
      ERRORS.GETERROR( ONUERRORCODE, OSBERRORMESSAGE );
   WHEN OTHERS THEN
      ERRORS.SETERROR;
      ERRORS.GETERROR( ONUERRORCODE, OSBERRORMESSAGE );
END;
/


