CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_OR_UNI_ITEM_BALA_MOV AFTER INSERT OR UPDATE OR DELETE ON OR_UNI_ITEM_BALA_MOV
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

UNI_ITEM_BALA_MOV_ID NUMBER(15);
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  UNI_ITEM_BALA_MOV_ID := :new.UNI_ITEM_BALA_MOV_ID;
  OPERATION := 'I';
ELSIF UPDATING THEN
  UNI_ITEM_BALA_MOV_ID := :new.UNI_ITEM_BALA_MOV_ID;
  OPERATION := 'U';
ELSE
  UNI_ITEM_BALA_MOV_ID := :old.UNI_ITEM_BALA_MOV_ID;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_OR_UNI_ITEM_BALA_MOV (
  UNI_ITEM_BALA_MOV_ID,
  OPERATION
)
VALUES (
  UNI_ITEM_BALA_MOV_ID,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EX.CONTROLLED_ERROR;
END;
/
