CREATE OR REPLACE PROCEDURE OS_UPDTELEMEASCONSUMPTION( ISBMEASELEMCODE IN ELEMMEDI.ELMECODI%TYPE, INUCONSUMPTIONTYPE IN GC_CONSTEME.COTMTCON%TYPE, IDTCONSUMPTIONDATE IN GC_CONSTEME.COTMFECO%TYPE, INUCONSUMPTIONUNITS IN GC_CONSTEME.COTMUNCO%TYPE, ONUERRORCODE OUT GE_ERROR_LOG.ERROR_LOG_ID%TYPE, OSBERRORMESSAGE OUT GE_ERROR_LOG.DESCRIPTION%TYPE )
 IS
 BEGIN
   PKERRORS.PUSH( 'OS_UpdTeleMeasConsumption' );
   PKERRORS.SETEXTERNALSYSTEM;
   PKERRORS.SETAPPLICATION( 'TMC' );
   PKBSGC_TELEMEASCONSUMP.UPDATECONSUMPTION( ISBMEASELEMCODE, INUCONSUMPTIONTYPE, IDTCONSUMPTIONDATE, INUCONSUMPTIONUNITS, ONUERRORCODE, OSBERRORMESSAGE );
   PKERRORS.POP;
 EXCEPTION
   WHEN LOGIN_DENIED OR PKCONSTANTE.EXERROR_LEVEL2 THEN
      PKERRORS.POP;
      PKERRORS.GETERRORVAR( ONUERRORCODE, OSBERRORMESSAGE );
   WHEN OTHERS THEN
      PKERRORS.NOTIFYERROR( PKERRORS.FSBLASTOBJECT, SQLERRM, OSBERRORMESSAGE );
      PKERRORS.POP;
      PKERRORS.GETERRORVAR( ONUERRORCODE, OSBERRORMESSAGE );
END OS_UPDTELEMEASCONSUMPTION;
/


