--LDCCCRCS
select * from open.LDC_SUI_CAUS_EQU where tipo_solicitud in (545, 50, 52);
select * from open.LDC_SUI_CAUS_EQU where tipo_solicitud in (100337);
--(CAUSAL_SOLICITUD);
SELECT CAUSAL_ID "Código", DESCRIPTION "Descripción" FROM open.CC_CAUSAL;
--(TIPO_SOLICITUD);
SELECT PACKAGE_TYPE_ID "CODIGO", DESCRIPTION "DESCRIPCION"
  FROM open.LDC_SUI_VISTA_TIPSOSSPD
 ORDER BY PACKAGE_TYPE_ID ASC;
--(GRUPO_CAUSAL);
SELECT CODIGO "ID", DESCRIPCION "DESCRIPTION"
  FROM open.LDC_SUI_GRUPCAUS
 ORDER BY CODIGO ASC;
--(CAUSAL_SSPD);
SELECT COD_CAUSAL_SSPD "ID", DESCRIPCION_CAUSAL "DESCRIPTION"
  FROM open.LDC_SUI_CAUSSPD
 ORDER BY COD_CAUSAL_SSPD ASC;
SELECT CODIGO "ID", DESCRIPCION "DESCRIPTION"
  FROM open.LDC_SUI_GRUPCAUS
 ORDER BY CODIGO ASC;
SELECT COD_CAUSAL_SSPD "ID", DESCRIPCION_CAUSAL "DESCRIPTION"
  FROM open.LDC_SUI_CAUSSPD
 ORDER BY COD_CAUSAL_SSPD ASC;
SELECT PACKAGE_TYPE_ID "CODIGO", DESCRIPTION "DESCRIPCION"
  FROM open.LDC_SUI_VISTA_TIPSOSSPD
 ORDER BY PACKAGE_TYPE_ID ASC;
SELECT * FROM open.CC_CAUSAL;
--- LDCTTCLRE
SELECT * FROM open.LDC_SUI_TIPSOL;
select * from open.LDC_SUI_TIPRES;
SELECT max(idrespu) FROM open.ldc_sui_respuesta; --181
SELECT * FROM open.ldc_sui_respuesta where tipo_solicitud in (545, 50, 52);
SELECT *
  FROM open.ldc_sui_respuesta
 where tipo_solicitud in (100338, 100337, 100335);
SELECT CODIGO          "ID",
       DESCRIPCION     "DESCRIPTION",
       CODIGO_RESP_OSF "TIPO RESPUESTA OSF"
  FROM open.LDC_SUI_TIPRES
 ORDER BY CODIGO ASC;
SELECT * FROM open.LDC_SUI_TITRCALE WHERE respuesta = 183;
