DECLARE
  nuConta NUMBER;
BEGIN
     SELECT COUNT(*) INTO nuConta
  FROM dba_objects
  WHERE object_name = 'LDC_PRFINALIZAPERIODOGRACIA'
   AND OWNER = 'OPEN'
   AND OBJECT_TYPE = 'PROCEDURE';

  IF nuConta = 1 THEN
      EXECUTE IMMEDIATE 'DROP PROCEDURE OPEN.LDC_PRFINALIZAPERIODOGRACIA';
  END IF;
END;
/