DECLARE
  nuConta NUMBER;
BEGIN
SELECT COUNT(1) INTO nuConta
  FROM DBA_OBJECTS
  WHERE OBJECT_NAME = 'LDC_PRGENTRAMITELARETECPRIO'
   AND OWNER = 'OPEN'
   AND OBJECT_TYPE='PROCEDURE';

  IF nuConta >= 1 THEN
      EXECUTE IMMEDIATE 'DROP PROCEDURE OPEN.LDC_PRGENTRAMITELARETECPRIO';
  END IF;
END;
/