set serveroutput on;
PROMPT BORRAR PRGENERANORTASPRONTOPAGO
DECLARE
  nuConta NUMBER;
BEGIN
  SELECT COUNT(*) INTO nuConta
  FROM dba_objects
  WHERE object_name = 'PRGENERANORTASPRONTOPAGO'
   AND OWNER = 'OPEN'
   AND OBJECT_TYPE <> 'SYNONYM';
   
  IF nuConta > 0 then
    EXECUTE IMMEDIATE 'DROP PROCEDURE PRGENERANORTASPRONTOPAGO';
  END IF;
EXCEPTION
    WHEN OTHERS THEN 
        dbms_output.put_line('No se pudo borrar procedimiento PRGENERANORTASPRONTOPAGO, '||sqlerrm); 
END;
/