
update master_personalizaciones
set comentario = 'FRAMEWORK OPEN'
where nombre in (select name from sa_executable)
and comentario is null;


update master_personalizaciones
set comentario = 'CIERRE COMERCIAL'
where nombre in
(
'LDC_PROGENCIERRE_RECAUDO',
'LDC_PROGENCIERRE_BRILLA',
'LDC_PROGENCIERRE_VARIOS',
'LDC_PROGENCIERRE_CREG',
'LDC_CIER_PROD_H1',
'LDC_CIER_PROD_H2',
'LDC_CIER_PROD_H3',
'LDC_CIER_PROD_H4',
'LDC_CIER_PROD_H5',
'LDC_CIER_PROD_H6',
'LDC_CIER_PROD_H7',
'LDC_CIER_PROD_H8',
'LDC_CIER_PROD_H9',
'LDC_CIER_PROD_H10',
'LDC_CIER_PROD_H11',
'LDC_CIER_PROD_H12',
'LDC_PROGENCIERRE',
'LDC_PROGENCIERFACT',
'LDC_PROJECJPROCMES',
'LDC_LLENA_RECAUDO_MES_SUCU',
'LDC_LLENAREPORTFRACFRAP',
'LDC_CIERRE_LRMA',
'LDC_PROCONTROLREINTE',
'LDC_PROLLENAVENTASCIERREBRILLA',
'LDC_PROLLESTADISTICASBRILLA',
'LDC_LLENASALBITEMP',
'LDC_LLENADIFERIDO',
'LDC_LLENACONTRATO',
'LDC_LLENASALCUINI',
'LDC_BCCREG',
'LDC_LLENASESUCIER_H1',
'LDC_ACTCONCCEROULTPLAFI',
'LDC_PROCCARGDATSESU',
'LDC_LLENASESUCIER_H2',
'LDC_ACTCONCCEROULTPLAFI2',
'LDC_LLENASESUCIER_H3',
'LDC_ACTCONCCEROULTPLAFI3',
'LDC_LLENASESUCIER_H4',
'LDC_ACTCONCCEROULTPLAFI4',
'LDC_LLENASESUCIER_H5',
'LDC_ACTCONCCEROULTPLAFI5',
'LDC_LLENASESUCIER_H6',
'LDC_ACTCONCCEROULTPLAFI6',
'LDC_LLENASESUCIER_H7',
'LDC_ACTCONCCEROULTPLAFI7',
'LDC_LLENASESUCIER_H8',
'LDC_ACTCONCCEROULTPLAFI8',
'LDC_LLENASESUCIER_H9',
'LDC_ACTCONCCEROULTPLAFI9',
'LDC_LLENASESUCIER_H10',
'LDC_ACTCONCCEROULTPLAFI10',
'LDC_LLENASESUCIER_H11',
'LDC_ACTCONCCEROULTPLAFI11',
'LDC_ACTCONCCEROULTPLAFI12',
'LDC_PROCRESUMENSESUCIER',
'LDC_PROCCARTCONCCIERRE_DB',
'LDC_CARTCASTIGADA_CIERRE',
'LDC_PROCSINCROCARTBRILLCI',
'LDC_PROGENCARTTIPOCONC',
'LDC_PROCLLENAECUACIONCARTERA',
'LDC_PROCCANTUSUAEDAMORLOC',
'LDC_PROCCIERCARTREFINANC',
'LDC_LLENACONTRIBUCIONCIERRE',
'LDC_LLENASUBSIDIOCIERRE',
'LDC_USUARIOSEXENTOS'
);

commit;
/