update  master_personalizaciones set COMENTARIO = 'MIGRADO ADM_PERSON'
where  NOMBRE in (
'LDC_FVATELSUBSCRIBER',
'LDC_FSBRETORNANOMBMES',
'LDC_FSBVALIDACASOSINSTALA',
'LDC_FUNCUOTPAIDDF',
'LDC_FUNFECHINTEMP',
'LDC_RETORNAPLANFINMAYPRIOR',
'FBLGENERATRAMITEREPARA',
'FSBVALCRITADICRECONEX',
'LDC_FNCRETORNAOTENCUECONCCERO',
'LDC_FSBACTIV_BLOQ_OSF',
'LDC_FSBRETORNARESPPRENENCUES',
'LDC_PLANFINMAYPRIOR',
'LDC_RETORNAAREASERVICIO',
'FNUGETITEMOSF_ROLLOUT',
'FNUOBTPERCONSANTE');
commit;
/