SELECT P1.SUSCRIPTION_ID, COUNT(1)
FROM LD_POLICY P1
WHERE P1.STATE_POLICY = 1
AND EXISTS 
(
    SELECT P2.SUSCRIPTION_ID
    FROM LD_POLICY P2
    WHERE P2.STATE_POLICY = 1
    AND  P2.SUSCRIPTION_ID = P1.SUSCRIPTION_ID 
    AND P2.PRODUCT_LINE_ID = 311 
)
AND EXISTS 
(
    SELECT P3.SUSCRIPTION_ID
    FROM LD_POLICY P3
    WHERE P3.STATE_POLICY = 1
    AND  P3.SUSCRIPTION_ID = P1.SUSCRIPTION_ID 
    AND P3.PRODUCT_LINE_ID <> 311 
)
GROUP BY P1.SUSCRIPTION_ID
HAVING COUNT(1) > 3
ORDER BY COUNT(1) DESC