set serveroutput on;
PROMPT BORRAR PROCEDIMIENTO LDCPROCCREATRAMFLUJSACXML
DECLARE
  nuConta NUMBER;
BEGIN
  SELECT COUNT(*) INTO nuConta
  FROM dba_objects
  WHERE object_name = 'LDCPROCCREATRAMFLUJSACXML'
   AND OWNER = 'OPEN'
   AND OBJECT_TYPE <> 'SYNONYM';
   
  IF nuConta > 0 then
    EXECUTE IMMEDIATE 'DROP PROCEDURE LDCPROCCREATRAMFLUJSACXML';
    dbms_output.put_line('PROCEDURE LDCPROCCREATRAMFLUJSACXML BORRADO');
  END IF;
EXCEPTION
    WHEN OTHERS THEN 
        dbms_output.put_line('No se pudo borrar el procedimiento LDCPROCCREATRAMFLUJSACXML, '||sqlerrm); 
END;
/