CREATE OR REPLACE PACKAGE MO_BSREGISTERWITHXML IS
   FUNCTION FSBVERSION
    RETURN VARCHAR2;
   PROCEDURE REGISTERREQUESTBYXML( ISBREQUESTXML IN VARCHAR2, ONUPACKAGEID OUT MO_PACKAGES.PACKAGE_ID%TYPE, ONUMOTIVEID OUT MO_MOTIVE.MOTIVE_ID%TYPE, ONUERRORCODE OUT GE_MESSAGE.MESSAGE_ID%TYPE, OSBERRORMESSAGE OUT VARCHAR2 );
   FUNCTION FBLISREGISTERXML( ONUERRORCODE OUT GE_MESSAGE.MESSAGE_ID%TYPE, OSBERRORMESSAGE OUT VARCHAR2 )
    RETURN BOOLEAN;
END MO_BSREGISTERWITHXML;
/


