PACKAGE Or_BcOrderActivities IS




























































































































































































































































































































































































































































































	    
	
        








        TYPE TYRCATTRIBADIT IS RECORD
        (
            NAME_ATTRIBUTE       GE_ATTRIBUTES.NAME_ATTRIBUTE%TYPE,
            STATEMENT_ID         OR_ACTIVITY_ADD_ATTS.STATEMENT_ID%TYPE,
            VALID_RULE_NAME      OR_ACTIVITY_ADD_ATTS.VALID_RULE_NAME%TYPE,
            DEFAULT_VALUE        OR_ACTIVITY_ADD_ATTS.DEFAULT_VALUE%TYPE,
            ATTRIBUTE_TYPE_ID    GE_ATTRIBUTES.ATTRIBUTE_TYPE_ID%TYPE,
            ATTRIBUTE_TYPE_NAME  GE_ATTRIBUTES_TYPE.DESCRIPTION%TYPE,
            LENGTH               GE_ATTRIBUTES.LENGTH%TYPE,
            PRECISION            GE_ATTRIBUTES.PRECISION%TYPE,
            SCALE                GE_ATTRIBUTES.SCALE%TYPE,
            DISPLAY_NAME         GE_ATTRIBUTES.DISPLAY_NAME%TYPE,
            REQUIRED             OR_ACTIVITY_ADD_ATTS.REQUIRED%TYPE,
            DISPLAY_ORDER        OR_ACTIVITY_ADD_ATTS.DISPLAY_ORDER%TYPE
        );
        
        








        SUBTYPE STYATTRIBADITNDX IS GE_ATTRIBUTES.NAME_ATTRIBUTE%TYPE;
        TYPE TYTBATTRIBADIT IS TABLE OF TYRCATTRIBADIT INDEX BY STYATTRIBADITNDX;
        
        TYPE TYTBATTRIBADITRF IS TABLE OF TYRCATTRIBADIT;
        
        









        TYPE TYRCACTATTRIBADITCONF IS RECORD
        (
            ACTIVITY_ID       GE_ITEMS.ITEMS_ID%TYPE,
            CLASS_CAUSAL_ID   GE_CLASS_CAUSAL.CLASS_CAUSAL_ID%TYPE,
            TB_ATTRIBS        OR_BCORDERACTIVITIES.TYTBATTRIBADIT
        );

        









        SUBTYPE STYACTATTADITCONFNDX IS BINARY_INTEGER;
        TYPE TYTBACTATTRIBADITCONF IS TABLE OF TYRCACTATTRIBADITCONF INDEX BY STYACTATTADITCONFNDX;


        TYPE TYRCACTIVITIESCONF IS RECORD
        (
            NUACTIVITYID       OR_TASK_TYPES_ITEMS.ITEMS_ID%TYPE,
            NUTASKTYPEID       OR_TASK_TYPES_ITEMS.TASK_TYPE_ID%TYPE,
            NUUSE              GE_ITEMS.USE_%TYPE,
            NUPRIORITY         OR_TASK_TYPE.PRIORITY%TYPE,
            NUOBJECTID         GE_OBJECT.OBJECT_ID%TYPE,
            NUOBJECTNAME       GE_OBJECT.NAME_%TYPE,
            SBLEGALIZEOBJECT   GE_OBJECT.NAME_%TYPE
        );

        TYPE TYTBACTIVITIESCONF  IS TABLE  OF TYRCACTIVITIESCONF INDEX BY VARCHAR2(16);

        TYPE TYRCACTIVITIESATTRIBCONF IS RECORD
        (
			NUACTIVITYID         GE_ITEMS_ATTRIBUTES.ITEMS_ID%TYPE,
            
            NUATTRIBUTE1         GE_ITEMS_ATTRIBUTES.ATTRIBUTE_1_ID%TYPE,
            SBATTRIBUTE1         GE_ATTRIBUTES.NAME_ATTRIBUTE%TYPE,
            SBDISPLAYNAME1       GE_ATTRIBUTES.DISPLAY_NAME%TYPE,
            NUATTRIBUTETYPE1     GE_ATTRIBUTES.ATTRIBUTE_TYPE_ID%TYPE,
            NULENGTH1            GE_ATTRIBUTES.LENGTH%TYPE,
            NUPRECISION1         GE_ATTRIBUTES.PRECISION%TYPE,
            NUSCALE1             GE_ATTRIBUTES.SCALE%TYPE,
            SBREQUIRED1          GE_ITEMS_ATTRIBUTES.REQUIRED1%TYPE,
            NUINITEXPRESSION1    GE_ITEMS_ATTRIBUTES.INIT_EXPRESSION_1_ID%TYPE,
			NUVALIDEXPRESSION1   GE_ITEMS_ATTRIBUTES.VALID_EXPRESSION_1_ID%TYPE,
			NUSTATEMENT1         GE_ITEMS_ATTRIBUTES.STATEMENT_1_ID%TYPE,
			NUCOMPONENT1         GE_ITEMS_ATTRIBUTES.COMPONENT_1_ID%TYPE,
            NUITEMS1             GE_ITEMS.ITEMS_ID%TYPE,
            NUELEMENTTYPE1       GE_ITEMS.ELEMENT_TYPE_ID%TYPE,
            SBACTION1            GE_ITEMS.USE_%TYPE,
            
			NUATTRIBUTE2         GE_ITEMS_ATTRIBUTES.ATTRIBUTE_2_ID%TYPE,
			SBATTRIBUTE2         GE_ATTRIBUTES.NAME_ATTRIBUTE%TYPE,
            SBDISPLAYNAME2       GE_ATTRIBUTES.DISPLAY_NAME%TYPE,
            NUATTRIBUTETYPE2     GE_ATTRIBUTES.ATTRIBUTE_TYPE_ID%TYPE,
            NULENGTH2            GE_ATTRIBUTES.LENGTH%TYPE,
            NUPRECISION2         GE_ATTRIBUTES.PRECISION%TYPE,
            NUSCALE2             GE_ATTRIBUTES.SCALE%TYPE,
            SBREQUIRED2          GE_ITEMS_ATTRIBUTES.REQUIRED2%TYPE,
			NUINITEXPRESSION2    GE_ITEMS_ATTRIBUTES.INIT_EXPRESSION_2_ID%TYPE,
			NUVALIDEXPRESSION2   GE_ITEMS_ATTRIBUTES.VALID_EXPRESSION_2_ID%TYPE,
			NUSTATEMENT2         GE_ITEMS_ATTRIBUTES.STATEMENT_2_ID%TYPE,
			NUCOMPONENT2         GE_ITEMS_ATTRIBUTES.COMPONENT_2_ID%TYPE,
            NUITEMS2             GE_ITEMS.ITEMS_ID%TYPE,
            NUELEMENTTYPE2       GE_ITEMS.ELEMENT_TYPE_ID%TYPE,
            SBACTION2            GE_ITEMS.USE_%TYPE,
            
            NUATTRIBUTE3         GE_ITEMS_ATTRIBUTES.ATTRIBUTE_3_ID%TYPE,
			SBATTRIBUTE3         GE_ATTRIBUTES.NAME_ATTRIBUTE%TYPE,
            SBDISPLAYNAME3       GE_ATTRIBUTES.DISPLAY_NAME%TYPE,
            NUATTRIBUTETYPE3     GE_ATTRIBUTES.ATTRIBUTE_TYPE_ID%TYPE,
            NULENGTH3            GE_ATTRIBUTES.LENGTH%TYPE,
            NUPRECISION3         GE_ATTRIBUTES.PRECISION%TYPE,
            NUSCALE3             GE_ATTRIBUTES.SCALE%TYPE,
            SBREQUIRED3          GE_ITEMS_ATTRIBUTES.REQUIRED3%TYPE,
            NUINITEXPRESSION3    GE_ITEMS_ATTRIBUTES.INIT_EXPRESSION_3_ID%TYPE,
			NUVALIDEXPRESSION3   GE_ITEMS_ATTRIBUTES.VALID_EXPRESSION_3_ID%TYPE,
			NUSTATEMENT3         GE_ITEMS_ATTRIBUTES.STATEMENT_3_ID%TYPE,
			NUCOMPONENT3         GE_ITEMS_ATTRIBUTES.COMPONENT_3_ID%TYPE,
			NUITEMS3             GE_ITEMS.ITEMS_ID%TYPE,
            NUELEMENTTYPE3       GE_ITEMS.ELEMENT_TYPE_ID%TYPE,
            SBACTION3            GE_ITEMS.USE_%TYPE,
            
			NUATTRIBUTE4         GE_ITEMS_ATTRIBUTES.ATTRIBUTE_4_ID%TYPE,
			SBATTRIBUTE4         GE_ATTRIBUTES.NAME_ATTRIBUTE%TYPE,
			SBDISPLAYNAME4       GE_ATTRIBUTES.DISPLAY_NAME%TYPE,
			NUATTRIBUTETYPE4     GE_ATTRIBUTES.ATTRIBUTE_TYPE_ID%TYPE,
            NULENGTH4            GE_ATTRIBUTES.LENGTH%TYPE,
            NUPRECISION4         GE_ATTRIBUTES.PRECISION%TYPE,
            NUSCALE4             GE_ATTRIBUTES.SCALE%TYPE,
            SBREQUIRED4          GE_ITEMS_ATTRIBUTES.REQUIRED4%TYPE,
			NUINITEXPRESSION4    GE_ITEMS_ATTRIBUTES.INIT_EXPRESSION_4_ID%TYPE,
			NUVALIDEXPRESSION4   GE_ITEMS_ATTRIBUTES.VALID_EXPRESSION_4_ID%TYPE,
			NUSTATEMENT4         GE_ITEMS_ATTRIBUTES.STATEMENT_4_ID%TYPE,
			NUCOMPONENT4         GE_ITEMS_ATTRIBUTES.COMPONENT_4_ID%TYPE,
			NUITEMS4             GE_ITEMS.ITEMS_ID%TYPE,
            NUELEMENTTYPE4       GE_ITEMS.ELEMENT_TYPE_ID%TYPE,
            SBACTION4            GE_ITEMS.USE_%TYPE
        );

        TYPE TYTBACTIVITIESATTRIBCONF  IS TABLE  OF TYRCACTIVITIESATTRIBCONF INDEX BY VARCHAR2(16);

    











        TYPE TYRCORDERACTIVITIES IS RECORD
        (
          NUORDERACTIVITY       OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
          NUORDERITEMID         OR_ORDER_ACTIVITY.ORDER_ITEM_ID%TYPE,
          NUPACKAGEID           OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
          NUMOTIVEID            OR_ORDER_ACTIVITY.MOTIVE_ID%TYPE,
          NUCOMPONENTID         OR_ORDER_ACTIVITY.COMPONENT_ID%TYPE,
          NUINSTANCEID          OR_ORDER_ACTIVITY.INSTANCE_ID%TYPE,
          NUADDRESSID           OR_ORDER_ACTIVITY.ADDRESS_ID%TYPE,
          NUELEMENTID           OR_ORDER_ACTIVITY.ELEMENT_ID%TYPE,
          NUSUBSCRIBERID        OR_ORDER_ACTIVITY.SUBSCRIBER_ID%TYPE,
          NUSUBSCRIPTIONID      OR_ORDER_ACTIVITY.SUBSCRIPTION_ID%TYPE,
          NUPRODUCTID           OR_ORDER_ACTIVITY.PRODUCT_ID%TYPE,
          NUPROCESSID           OR_ORDER_ACTIVITY.PROCESS_ID%TYPE,
          NUACTIVITYID          OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
          NULEGALIZECOUNT       OR_ORDER_ITEMS.LEGAL_ITEM_AMOUNT%TYPE,
          NUSTATUSLEGALIZE      OR_ORDER_ACTIVITY.STATUS%TYPE,   
          NUACTIVITYGROUPID     OR_ORDER_ACTIVITY.ACTIVITY_GROUP_ID%TYPE,
          NUACTIVITYSEQUENCE    OR_ORDER_ACTIVITY.SEQUENCE_%TYPE,
          NUORIGINACTIVITY      OR_ORDER_ACTIVITY.ORIGIN_ACTIVITY_ID%TYPE,
          NUOPERSECTOR          OR_ORDER_ACTIVITY.OPERATING_SECTOR_ID%TYPE,
          SBCOMMENT             OR_ORDER_ACTIVITY.COMMENT_%TYPE,
          DTEXECSTIMATEDATE     OR_ORDER_ACTIVITY.EXEC_ESTIMATE_DATE%TYPE,
          NUTASKTYPE            OR_ORDER_ACTIVITY.TASK_TYPE_ID%TYPE,
          SBATTRIBUTEVALUE1     OR_ORDER_ACTIVITY.VALUE1%TYPE,
          SBATTRIBUTEVALUE2     OR_ORDER_ACTIVITY.VALUE2%TYPE,
          SBATTRIBUTEVALUE3     OR_ORDER_ACTIVITY.VALUE3%TYPE,
          SBATTRIBUTEVALUE4     OR_ORDER_ACTIVITY.VALUE4%TYPE,
          SBTRASLATEACTIVITY    VARCHAR2(1) ,
          SBISCOMPENSATE        OR_ORDER_ACTIVITY.COMPENSATED%TYPE,
          BLREGENACTIVITY       BOOLEAN,
          NUTRYLEGALIZETIMES    OR_ORDER_ACTIVITY.LEGALIZE_TRY_TIMES%TYPE,
          SBTAGNAME             OR_ORDER_ACTIVITY.WF_TAG_NAME%TYPE,
          NUGENERATEDACT        OR_ORDER_ACTIVITY.GENERATED_ACT_ID%TYPE,
          NUEQUIPCOMPONENT      OR_ORDER_ACTIVITY.EQUIP_COMPONENT_ID%TYPE,
          SBSERIAL              GE_ITEMS_SERIADO.SERIE%TYPE
        );

        TYPE TYTBORDERACTIVITIES IS TABLE  OF TYRCORDERACTIVITIES INDEX BY BINARY_INTEGER;

        TYPE TYRCELEMENTSCONF IS RECORD
        (
         INUELEMENTTYPE IF_ELEMENT_TYPE.ELEMENT_TYPE_ID%TYPE,
         INUINITINDEX   NUMBER,
         INUFINALINDEX   NUMBER
        );

        TYPE TYTBELEMENTSCONF IS TABLE  OF TYRCELEMENTSCONF INDEX BY BINARY_INTEGER;

        TYPE TYRCELEMENTITEMSCONF IS RECORD
        (
         INUITEMSID         GE_ITEMS.ITEMS_ID%TYPE,
         INUATTRIBUTEID     GE_ATTRIBUTES.ATTRIBUTE_ID%TYPE,
         ISBACTION          VARCHAR2(2),
         INUELEMENTTYPEID   IF_ELEMENT_TYPE.ELEMENT_TYPE_ID%TYPE,
         INUELEMENTCLASSID  IF_ELEMENT_CLASS.CLASS_ID%TYPE
        );
        TYPE TYTBELEMENTITEMSCONF IS TABLE  OF TYRCELEMENTITEMSCONF INDEX BY BINARY_INTEGER;

        TYPE TYRCORDERANDACTIVITY IS RECORD
        (
          NUORDERACTIVITY       OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
          NUORDERITEMID         OR_ORDER_ACTIVITY.ORDER_ITEM_ID%TYPE,
          NUORDERID             OR_ORDER_ACTIVITY.ORDER_ID%TYPE,
          NUACTIVITYID          OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE
        );
        TYPE TYTBORDERANDACTIVITY IS TABLE OF TYRCORDERANDACTIVITY INDEX BY BINARY_INTEGER;

        
        TYPE TYRCACTIVITYITEM   IS RECORD
        (
            NUACTIVITYID        OR_ORDER_ITEMS.ORDER_ACTIVITY_ID%TYPE,
            SBELEMENTCODE       OR_ORDER_ITEMS.ELEMENT_CODE%TYPE,
            NUITEMID            OR_ORDER_ITEMS.ITEMS_ID%TYPE,
            NUELEMENTTYPEID     NUMBER,
            NUELEMENTCLASSID    IF_ELEMENT_CLASS.CLASS_ID%TYPE,
            NUELEMENTID         OR_ORDER_ITEMS.ELEMENT_ID%TYPE,
            SBACTION            VARCHAR2(1),
            SBADDDATA           VARCHAR2(200)
        );

        TYPE TYTBACTIVITYITEMS  IS TABLE OF TYRCACTIVITYITEM INDEX BY BINARY_INTEGER;

    	TYPE TYDATAACTIVITIES IS RECORD (
                                            ORDER_ACTIVITY_ID   OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
                                            ACTIVITY_ID         OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
                                            PRODUCT_ID          OR_ORDER_ACTIVITY.PRODUCT_ID%TYPE,
                                            PRODUCT_TYPE_ID     PR_PRODUCT.PRODUCT_TYPE_ID%TYPE,
                                            SUBSCRIBER_ID       OR_ORDER_ACTIVITY.SUBSCRIBER_ID%TYPE,
                                            SUBSCRIBER_NAME     VARCHAR2(200),
                                            IDENT_TYPE_ID       GE_SUBSCRIBER.IDENT_TYPE_ID%TYPE,
                                            IDENTIFICATION      GE_SUBSCRIBER.IDENTIFICATION%TYPE,
                                            SUBSCRIPTION_ID     OR_ORDER_ACTIVITY.SUBSCRIPTION_ID%TYPE,
                                            PACKAGE_ID          OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
                                            MOTIVE_ID           OR_ORDER_ACTIVITY.MOTIVE_ID%TYPE,
                                            COMPONENT_ID        OR_ORDER_ACTIVITY.COMPONENT_ID%TYPE,
                                            ELEMENT_ID          OR_ORDER_ACTIVITY.ELEMENT_ID%TYPE
    	);
    	TYPE TBDATAACTIVITIES IS TABLE OF TYDATAACTIVITIES
        INDEX BY BINARY_INTEGER;
        
        TYPE TYTBITEMS IS TABLE OF VARCHAR2(50) INDEX BY VARCHAR2(50);
        
       TYPE TYRCORDERACTIVITY IS RECORD
        (
            ORDERID         OR_ORDER.ORDER_ID%TYPE,
            ORDERACTIVITYID OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
            ACTIVITYID      GE_ITEMS.ITEMS_ID%TYPE,
            STATUS          OR_ORDER_ACTIVITY.STATUS%TYPE,
            COMPENSATED     OR_ORDER_ACTIVITY.COMPENSATED%TYPE,
            PRODUCTID       PR_PRODUCT.PRODUCT_ID%TYPE,
            COMPONENTID     PR_COMPONENT.COMPONENT_ID%TYPE,
            IDITEMSTIPO     GE_ITEMS.ID_ITEMS_TIPO%TYPE,
            IDITEMSGAMA     GE_ITEMS_GAMA.ID_ITEMS_GAMA%TYPE
        );

        TYPE TYTBORDERACTIVITY  IS TABLE OF TYRCORDERACTIVITY INDEX BY BINARY_INTEGER;

        
        TYPE TYTBACTIVITYIDS IS TABLE OF OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE INDEX BY BINARY_INTEGER;
        
        
        TYPE TYTBCAPABYPRODTYPE  IS TABLE OF NUMBER INDEX BY BINARY_INTEGER;

        








        TYPE TYRCACTORDBYINST IS RECORD
        (
            NUORDERID       OR_ORDER_ACTIVITY.ORDER_ID%TYPE,
            NUMOTIVEID      OR_ORDER_ACTIVITY.MOTIVE_ID%TYPE,
            NUPACKAGEID     OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
            NUSUBSCRIBERID  OR_ORDER_ACTIVITY.SUBSCRIBER_ID%TYPE

        );
        
        TYPE TYTBACTORDBYINST  IS TABLE OF TYRCACTORDBYINST INDEX BY BINARY_INTEGER;
        
        TYPE TYRCORDACTITEM IS RECORD
        (
            ORDER_ACTIVITY_ID   OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
            ORDER_ITEM_ID       OR_ORDER_ACTIVITY.ORDER_ITEM_ID%TYPE
        );

        TYPE TYTBORDACTITEM IS TABLE OF TYRCORDACTITEM INDEX BY UT_DATATYPES.STYNUMBERINDEX;
        
        








        TYPE TYRCBASICORDER IS RECORD
        (
            ORDER_ID                OR_ORDER.ORDER_ID%TYPE,
            ORDER_STATUS_ID         OR_ORDER.ORDER_STATUS_ID%TYPE,
            ORDER_STATUS_DESC       OR_ORDER_STATUS.DESCRIPTION%TYPE,
            OPERATING_UNIT_ID       OR_ORDER.OPERATING_UNIT_ID%TYPE,
            OPERATING_UNIT_DESC     OR_OPERATING_UNIT.NAME%TYPE,
            OPERATING_SECTOR_ID     OR_ORDER.OPERATING_SECTOR_ID%TYPE,
            OPERATING_SECTOR_DESC   OR_OPERATING_SECTOR.DESCRIPTION%TYPE,
            ASSIGNED_DATE           OR_ORDER.ASSIGNED_DATE%TYPE,
            ARRANGED_HOUR           OR_ORDER.ARRANGED_HOUR%TYPE,
            ASSIGNED_WITH           OR_ORDER.ASSIGNED_WITH%TYPE,
            CREATED_DATE            OR_ORDER.CREATED_DATE%TYPE,
            EXECUTION_FINAL_DATE    OR_ORDER.EXECUTION_FINAL_DATE%TYPE,
            EXEC_ESTIMATE_DATE      OR_ORDER.EXEC_ESTIMATE_DATE%TYPE,
            EXEC_INITIAL_DATE       OR_ORDER.EXEC_INITIAL_DATE%TYPE,
            LEGALIZATION_DATE       OR_ORDER.LEGALIZATION_DATE%TYPE,
            MAX_DATE_TO_LEGALIZE    OR_ORDER.MAX_DATE_TO_LEGALIZE%TYPE,
            ASSO_UNIT_ID            OR_ORDER.ASSO_UNIT_ID%TYPE,
            ASSO_UNIT_DESC          OR_OPERATING_UNIT.NAME%TYPE,
            TASK_TYPE_ID            OR_ORDER.TASK_TYPE_ID%TYPE,
            TASK_TYPE_DESC          OR_TASK_TYPE.DESCRIPTION%TYPE,
            PRIORITY                OR_ORDER.PRIORITY%TYPE
        );

        








        TYPE TYRCBASICORDERACT IS RECORD
        (
            ACTIVITY_ID         OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
            ADDRESS_ID          OR_ORDER_ACTIVITY.ADDRESS_ID%TYPE,
            ORDER_ACTIVITY_ID   OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
            PACKAGE_ID          OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
            STATUS              OR_ORDER_ACTIVITY.STATUS%TYPE,
            TASK_TYPE_ID        OR_ORDER_ACTIVITY.TASK_TYPE_ID%TYPE,
            COMMENT_            OR_ORDER_ACTIVITY.COMMENT_%TYPE,
            ELEMENT_ID          OR_ORDER_ACTIVITY.ELEMENT_ID%TYPE,
            MOTIVE_ID           OR_ORDER_ACTIVITY.MOTIVE_ID%TYPE,
            PROCESS_ID          OR_ORDER_ACTIVITY.PROCESS_ID%TYPE,
            PRODUCT_ID          OR_ORDER_ACTIVITY.PRODUCT_ID%TYPE,
            REGISTER_DATE       OR_ORDER_ACTIVITY.REGISTER_DATE%TYPE,
            SUBSCRIBER_ID       OR_ORDER_ACTIVITY.SUBSCRIBER_ID%TYPE,
            SUBSCRIPTION_ID     OR_ORDER_ACTIVITY.SUBSCRIPTION_ID%TYPE
        );

        TYPE TYTBBASICORDERACT IS TABLE OF TYRCBASICORDERACT INDEX BY UT_DATATYPES.STYNUMBERINDEX;

        








        TYPE TYRCBASICORDERCOM IS RECORD
        (
            ORDER_COMMENT_ID    OR_ORDER_COMMENT.ORDER_COMMENT_ID%TYPE,
            COMMENT_TYPE_ID     OR_ORDER_COMMENT.COMMENT_TYPE_ID%TYPE,
            COMMENT_DESCRIPTION GE_COMMENT_TYPE.DESCRIPTION%TYPE,
            ORDER_COMMENT       OR_ORDER_COMMENT.ORDER_COMMENT%TYPE,
            REGISTER_DATE       OR_ORDER_COMMENT.REGISTER_DATE%TYPE,
            PERSON_ID           GE_PERSON.PERSON_ID%TYPE,
            PERSON_NAME         GE_PERSON.NAME_%TYPE
        );

       TYPE TYTBBASICORDERCOM IS TABLE OF TYRCBASICORDERCOM INDEX BY UT_DATATYPES.STYNUMBERINDEX;

	
    CSBPROGRAMMABLE     CONSTANT VARCHAR2(1) := 'P';
    CSBREPROGRAMMABLE   CONSTANT VARCHAR2(1) := 'R';
    
    
    CNUPROCACTSUPPORT   CONSTANT OR_ORDER_ACTIVITY.PROCESS_ID%TYPE := 15;
    
	

    
    FUNCTION FSBVERSION  RETURN UT_DATATYPES.STYSAOVERSION;

    
















    CURSOR  CUPENDORDBYPACK
    (
        INUPACKAGEID    IN   OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE
    )
    IS
        SELECT  /*+ index(or_order_activity IDX_OR_ORDER_ACTIVITY_06) */
                OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID,
                OR_ORDER_ACTIVITY.ORDER_ITEM_ID,
                OR_ORDER_ACTIVITY.ORDER_ID,
                OR_ORDER_ACTIVITY.ACTIVITY_ID
        FROM    OR_ORDER_ACTIVITY /*+ Or_BcOrderActivities.cuPendOrdByPack */
        WHERE   OR_ORDER_ACTIVITY.PACKAGE_ID = INUPACKAGEID;


     



















    CURSOR CUPENDORDACTBYPACK
    (
        INUPACKAGEID    IN   OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE
    )
    IS
        SELECT  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID,
                OR_ORDER_ACTIVITY.ORDER_ITEM_ID,
                OR_ORDER_ACTIVITY.ORDER_ID,
                OR_ORDER_ACTIVITY.ACTIVITY_ID,
                OR_ORDER_ACTIVITY.PROCESS_ID
        FROM    OR_ORDER_ACTIVITY
        WHERE   OR_ORDER_ACTIVITY.PACKAGE_ID = INUPACKAGEID
        AND     OR_ORDER_ACTIVITY.STATUS <> OR_BOCONSTANTS.CSBFINISHSTATUS;


     















    CURSOR  CUPENDORDACTBYMOT
    (
        INUMOTIVEID    IN   OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE
    )
    IS
        SELECT  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID,
                OR_ORDER_ACTIVITY.ORDER_ITEM_ID,
                OR_ORDER_ACTIVITY.ORDER_ID,
                OR_ORDER_ACTIVITY.ACTIVITY_ID
        FROM   OR_ORDER_ACTIVITY
        WHERE  OR_ORDER_ACTIVITY.MOTIVE_ID = INUMOTIVEID
        AND    OR_ORDER_ACTIVITY.STATUS <> OR_BOCONSTANTS.CSBFINISHSTATUS;
        

     















    CURSOR  CUPENDORDACTBYCOMP
    (
        INUCOMPONENTID    IN   OR_ORDER_ACTIVITY.COMPONENT_ID%TYPE
    )
    IS
        SELECT  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID,
                OR_ORDER_ACTIVITY.ORDER_ITEM_ID,
                OR_ORDER_ACTIVITY.ORDER_ID,
                OR_ORDER_ACTIVITY.ACTIVITY_ID
        FROM   OR_ORDER_ACTIVITY
        WHERE  OR_ORDER_ACTIVITY.COMPONENT_ID = INUCOMPONENTID
        AND    OR_ORDER_ACTIVITY.STATUS <> OR_BOCONSTANTS.CSBFINISHSTATUS;

    
















    CURSOR CUISDIAGNOSEORDER
    (
        INUORDER    IN NUMBER
    )
    IS
        SELECT  /*+ leading(or_order_activity)
                    index(or_order_activity IDX_OR_ORDER_ACTIVITY_05)
                */
                TT_DAMAGE.PACKAGE_ID
        FROM    /*+ OR_BCOrderActivities.cuIsDiagnoseOrder SAO307976 */
                OR_ORDER_ACTIVITY,
                TT_DAMAGE,
                GE_ITEMS
        WHERE   OR_ORDER_ACTIVITY.ACTIVITY_ID = GE_ITEMS.ITEMS_ID
        AND     TT_DAMAGE.PACKAGE_ID = OR_ORDER_ACTIVITY.PACKAGE_ID
        AND     GE_ITEMS.USE_ = OR_BOCONSTANTS.CSBCLIENT_MAINTENA_USE
        AND     OR_ORDER_ACTIVITY.ORDER_ID =  INUORDER
        AND     OR_ORDER_ACTIVITY.STATUS <> OR_BOCONSTANTS.CSBFINISHSTATUS
        AND     ROWNUM = 1;

    


















    CURSOR CUACTIVITYOUTAGE ( INUORDERID IN OR_ORDER_ACTIVITY.ORDER_ID%TYPE)
    IS
        SELECT 









                OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID,
                GE_ITEMS.ITEMS_ID ACTIVITY_ID,
                GE_ITEMS.DESCRIPTION,
                IF_NODE.ID ELEMENT_ID,
                IF_NODE.CODE,
                IF_NODE.COMPOSITE_CODE,
                IF_ELEMENT_TYPE.ELEMENT_TYPE_ID,
                IF_ELEMENT_TYPE.DESCRIPTION ELEMENT_TYPE_NAME,
                IF_ELEMENT_CLASS.CLASS_ID,
                IF_ELEMENT_CLASS.DESCRIPTION AS ELEMENT_CLASS_NAME
        FROM    OR_ORDER_ACTIVITY,
                GE_ITEMS,
                IF_NODE,
                IF_ELEMENT_CLASS,
                IF_ELEMENT_TYPE,
                OR_ACT_BY_ELE_TYPE
        WHERE
                IF_ELEMENT_TYPE.ELEMENT_TYPE_ID = IF_NODE.ELEMENT_TYPE_ID
        AND     IF_ELEMENT_CLASS.CLASS_ID = IF_NODE.CLASS_ID
        AND     IF_NODE.ELEMENT_TYPE_ID = IF_ELEMENT_CLASS.ELEMENT_TYPE_ID
        AND     IF_NODE.ELEMENT_TYPE_ID = OR_ACT_BY_ELE_TYPE.ELEMENT_TYPE_ID
        AND     IF_NODE.CLASS_ID = OR_ACT_BY_ELE_TYPE.CLASS_ID
        AND     IF_NODE.ID = OR_ORDER_ACTIVITY.ELEMENT_ID
        AND     OR_ACT_BY_ELE_TYPE.ITEMS_ID = OR_ORDER_ACTIVITY.ACTIVITY_ID
        AND     GE_ITEMS.ITEMS_ID = OR_ORDER_ACTIVITY.ACTIVITY_ID
        
        AND     OR_ACT_BY_ELE_TYPE.GENERATE_OUTAGE = GE_BOCONSTANTS.CSBYES
        AND     GE_ITEMS.ITEM_CLASSIF_ID = OR_BOCONSTANTS.CNUITEMS_CLASS_TO_ACTIVITY
        AND     OR_ORDER_ACTIVITY.ORDER_ID = INUORDERID;

           
    














    CURSOR CUPREVENTMAINTENORDER ( INUORDERID IN OR_ORDER.ORDER_ID%TYPE )
    IS
        SELECT  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID
          FROM  OR_ORDER_ACTIVITY
         WHERE  ORDER_ID = INUORDERID
           AND  PROCESS_ID = OR_BOCREATACTIVFROMELEMS.FNUPROCESS_PREV_MAINT
           AND  ROWNUM = 1;
           
    













    CURSOR CUCORRECTMAINTENORDER ( INUORDERID IN OR_ORDER.ORDER_ID%TYPE )
    IS
        SELECT  OR_ORDER_ACTIVITY.*, OR_ORDER_ACTIVITY.ROWID
          FROM  OR_ORDER_ACTIVITY
         WHERE  ORDER_ID = INUORDERID
           AND  PROCESS_ID = OR_BOCREATACTIVFROMELEMS.FNUPROCESS_CORR_MAINT
           AND  ROWNUM = 1;


    













    CURSOR CUORDERSBYDAMAGE
    (
        INUDAMAGEID IN MO_PACKAGES.PACKAGE_ID%TYPE
    )
    IS
        SELECT DISTINCT ORDER_ID
        FROM OR_ORDER_ACTIVITY
        WHERE PACKAGE_ID = INUDAMAGEID
          AND STATUS <> OR_BOCONSTANTS.CSBFINISHSTATUS;

                                 
    














    CURSOR CUGETACTIVITYPACKAGE
    (
        INUORDERID IN OR_ORDER.ORDER_ID%TYPE
    )
    IS
        SELECT PACKAGE_ID
        FROM OR_ORDER_ACTIVITY
        WHERE ORDER_ID = INUORDERID
          AND PACKAGE_ID IS NOT NULL
          AND ROWNUM = 1;


    



















     CURSOR CUISDAMAGEREPARORDER
     (
        INUORDER    IN NUMBER,
        INUDAMAGE   IN NUMBER
     )
     IS
      SELECT    /*+ leading(or_order_activity)
                    index(or_order_activity IDX_OR_ORDER_ACTIVITY_06) */
                OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID
        FROM    
                OR_ORDER_ACTIVITY, GE_ITEMS
        WHERE   OR_ORDER_ACTIVITY.ACTIVITY_ID = GE_ITEMS.ITEMS_ID
        AND     (
                 (GE_ITEMS.USE_ IN
                   (OR_BOCONSTANTS.CSBCLIENT_INSTALL_USE, OR_BOCONSTANTS.CSBCLIENT_RETIRE_USE,
                    OR_BOCONSTANTS.CSBNET_INSTALL, OR_BOCONSTANTS.CSBNET_RETIRE_USE,
                    OR_BOCONSTANTS.CSBCLIENT_FIX, OR_BOCONSTANTS.CSBCLIENT_WORK)
                 )
                 OR
                 (GE_ITEMS.USE_ IS NULL)
                )
        AND     OR_ORDER_ACTIVITY.ORDER_ID =  INUORDER
        AND     OR_ORDER_ACTIVITY.PACKAGE_ID = INUDAMAGE
        AND     ROWNUM = 1;


    

















     CURSOR CUISDAMAGEDIAGNOSORDER
     (
        INUORDER    IN NUMBER,
        INUDAMAGE   IN NUMBER
     )
      IS
      SELECT    /*+ leading(OR_order_activity)
                    index(OR_order_activity IDX_OR_ORDER_ACTIVITY_06)
                */
                OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID
        FROM    /*+ OR_BCOrderActivities.cuIsDamageDiagnosOrder SAO307976 */
                OR_ORDER_ACTIVITY, GE_ITEMS
        WHERE   OR_ORDER_ACTIVITY.ACTIVITY_ID = GE_ITEMS.ITEMS_ID
        AND     GE_ITEMS.USE_ = OR_BOCONSTANTS.CSBCLIENT_MAINTENA_USE
        AND     OR_ORDER_ACTIVITY.ORDER_ID =  INUORDER
        AND     OR_ORDER_ACTIVITY.PACKAGE_ID = INUDAMAGE
        AND     ROWNUM = 1;


    


















     CURSOR CUISPENDREPARORDER
     (
        INUORDER    IN NUMBER
     )
     IS
      SELECT    


                OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID
        FROM    /*+ OR_BCOrderActivities.cuIsPendReparOrder SAO307976 */
                OR_ORDER_ACTIVITY, TT_DAMAGE, GE_ITEMS
        WHERE   OR_ORDER_ACTIVITY.ACTIVITY_ID = GE_ITEMS.ITEMS_ID
        AND     TT_DAMAGE.PACKAGE_ID = OR_ORDER_ACTIVITY.PACKAGE_ID
        AND     (
                 (GE_ITEMS.USE_ IN
                   (OR_BOCONSTANTS.CSBCLIENT_INSTALL_USE, OR_BOCONSTANTS.CSBCLIENT_RETIRE_USE,
                    OR_BOCONSTANTS.CSBNET_INSTALL, OR_BOCONSTANTS.CSBNET_RETIRE_USE,
                    OR_BOCONSTANTS.CSBCLIENT_FIX, OR_BOCONSTANTS.CSBCLIENT_WORK)
                 )
                 OR
                 (GE_ITEMS.USE_ IS NULL)
                )
        AND     OR_ORDER_ACTIVITY.ORDER_ID =  INUORDER
        AND     OR_ORDER_ACTIVITY.STATUS <> OR_BOCONSTANTS.CSBFINISHSTATUS
        AND     ROWNUM = 1;

    















    CURSOR CUPENDORDACTBYSERIALITEM
    (
        INUSERIALITEMID         IN      OR_ORDER_ACTIVITY.SERIAL_ITEMS_ID%TYPE
    )
    IS
        SELECT  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID,
                OR_ORDER_ACTIVITY.ORDER_ITEM_ID,
                OR_ORDER_ACTIVITY.ORDER_ID,
                OR_ORDER_ACTIVITY.ACTIVITY_ID,
                OR_ORDER_ACTIVITY.PROCESS_ID
        FROM    OR_ORDER_ACTIVITY
        WHERE   OR_ORDER_ACTIVITY.SERIAL_ITEMS_ID = INUSERIALITEMID
        AND     OR_ORDER_ACTIVITY.STATUS <> OR_BOCONSTANTS.CSBFINISHSTATUS;

    
















    PROCEDURE GETACTGRBYINSTID
    (
        INUINSTANCEID   IN  OR_ORDER_ACTIVITY.INSTANCE_ID%TYPE,
        OTBPLANNEDGROUP OUT NOCOPY  UT_STRING.TYTB_STRING
    );


    













    PROCEDURE GETCONFIG (OTBACTIVITIESCONF OUT NOCOPY TYTBACTIVITIESCONF);

	PROCEDURE GETCONFIGATTRIBS (OTBACTIVITYATTRIBCONF OUT NOCOPY TYTBACTIVITIESATTRIBCONF);


    
    
    
    PROCEDURE GETACTIVITIESBYORDER
    (
        INUORDERID          IN  OR_ORDER.ORDER_ID%TYPE,
        OTBORDERACTIVITIES  OUT NOCOPY TYTBORDERACTIVITIES,
        BLGETACTIANULL      IN  BOOLEAN DEFAULT TRUE
    );


    



    PROCEDURE GETACTIVITYBYORACTID
    (
        INUORDERACTIVITYID  IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        ORCORDERACTIVITIES  OUT NOCOPY OR_BCORDERACTIVITIES.TYRCORDERACTIVITIES,
        BLGETACTIANULL      IN  BOOLEAN DEFAULT TRUE
    );
    
    
    
    
    FUNCTION FRFGETACTIVITIESBYORDER
    (
        INUORDERID              IN  OR_ORDER.ORDER_ID%TYPE
    )
    RETURN CONSTANTS.TYREFCURSOR;

    



    FUNCTION FRFGETACTIVITYBYORACTID
    (
        INUORDERACTIVITYID  IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE
    )
    RETURN CONSTANTS.TYREFCURSOR;

    






    PROCEDURE GETORDERIDGROUPBYADDRESS
    (
        INUADDRESSID   IN OR_ORDER_ACTIVITY.ADDRESS_ID%TYPE,
        INUTASKTYPEID  IN OR_ORDER_ACTIVITY.TASK_TYPE_ID%TYPE,
        INUACTIVITYID  IN GE_ITEMS.ITEMS_ID%TYPE,
        INUSTAGEID     IN OR_ORDER.STAGE_ID%TYPE,
        ONUORDERID     OUT OR_ORDER.ORDER_ID%TYPE
    );

    
    
    
    FUNCTION FBLHASPENDINGACTIVITIES
    (
        INUORDERID      IN  OR_ORDER.ORDER_ID%TYPE,
        INUINSTANCEID   IN  OR_ORDER_ACTIVITY.INSTANCE_ID%TYPE
    )
    RETURN BOOLEAN;

    













   
	

    













   
	

    














    PROCEDURE GETACTIVITYBYPACKAGE
    (
        INUPACKAGEID         IN   OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
        ISBSTATUS            IN   OR_ORDER_ACTIVITY.STATUS%TYPE,
        INUPROCESSID         IN   OR_ORDER_ACTIVITY.PROCESS_ID%TYPE,
        OTBACTIVITY          OUT  NOCOPY TYTBORDERANDACTIVITY
    );

    













    PROCEDURE GETEXECSTATEMENT
    (
        INUORDERACTIVITY    IN OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        INUSTATEMENTID      IN GE_STATEMENT.STATEMENT_ID%TYPE,
        OCURFGETDATA        OUT CONSTANTS.TYREFCURSOR
    );


    






















    FUNCTION FSBGETELEMENTCODE
    (
        INUACTIVITYID    IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        INUELEMTYPEID    IN  IF_ELEMENT_TYPE.ELEMENT_TYPE_ID%TYPE,
        ISBACTION        IN  VARCHAR2,
        IBLVALIDATE      IN  BOOLEAN := TRUE
    ) RETURN OR_ORDER_ITEMS.ELEMENT_CODE%TYPE;

    






















    PROCEDURE GETACTIVITYBYGROUP
    (
        INUACTIVITYGROUPID      IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        ISBACTIVITYSTATUS       IN  OR_ORDER_ACTIVITY.STATUS%TYPE,
        INUSEQUENC_             IN  OR_ORDER_ACTIVITY.SEQUENCE_%TYPE,
        OTBORDERACTIVITIES      OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBACTIVITY_ID
    );

    





















    PROCEDURE GETPENDACTBYGROUP
    (
        INUACTIVITYGROUPID      IN  OR_ORDER_ACTIVITY.ACTIVITY_GROUP_ID%TYPE,
        INUSEQUENC_             IN  OR_ORDER_ACTIVITY.SEQUENCE_%TYPE,
        OTBPENDACTBYGROUP       OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBACTIVITY_ID
    );
    


















    FUNCTION FNUGETMINSEQBYGROUP
    (
        INUACTIVITYGROUPID   IN  OR_ORDER_ACTIVITY.ACTIVITY_GROUP_ID%TYPE,
        ISBACTIVITYSTATUS    IN  OR_ORDER_ACTIVITY.STATUS%TYPE
    ) RETURN OR_ORDER_ACTIVITY.SEQUENCE_%TYPE;


    































    PROCEDURE GETELEMSBYACTIVITY
    (
        INUACTIVITYID           IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        ISBACTION               IN  VARCHAR2,
        OTBELEMSBYACTIVITY      OUT NOCOPY TYTBACTIVITYITEMS
    );

    


























    PROCEDURE GETELEMSBYELEMTYPEACT
    (
        INUACTIVITYID           IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        ISBACTION               IN  VARCHAR2,
        INUELEMENTTYPEID        IN  IF_ELEMENT_TYPE.ELEMENT_TYPE_ID%TYPE,
        OTBELEMSBYACTIVITY      OUT NOCOPY TYTBACTIVITYITEMS
    );


    
























    FUNCTION FNUGETTASKTYPEBYACTID
    (
        INUACTIVITYID   IN  GE_ITEMS.ITEMS_ID%TYPE
    ) RETURN OR_TASK_TYPES_ITEMS.TASK_TYPE_ID%TYPE;



    


















   
	

    


















    FUNCTION FNUGETCOUNTORDERACTIVITIES
    (
        INUORDERID   IN  OR_ORDER_ACTIVITY.ORDER_ID%TYPE,
        INUPACKAGEID IN  OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE DEFAULT NULL
    ) RETURN NUMBER;
    


















   
	

    



    PROCEDURE GETACTIVPENDBYPACK
    (
        INUPACKAGEID           IN  OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
        OTBORDERID             OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBORDER_ID
    );
    
    





    PROCEDURE GETORDERIDBYMOTIVEANDADDRESS
    (
        INUMOTIVEID    IN OR_ORDER_ACTIVITY.MOTIVE_ID%TYPE,
        INUADDRESSID   IN OR_ORDER_ACTIVITY.ADDRESS_ID%TYPE,
        INUTASKTYPEID  IN OR_ORDER_ACTIVITY.TASK_TYPE_ID%TYPE,
        INUACTIVITYID  IN GE_ITEMS.ITEMS_ID%TYPE,
        ONUORDERID     OUT OR_ORDER.ORDER_ID%TYPE
    );

    















    FUNCTION FNUGETPRODUCTIDBYORDER
    (
        INUORDERID      IN  OR_ORDER.ORDER_ID%TYPE
    ) RETURN OR_ORDER_ACTIVITY.PRODUCT_ID%TYPE;
    
    
    














    FUNCTION FNUGETORIGINORDERACTIVITYID
    (
        INUORDERACTIVITYID  IN OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE
    ) RETURN OR_ORDER_ACTIVITY.ORIGIN_ACTIVITY_ID%TYPE;
    
    
















    PROCEDURE GETPENDIORDERBYINSTANCE
    (
        INUINSTANCEID        IN  OR_ORDER_ACTIVITY.INSTANCE_ID%TYPE,
        OTBORDERID           OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBORDER_ID
    );
    
    












   
	
    














   
	
    
    





    PROCEDURE UPDSTATUSACTIVITYBYORDER
    (
        INUORDERID  IN  OR_ORDER.ORDER_ID%TYPE,
        ISBSTATUS   IN  OR_ORDER_ACTIVITY.STATUS%TYPE
    );
    
    













    FUNCTION FRCORDERACTIVBYORDERITEM
    (
        INUORDER_ITEMS_ID IN OR_ORDER_ITEMS.ORDER_ITEMS_ID%TYPE
    )
    RETURN DAOR_ORDER_ACTIVITY.STYOR_ORDER_ACTIVITY;
    
    
    















   
	
    
    


















    PROCEDURE GETPENDACTIVBYPACKWITHOUTWF

    (
        INUPACKAGEID         IN   OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
        OTBORDERACTIVITY     OUT  NOCOPY DAOR_ORDER_ACTIVITY.TYTBOR_ORDER_ACTIVITY,
        ISBTAGNAME       IN  OR_ORDER_ACTIVITY.WF_TAG_NAME%TYPE DEFAULT NULL
    );

    
















    PROCEDURE GETACTIVITIESBYINSTANCE
    (
        INUINSTANCE_ID  IN OR_ORDER_ACTIVITY.INSTANCE_ID%TYPE,
        OTBACTIVITIES   OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBOR_ORDER_ACTIVITY
    );
    
    













   
	

    
















    PROCEDURE GETACTBASICDATABYORDER  (
                                        INUORDERID               IN OR_ORDER.ORDER_ID%TYPE,
                                        OTBDATAORDERACTIVITIES  OUT NOCOPY TBDATAACTIVITIES
                                      );
                                      
    

















   
	

    

















    PROCEDURE GETSUBSDATABYORDER (
                                    INUORDERID           IN OR_ORDER.ORDER_ID%TYPE,
                                    ONUSUBSCRIBERID     OUT GE_SUBSCRIBER.SUBSCRIBER_ID%TYPE,
                                    ONUADDRESSID        OUT AB_ADDRESS.ADDRESS_ID%TYPE
                                  );
                                  
    


















    FUNCTION FNUGETACTSTANDARDTIME
    (
        INUORDERID IN OR_ORDER.ORDER_ID%TYPE
    )
    RETURN GE_ITEMS.STANDARD_TIME%TYPE;

    
    

















   
	

    





   
	

    













   
	
    
    















    PROCEDURE GETPENDACTIVBYMOTWITHOUTWF
    (
        INUMOTIVEID         IN  OR_ORDER_ACTIVITY.MOTIVE_ID%TYPE,
        OTBORDERACTIVITY    OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBOR_ORDER_ACTIVITY,
        ISBTAGNAME       IN  OR_ORDER_ACTIVITY.WF_TAG_NAME%TYPE DEFAULT NULL
    );
    
    













   FUNCTION FNUGETPACKIDINFIRSTACT(
                                    INUORDERID IN OR_ORDER.ORDER_ID%TYPE
                                  )
   RETURN OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE;

    















    PROCEDURE UPDLEGALITEMAMOUNT
    (
        INUORDER_ID          IN OR_ORDER_ITEMS.ORDER_ACTIVITY_ID%TYPE,
        INULEGAL_ITEM_AMOUNT IN OR_ORDER_ITEMS.LEGAL_ITEM_AMOUNT%TYPE DEFAULT 1
    );

    
    
    
    PROCEDURE UPDOPERATINGUNITSECTOR
    (
        IRCORDER       IN DAOR_ORDER.STYOR_ORDER
    );
    
    
    














    PROCEDURE GETACTBYCOMPONENT
    (
        INUCOMPONENTID  IN  MO_COMPONENT.COMPONENT_ID%TYPE,
        OTBACTIVITIES   OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBORDER_ACTIVITY_ID
    );
    
    






    FUNCTION FBLORDERHASINSTALLACTS
    (
         INUORDERID IN OR_ORDER.ORDER_ID%TYPE
    )
    RETURN BOOLEAN;
    
    






   PROCEDURE GETORDERIDGROUPBYPRODUCT
    (
        INUPRODUCTID   IN OR_ORDER_ACTIVITY.PRODUCT_ID%TYPE,
        INUTASKTYPEID  IN OR_ORDER_ACTIVITY.TASK_TYPE_ID%TYPE,
        INUACTIVITYID  IN GE_ITEMS.ITEMS_ID%TYPE,
        ONUORDERID     OUT OR_ORDER.ORDER_ID%TYPE
    );
    
    













   FUNCTION FNUGETPRODIDINFIRSTACT(
                                    INUORDERID IN OR_ORDER.ORDER_ID%TYPE
                                  )
   RETURN OR_ORDER_ACTIVITY.PRODUCT_ID%TYPE;
   
    













   FUNCTION FNUGETSUBSCIDINFIRSTACT(
                                    INUORDERID IN OR_ORDER.ORDER_ID%TYPE
                                   )
   RETURN OR_ORDER_ACTIVITY.SUBSCRIBER_ID%TYPE;
   
   

















    PROCEDURE GETACTIVITIESBYORDER
    (
        INUORDERID      IN OR_ORDER_ACTIVITY.ORDER_ID%TYPE,
        INUACTIVITYID   IN OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
        OTYTBACTIVITY   OUT NOCOPY UT_STRING.TYTB_STRING
    );

    





















    PROCEDURE GETITEMSBYACTIVITY
    (
        INUACTIVITYID           IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        ISBACTION               IN  VARCHAR2,
        OTBITEMSBYACTIVITY      OUT NOCOPY TYTBACTIVITYITEMS
    );
    

    PROCEDURE LINKUNBOUNDITEMS
    (
        INUORDERID          IN OR_ORDER_ACTIVITY.ORDER_ID%TYPE,
        INUORDERACTIVITYID  IN OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE
    );
    
    
    













   
	
    
    
    














   
	
    
    
    






    PROCEDURE GETDAMORDERGROUPBYADDRESS
    (
        INUADDRESSID   IN OR_ORDER_ACTIVITY.ADDRESS_ID%TYPE,
        ISBGROUPASSIGN IN VARCHAR2,
        INUACTIVITYID  IN GE_ITEMS.ITEMS_ID%TYPE,
        ONUORDERID    OUT OR_ORDER.ORDER_ID%TYPE
    );
    
    


















    FUNCTION FNUOBTDIRECCIONBYORDER
    (
        INUORDERID          IN  OR_ORDER.ORDER_ID%TYPE

    ) RETURN NUMBER;

    















   
	


    















    FUNCTION FBLESDAMORDENREPARA
    (
        INUORDER_ID  IN OR_ORDER.ORDER_ID%TYPE,
        INUDAMAGE_ID IN MO_PACKAGES.PACKAGE_ID%TYPE
    )
    RETURN BOOLEAN;


    















    FUNCTION FBLESDAMORDENDIAG
    (
        INUORDER_ID  IN OR_ORDER.ORDER_ID%TYPE,
        INUDAMAGE_ID IN MO_PACKAGES.PACKAGE_ID%TYPE
    )
    RETURN BOOLEAN;


    














   
	
    
    
    
    
    PROCEDURE ACTIVIANULADASORDEN
    (
        INUORDERID              IN  OR_ORDER.ORDER_ID%TYPE,
        OTBACTIVIDADESANULADAS  OUT NOCOPY TYTBORDERACTIVITIES
    );

    















   
	

    FUNCTION FRFGETDATASUBSCRIBER
    (
        INUSUBSCRIBERID  IN GE_SUBSCRIBER.SUBSCRIBER_ID%TYPE,
        INUADDRESSID     IN AB_ADDRESS.ADDRESS_ID%TYPE
    ) RETURN CONSTANTS.TYREFCURSOR;


    
    
    
    PROCEDURE GETPRODINFOBYACT
    (
        INUORDERACTIVITYID  IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        ONUADDRESSID        OUT OR_ORDER_ACTIVITY.ADDRESS_ID%TYPE,
        ONUSUBSCRIBERID     OUT OR_ORDER_ACTIVITY.SUBSCRIBER_ID%TYPE,
        ONUCOMPPRODID       OUT OR_ORDER_ACTIVITY.COMPONENT_ID%TYPE,
        ONUCOMPONENTTYPEID  OUT PR_COMPONENT.COMPONENT_TYPE_ID%TYPE,
        ONUCLASSSERVICEID   OUT PR_COMPONENT.CLASS_SERVICE_ID%TYPE,
        ONUPRODUCTID        OUT OR_ORDER_ACTIVITY.PRODUCT_ID%TYPE,
        ONUPRODUCTTYPEID    OUT PR_PRODUCT.PRODUCT_TYPE_ID%TYPE
    );
    
    FUNCTION FSBISADMINORDER
    (
        INUORDERID          IN  OR_ORDER.ORDER_ID%TYPE
    )
    RETURN VARCHAR2;
    
    
    
    
    PROCEDURE GETPENDORDACTBYPACK
    (
        INUPACKAGEID         IN    OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
        OTBORDERACTIVITIES   OUT   NOCOPY TYTBORDERANDACTIVITY
    );

    
    
    
    PROCEDURE GETPENDORDACTBYMOT
    (
        INUMOTIVEID          IN    OR_ORDER_ACTIVITY.MOTIVE_ID%TYPE,
        OTBORDERACTIVITIES   OUT   NOCOPY TYTBORDERANDACTIVITY
    );

    
    
    
    PROCEDURE GETPENDORDACTBYCOMP
    (
        INUCOMPONENTID         IN    OR_ORDER_ACTIVITY.COMPONENT_ID%TYPE,
        OTBORDERACTIVITIES     OUT   NOCOPY TYTBORDERANDACTIVITY
    );

     

















    PROCEDURE GETITEMSBYACTIVITY
    (
        INUACTIVITYID           IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        ISBACTION               IN  VARCHAR2,
        INUELEMENT_ID           IN  OR_ORDER_ITEMS.ELEMENT_ID%TYPE ,
        OTBITEMSBYACTIVITY      OUT NOCOPY TYTBACTIVITYITEMS
    );

    





    PROCEDURE DELETEACTIVITY
    (
        IDITEMSID   IN  GE_ITEMS.ITEMS_ID%TYPE
    );
    

    PROCEDURE GETREGORDERSBYPACK
    (
        INUPACKAGEID    IN  MO_PACKAGES.PACKAGE_ID%TYPE,
        ORFREFCURSOR    OUT CONSTANTS.TYREFCURSOR
    );
    
    PROCEDURE GETCOMPNSERVNUMBYACT
    (
        INUORDERACT     IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        ONUCOMPONENTID  OUT NOCOPY OR_ORDER_ACTIVITY.COMPONENT_ID%TYPE,
        ONUSERVICENUM   OUT NOCOPY PR_COMPONENT.SERVICE_NUMBER%TYPE
    );

    



























    PROCEDURE GETPRODINFOBYACTPR
    (
        INUORDERACTIVITYID  IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        INUPRCOMPONENTID    IN  PR_COMPONENT.COMPONENT_ID%TYPE,
        ONUADDRESSID        OUT OR_ORDER_ACTIVITY.ADDRESS_ID%TYPE,
        ONUSUBSCRIBERID     OUT OR_ORDER_ACTIVITY.SUBSCRIBER_ID%TYPE,
        ONUCOMPPRODID       OUT OR_ORDER_ACTIVITY.COMPONENT_ID%TYPE,
        ONUCOMPONENTTYPEID  OUT PR_COMPONENT.COMPONENT_TYPE_ID%TYPE,
        ONUCLASSSERVICEID   OUT PR_COMPONENT.CLASS_SERVICE_ID%TYPE,
        ONUPRODUCTID        OUT OR_ORDER_ACTIVITY.PRODUCT_ID%TYPE,
        ONUPRODUCTTYPEID    OUT PR_PRODUCT.PRODUCT_TYPE_ID%TYPE
    );
    
    
    PROCEDURE GETORIGINACTIVITIES
    (
        INUORDERACTIVITYID  IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        OTBACTIVITIES       OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBOR_ORDER_ACTIVITY
    );
    
    FUNCTION FBLEXISTRELATEDACTIVITIES
    (
        INUORDERACTIVITYID  IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        INUEXCORACTIVITYID  IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE DEFAULT NULL
    ) RETURN BOOLEAN;

    






    PROCEDURE GETORDERBYBASEADDRESS
    (
        INUADDRESSID   IN OR_ORDER_ACTIVITY.ADDRESS_ID%TYPE,
        INUTASKTYPEID  IN OR_ORDER_ACTIVITY.TASK_TYPE_ID%TYPE,
        INUSTAGEID     IN OR_ORDER.STAGE_ID%TYPE,
        ONUORDERID     OUT OR_ORDER.ORDER_ID%TYPE
    );

    




    PROCEDURE GETPENDACTIVBYPACK
    (
        INUPACKAGEID        IN   OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
        OTBORDERACT         OUT  NOCOPY DAOR_ORDER_ACTIVITY.TYTBOR_ORDER_ACTIVITY
    );

     PROCEDURE GETALLACTBYCOMPONENT
    (
        INUCOMPONENTID  IN  MO_COMPONENT.COMPONENT_ID%TYPE,
        OTBACTIVITIES   OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBORDER_ACTIVITY_ID
    );
    
    






    FUNCTION FBLHASPENDINGACTIVITIES
    (
        INUINSTANCEID   IN  OR_ORDER_ACTIVITY.INSTANCE_ID%TYPE
    )
    RETURN BOOLEAN;
    
    




   FUNCTION FNUGETINSTANCEBYORDER
   (
        INUORDERID IN OR_ORDER.ORDER_ID%TYPE
   )
   RETURN NUMBER;
   
   PROCEDURE GETPRODDATEROUTEORDER (
                                        INUPRODUCTID    IN PR_PRODUCT.PRODUCT_ID%TYPE,
                                        INUROUTEID      IN OR_ROUTE.ROUTE_ID%TYPE,
                                        IDTEXCDATE      IN OR_ORDER_ACTIVITY.EXEC_ESTIMATE_DATE%TYPE,
                                        INUTASKTYPEID   IN OR_ORDER_ACTIVITY.TASK_TYPE_ID%TYPE,
                                        ONUORDERID     OUT OR_ORDER.ORDER_ID%TYPE
                                   );

    

















   
	
    
    




    FUNCTION FRFGETREGISORDERBYPACK
    (
        INUPACKAGEID    IN  MO_PACKAGES.PACKAGE_ID%TYPE,
        INUACTIVITYID   IN  GE_ITEMS.ITEMS_ID%TYPE
    ) RETURN CONSTANTS.TYREFCURSOR;
    
    





    PROCEDURE GETACTIVITYGROUPBYPACKAGE
    (
        INUPACKAGEID   IN  OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
        OTBPLANNEDGROUP OUT NOCOPY  UT_STRING.TYTB_STRING
    );
    
    



    PROCEDURE GETACTSUPPORTINFO
    (
        INUACTIVITYID       IN  OR_ACTIVIDAD.ID_ACTIVIDAD%TYPE,
        OSBMULTILEGAL       OUT NOCOPY OR_ACTIVIDAD.LEGALIZA_MULTIPLE%TYPE,
        ONULEGALITEMAMOUNT  OUT NOCOPY OR_ACTIVIDAD.CANTIDAD_DEFECTO%TYPE
    );

    




    FUNCTION FRFGETIDORDERSBYPACK
    (
        INUPACKAGEID    IN  MO_PACKAGES.PACKAGE_ID%TYPE
    ) RETURN CONSTANTS.TYREFCURSOR;
    
    



    PROCEDURE GETBASICDATABYORDER
    (
        INUORDERID          IN  OR_ORDER.ORDER_ID%TYPE,
        ORFORDER            OUT CONSTANTS.TYREFCURSOR,
        ORFORDERACTIVITY    OUT CONSTANTS.TYREFCURSOR,
        ORFORDERCOMMENTS    OUT CONSTANTS.TYREFCURSOR
    );

    




   
    PROCEDURE UPDACTOFORDERTOCLOSE
    (
        INUORDERID          IN  OR_ORDER.ORDER_ID%TYPE,
        ISBORDERACTSTATUS   IN  OR_ORDER_ACTIVITY.STATUS%TYPE,
        IDTEXECESTIMATEDATE IN  OR_ORDER_ACTIVITY.EXEC_ESTIMATE_DATE%TYPE
    );

    



    FUNCTION FNUGETFIRSTORDERACT
    (
        INUORDERID IN OR_ORDER.ORDER_ID%TYPE
    )
    RETURN OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE;

    



    PROCEDURE GETACTPENDBYPACKLOCK
    (
        INUPACKAGEID IN         OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
        IBLLOCKED    IN         BOOLEAN,
        OTBORDERID   OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBORDER_ID
    );
    
    



    FUNCTION FRFGETORDERSBYPACKAGE
    (
        INUPACKAGEID    IN  MO_PACKAGES.PACKAGE_ID%TYPE,
        ITBTASKS        IN  GE_TYTBNUMBER  DEFAULT NULL
    )
    RETURN PKCONSTANTE.TYREFCURSOR;


    



    FUNCTION FRFGETORDERACTIVITIES
    (
        INUORDERID              IN  OR_ORDER.ORDER_ID%TYPE
    )
    RETURN CONSTANTS.TYREFCURSOR;
    
    





    PROCEDURE GETPENDORDACTBYSERIALITEM
    (
        INUSERIALITEMID         IN OR_ORDER_ACTIVITY.SERIAL_ITEMS_ID%TYPE,
        OTBORDERACTIVITIES     OUT NOCOPY OR_BCORDERACTIVITIES.TYTBORDERANDACTIVITY,
        INUDISCARDACTSTATUS     IN OR_ORDER_ACTIVITY.STATUS%TYPE,
        INUPACKAGEID            IN OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE DEFAULT NULL
    );

    




    PROCEDURE GETORDERACTIVITYATTRI
    (
        INUORDERID      IN  OR_ORDER_ACTIVITY.ORDER_ID%TYPE,
        INUITEMID       IN  OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
        OSBVALUE1       OUT NOCOPY OR_ORDER_ACTIVITY.VALUE1%TYPE,
        OSBVALUE2       OUT NOCOPY OR_ORDER_ACTIVITY.VALUE2%TYPE,
        OSBVALUE3       OUT NOCOPY OR_ORDER_ACTIVITY.VALUE3%TYPE,
        OSBVALUE4       OUT NOCOPY OR_ORDER_ACTIVITY.VALUE4%TYPE
    );
    
    





   
	
    
    






    FUNCTION FBOHASACTIVBYPACK
    (
        INUPACKAGEID        IN   OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE
    )
    RETURN BOOLEAN;
    
    









    
    PROCEDURE GETROUTEORDER
    (
        INUROUTEID      IN OR_ROUTE.ROUTE_ID%TYPE,
        INUTASKTYPEID   IN OR_ORDER.TASK_TYPE_ID%TYPE,
        INUSTAGEID      IN  OR_ORDER.STAGE_ID%TYPE,
        ONUORDERID     OUT OR_ORDER.ORDER_ID%TYPE
     );

    





   
	
    
    








    PROCEDURE GETSUSBACTIBYREFVALUE
    (
        INUSUBSCRIPTIONID   IN  OR_ORDER_ACTIVITY.SUBSCRIPTION_ID%TYPE,
        INUREFERENCEVALUE   IN  OR_ORDER_ACTIVITY.VALUE_REFERENCE%TYPE,
        INUACTIVITYID       IN  OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
        OTBACTIVITY         OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBOR_ORDER_ACTIVITY
    );

    





   
	

    



    FUNCTION FNUCOUNTPENDACTBYWF(
        INUINSTANCEID  IN OR_ORDER_ACTIVITY.INSTANCE_ID%TYPE
    ) RETURN NUMBER;
    
    







    FUNCTION FNUGETMAINACTIVITY
    (
        INUORDERID           IN   OR_ORDER_ACTIVITY.ORDER_ID%TYPE
    )
    RETURN OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE;


    




    PROCEDURE GETPENDACTBYORDER
    (
        INUORDERID    IN  OR_ORDER_ACTIVITY.ORDER_ID%TYPE,
        OTBACTIVITIES OUT NOCOPY DAOR_ORDER_ACTIVITY.TYTBOR_ORDER_ACTIVITY
    );
    
    





    PROCEDURE UPDORDACTVALUEANDCOMMENT
    (
        INUORDERACTIVITY    IN OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        ISBVALUE1           IN OR_ORDER_ACTIVITY.VALUE1%TYPE,
        ISBCOMMENT_         IN OR_ORDER_ACTIVITY.COMMENT_%TYPE
    );
    
    





   
	
    
    



    FUNCTION FRFGETMAXDEMAND
    (
        INUORDERID      IN  OR_ORDER.ORDER_ID%TYPE
    )
    RETURN CONSTANTS.TYREFCURSOR;
    
    






    FUNCTION FNUMAXDEMORDBYSESU
    (
        INUSESUID      IN  LECTELME.LEEMSESU%TYPE,
        INUPECSID      IN  PERICOSE.PECSCONS%TYPE
    )
   RETURN OR_ORDER.ORDER_ID%TYPE;
   
    






    FUNCTION FNUMAXDEMORDBYLECT
    (
        INULECTELMEID       IN  LECTELME.LEEMCONS%TYPE
    )
   RETURN OR_ORDER.ORDER_ID%TYPE;
   
    






    PROCEDURE GETORDBYPACK
    (
        INUPACKAGEID         IN         OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
        OTBORDERACTIVITIES   OUT NOCOPY TYTBORDERANDACTIVITY
    );
    
    








    FUNCTION FNUGETGE_REQCOMP_ATRIB
    (
        INUORDERID           IN   OR_ORDER_ACTIVITY.ORDER_ID%TYPE
    )
    RETURN GE_BOOPERATCOMPANY.TYRCGE_REQCOMP_ATRIB;
    
    PROCEDURE UPDACTINSTANCEID
    (
        INUACTIVITYGROUP    IN  OR_ORDER_ACTIVITY.ACTIVITY_GROUP_ID%TYPE,
        INUINSTANCE         IN  OR_ORDER_ACTIVITY.INSTANCE_ID%TYPE
    );

    FUNCTION FBOLOCKPACKPLANACTIV
    (
        INUPACKAGE  IN  MO_PACKAGES.PACKAGE_ID%TYPE
    )
    RETURN BOOLEAN;
    
     






    PROCEDURE GETORDACTBYORDANDACT
    (
        INUORDERID      IN OR_ORDER_ACTIVITY.ORDER_ID%TYPE,
        ISBACTIVITYIDS  IN VARCHAR2,
        OTYTBACTIVITY   OUT NOCOPY UT_STRING.TYTB_STRING
    );
    
     




   
	
    
    





    PROCEDURE GETCONFATTRADDIBYACTCAU
    (
        INUACTIVITYID    IN         OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
        INUCLASSCAUSAL   IN         GE_CLASS_CAUSAL.CLASS_CAUSAL_ID%TYPE,
        OTBATTRIBADITACT OUT NOCOPY OR_BCORDERACTIVITIES.TYTBATTRIBADIT
    );
    
    




    FUNCTION FTBCONFATTRADDIBYACTCAU
    (
        INUACTIVITYID   IN  OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
        INUCLASSCAUSAL  IN  GE_CLASS_CAUSAL.CLASS_CAUSAL_ID%TYPE
    )
    RETURN OR_BCORDERACTIVITIES.TYTBATTRIBADITRF PIPELINED;

    






    FUNCTION FRFCONFATTRADDIBYACTCAU
    (
        INUACTIVITYID   IN  OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
        INUCLASSCAUSAL  IN  GE_CLASS_CAUSAL.CLASS_CAUSAL_ID%TYPE
    )
    RETURN CONSTANTS.TYREFCURSOR;
    
    






    FUNCTION FSBHASCONFADDATTR
    (
        INUACTIVITYID   IN  OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
        INUCLASSCAUSAL  IN  GE_CLASS_CAUSAL.CLASS_CAUSAL_ID%TYPE
    )
    RETURN VARCHAR2;
    
    






    FUNCTION FNUGETCLIENTBYACT
    (
        INUORDERACTIVITY   IN OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE
    )
    RETURN GE_SUBSCRIBER.SUBSCRIBER_ID%TYPE;
    
    






    FUNCTION FSBGETEQUIPBYACT
    (
        INUORDERACTIVITY  IN OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE
    )
    RETURN GE_ITEMS_SERIADO.SERIE%TYPE;
    
    






    FUNCTION FTBGETCAPACITYBYACT
    (
        INUACTIVITY IN OR_ACTIVIDAD.ID_ACTIVIDAD%TYPE
    )
    RETURN TYTBCAPABYPRODTYPE;

    






    FUNCTION FSBGETSERIEBYCOMP
    (
        INUCOMPONENTID  IN  PR_COMPONENT.COMPONENT_ID%TYPE
    )
    RETURN PR_SERIAL_ITEM.SERIAL%TYPE;

    






    PROCEDURE GETPRODTYPEBYCOMP
    (
        INUCOMPONENTID  IN  PR_COMPONENT.COMPONENT_ID%TYPE,
        ONUPRODTYPEID   OUT SERVICIO.SERVCODI%TYPE,
        ONUPRODTYPEDESC OUT SERVICIO.SERVDESC%TYPE
    );

    






    PROCEDURE GETEQUIPMENTCAPACITY
    (
        ISBSERIE         IN  GE_ITEMS_SERIADO.SERIE%TYPE,
        INUCOMPONENTID   IN  PR_COMPONENT.COMPONENT_ID%TYPE,
        ONUCAPACITYID    OUT GE_ITEM_SERIADO_CAP.ITEM_SERIADO_CAP_ID%TYPE,
        ONUTOTALCAPACITY OUT GE_ITEM_SERIADO_CAP.CAPACITY_TOTAL%TYPE,
        ONUOCCUPIEDCAPA  OUT GE_ITEM_SERIADO_CAP.CAPACITY_OCCUPIED%TYPE
    );

    






    FUNCTION FTBGETPRTYPESUMBYACT
    (
        INUACTIVITY IN OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE
    )
    RETURN TYTBCAPABYPRODTYPE;
    
    





    FUNCTION FTBACTIVITRETSER
    (
        INUCOMPONENTID      IN  MO_COMPONENT.COMPONENT_ID%TYPE
    )
    RETURN DAOR_ORDER_ACTIVITY.TYTBOR_ORDER_ACTIVITY;
    
    













    PROCEDURE GETACTIVITIESBYPACKAGE
    (
        INUPACKAGEID         IN   OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
        OTBACTIVITY          OUT  NOCOPY TYTBORDERANDACTIVITY
    );
    
    





    FUNCTION FRFGETACTITEMORDER
    (
        INUORDERID              IN  OR_ORDER.ORDER_ID%TYPE
    )
    RETURN CONSTANTS.TYREFCURSOR;

    






    PROCEDURE GETORDPENDBYPACK
    (
          INUPACKAGEID  IN          OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE
        , OTBORDERS     OUT NOCOPY  DAOR_ORDER.TYTBORDER_ID
    );
    
    
    






    PROCEDURE ORDERIDBYMPLANANDSECT
    (
        INUMAINTREFERENCE       IN  IF_MAINTENANCE.ENTITY_ID%TYPE,
        INUMAINTCONFIGURATION   IN  IF_MAINTENANCE.MAINTENANCE_CONF_ID%TYPE,
        INUSECTORID             IN  OR_ORDER.OPERATING_SECTOR_ID%TYPE,
        ONUORDERID              OUT OR_ORDER.ORDER_ID%TYPE
    );

    






    PROCEDURE ORDERIDBYMAINTPROJECT
    (
        INUMAINTREFERENCE       IN  IF_MAINTENANCE.ENTITY_ID%TYPE,
        INUMAINTCONFIGURATION   IN  IF_MAINTENANCE.MAINTENANCE_CONF_ID%TYPE,
        INUSECTORID             IN  OR_ORDER.OPERATING_SECTOR_ID%TYPE,
        INUSTAGEID              IN  OR_ORDER.STAGE_ID%TYPE,
        ONUORDERID              OUT OR_ORDER.ORDER_ID%TYPE
    );
    
    






    FUNCTION FSBISORDERINFINSTAT
    (
        INUPRODUCTID   IN  OR_ORDER_ACTIVITY.PRODUCT_ID%TYPE,
        INUACTIVITYID  IN  OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE

    ) RETURN UT_DATATYPES.STYYESORNO;
    
    




    FUNCTION FSBVALACTIVITYFORUSER
    (
        INUACTIVITYID         IN  OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
        INUPERSONID           IN  GE_PERSON.PERSON_ID%TYPE,
        INUUNIDPERAREA        IN  OR_OPER_UNIT_CLASSIF.OPER_UNIT_CLASSIF_ID%TYPE,
        INUSPECIALPROFICIENCY IN  OR_PROFICIENCY.PROFICIENCY_ID%TYPE
    )RETURN UT_DATATYPES.STYYESORNO;
    
    





    FUNCTION FSBEXISTACTBYPACKAGE
    (
        INUPACKAGEID   IN  OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
        INUACTIVITYID  IN  OR_ORDER_ACTIVITY.ACTIVITY_ID%TYPE,
        INUINSTANCEID  IN  WF_INSTANCE.INSTANCE_ID%TYPE
    )
    RETURN UT_DATATYPES.STYYESORNO;
    
    





    FUNCTION FRFINFACCFORORDPRINT
    (
        INUORDERACTIVITY  IN OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE
    ) RETURN CONSTANTS.TYREFCURSOR;
    
    





    FUNCTION FNUGETACTIVITYFORANULL
    (
        INUPACKAGE   IN OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE,
        INUGAMA      IN GE_ITEMS_GAMA.ID_ITEMS_GAMA%TYPE,
        INUCOMPONENT IN OR_ORDER_ACTIVITY.COMPONENT_ID%TYPE
    )
    RETURN OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE;

    





    PROCEDURE GETORDERBYADDRANDCUST
    (
        INUADDRESSID    IN  OR_ORDER_ACTIVITY.ADDRESS_ID%TYPE,
        INUSUBSCRIBERID IN  OR_ORDER_ACTIVITY.SUBSCRIBER_ID%TYPE,
        INUTASKTYPEID   IN  OR_ORDER_ACTIVITY.TASK_TYPE_ID%TYPE,
        INUSTAGEID      IN  OR_ORDER.STAGE_ID%TYPE,
        ONUORDERID      OUT OR_ORDER.ORDER_ID%TYPE
    );

    





    PROCEDURE GETACTIVORDBYINSTANCE
    (
        INUINSTANCEID   IN  OR_ORDER_ACTIVITY.INSTANCE_ID%TYPE,
        OTBACTIVITIES   OUT NOCOPY TYTBACTORDBYINST
    );
    
    




    PROCEDURE GETORDERACTSUPPORT
    (
        INUORDERACTIVITYID IN  OR_ORDER_ACTIVITY.ORDER_ACTIVITY_ID%TYPE,
        OTBORDERACTSUPPORT OUT NOCOPY TYTBORDACTITEM
    );
    
    




    PROCEDURE GETBASICDATAORDER
    (
        INUORDERID          IN  OR_ORDER.ORDER_ID%TYPE,
        ORCORDER            OUT NOCOPY TYRCBASICORDER,
        OTBORDERACTIVITY    OUT NOCOPY TYTBBASICORDERACT,
        OTBORDERCOMMENTS    OUT NOCOPY TYTBBASICORDERCOM
    );
    
    




    PROCEDURE UPDORDERDATA
    (
        INUORDERID      IN      OR_ORDER.ORDER_ID%TYPE,
        IDTEXECDATE     IN      OR_ORDER.EXEC_ESTIMATE_DATE%TYPE,
        INUREFVALUE     IN      OR_ORDER_ACTIVITY.VALUE_REFERENCE%TYPE
    );
    
END OR_BCORDERACTIVITIES;