CREATE OR REPLACE PACKAGE BODY OR_BOITEMS IS
   CSBVERSION CONSTANT VARCHAR2( 20 ) := 'SAO232863';
   CSBCOSTLIST CONSTANT VARCHAR2( 1 ) := 'L';
   CSBAVERCOST CONSTANT VARCHAR2( 1 ) := 'C';
   CNUN_EXIST_ORD_SET_ITEMS CONSTANT NUMBER := 391;
   CNUN_EXIST_ORD_LEG_ITEMS CONSTANT NUMBER := 425;
   CNUN_EXIST_ORD_COMP_ITEMS CONSTANT NUMBER := 379;
   CNU_LOAD_FIRST_GET_ITEMS CONSTANT NUMBER := 381;
   CNUSECT_OPER_NULL CONSTANT NUMBER := 386;
   CNUITEM_TO_LEGALIZ_NE CONSTANT NUMBER := 407;
   CNUNULLORDER CONSTANT OR_ORDER.ORDER_ID%TYPE := -1;
   CNUITEM_N_ENOUGH CONSTANT NUMBER := 1274;
   CNUBALANCE_TROUBLE CONSTANT NUMBER := 1814;
   CNUNOHACARGADOITEMS CONSTANT NUMBER := 2262;
   CNUERR249 CONSTANT NUMBER( 3 ) := 249;
   CNUERR251 CONSTANT NUMBER( 3 ) := 251;
   CNUERR_111120 CONSTANT NUMBER( 6 ) := 111120;
   CNUERR_116640 CONSTANT NUMBER( 6 ) := 116640;
   GNUITEMMOVECAUS NUMBER := GE_BOPARAMETER.FNUGET( OR_BOCONSTANTS.CSBUNKNOWNMOVECAUSE );
   TYPE TYTBITEMSDOCUMENTO IS TABLE OF GE_ITEMS_DOCUMENTO.ID_ITEMS_DOCUMENTO%TYPE INDEX BY VARCHAR2( 15 );
   GTBITEMSDOCUMENT TYTBITEMSDOCUMENTO;
   NUSESSIONID NUMBER := NULL;
   BLCOMPUTEITEMS BOOLEAN := FALSE;
   FUNCTION FNUGETLASTVALUE( INUITEM IN OR_UNI_ITEM_BALA_MOV.ID_ITEMS_SERIADO%TYPE )
    RETURN OR_UNI_ITEM_BALA_MOV.TOTAL_VALUE%TYPE
    IS
      NUVALOR OR_UNI_ITEM_BALA_MOV.TOTAL_VALUE%TYPE;
      CURSOR CUVALUES IS
SELECT total_value
            FROM or_uni_item_bala_mov
            WHERE movement_type = 'D'
            AND ID_ITEMS_SERIADO = inuItem
            ORDER BY move_date DESC;
    BEGIN
      IF CUVALUES%ISOPEN THEN
         CLOSE CUVALUES;
      END IF;
      OPEN CUVALUES;
      FETCH CUVALUES
         INTO NUVALOR;
      IF CUVALUES%NOTFOUND THEN
         NUVALOR := NULL;
      END IF;
      CLOSE CUVALUES;
      RETURN NUVALOR;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   FUNCTION FNUGETSUGESTEDAMMOUNT( INUMAX IN NUMBER, INUMIN IN NUMBER, INUINVENTARIO IN NUMBER, INUTRANSITO IN NUMBER, INUPROMEDIO IN NUMBER )
    RETURN NUMBER
    IS
    BEGIN
      IF INUPROMEDIO >= 5 THEN
         RETURN INUMAX - ( ( INUINVENTARIO + INUTRANSITO ) - INUPROMEDIO * 3 );
       ELSE
         RETURN INUMIN - ( ( INUINVENTARIO + INUTRANSITO ) - INUPROMEDIO * 3 );
      END IF;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   FUNCTION FBLISEMPTYORDERITEMSTEMPTAB( INUORDER IN OR_ORDER.ORDER_ID%TYPE )
    RETURN BOOLEAN
    IS
      CURSOR CU_ORDERITEMTEMP( NUORDER IN OR_ORDER.ORDER_ID%TYPE ) IS
SELECT COUNT(1)
            FROM   Or_Temp_Order_Items
            WHERE  Order_Id = nuOrder
              AND  rownum = 1;
      NUCONTA NUMBER := 0;
    BEGIN
      OPEN CU_ORDERITEMTEMP( INUORDER );
      FETCH CU_ORDERITEMTEMP
         INTO NUCONTA;
      CLOSE CU_ORDERITEMTEMP;
      IF ( NUCONTA = 0 ) THEN
         RETURN ( TRUE );
      END IF;
      RETURN ( FALSE );
    EXCEPTION
      WHEN OTHERS THEN
         IF ( CU_ORDERITEMTEMP%ISOPEN ) THEN
            CLOSE CU_ORDERITEMTEMP;
         END IF;
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FBLISEMPTYORDERITEMSTEMPTAB;
   PROCEDURE FREEBALANCE( INUITEM IN OR_OPE_UNI_ITEM_BALA.ITEMS_ID%TYPE, INUOPEUNI IN OR_OPE_UNI_ITEM_BALA.OPERATING_UNIT_ID%TYPE, INUBALANCE IN OR_OPE_UNI_ITEM_BALA.BALANCE%TYPE )
    IS
    BEGIN
      UPDATE Or_Ope_Uni_Item_Bala
        SET    Balance = Balance + inuBalance
        WHERE  Items_Id = inuItem
          AND  Operating_Unit_Id = inuOpeUni;
    EXCEPTION
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FREEBALANCE;
   FUNCTION FNUGETDISPLAY_ORDER( INUTASKTYPE IN OR_ORDER.TASK_TYPE_ID%TYPE, INUITEMID IN GE_ITEMS.ITEMS_ID%TYPE )
    RETURN NUMBER
    IS
      NUDISPLAYORDER OR_TASK_TYPES_ITEMS.DISPLAY_ORDER%TYPE := 999999999;
    BEGIN
      IF DAOR_TASK_TYPES_ITEMS.FBLEXIST( INUTASKTYPE, INUITEMID ) THEN
         NUDISPLAYORDER := DAOR_TASK_TYPES_ITEMS.FNUGETDISPLAY_ORDER( INUTASKTYPE, INUITEMID );
      END IF;
      RETURN NUDISPLAYORDER;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FNUGETDISPLAY_ORDER;
   PROCEDURE GETITEMSORDERSAVE( INUORDERID IN OR_ORDER.ORDER_ID%TYPE, OTBITEMS OUT NOCOPY TYTBITEMS )
    IS
      NUINDEX BINARY_INTEGER := 0;
      CURSOR CUITEMSASSIGNED( INUORDERID IN OR_ORDER.ORDER_ID%TYPE, INUTASKTYPE IN OR_ORDER.TASK_TYPE_ID%TYPE ) IS
SELECT  a.Items_Id,
                    a.Assigned_Item_Amount,
                    a.Legal_Item_Amount,
                    a.Value ,
                    a.order_items_id ,
                    fnuGetdisplay_order (inuTaskType, a.Items_Id) display_order,
                    a.out_
            FROM    Or_Order_Items a,
                    Ge_Items b
            WHERE   a.order_id = inuOrderId
              AND   a.Items_Id = b.Items_Id
              --AND   b.item_classif_id <> or_boorderactivities.cnuActivityType
            ORDER BY display_order;
    BEGIN
      DAOR_ORDER.ACCKEY( INUORDERID );
      FOR RCITEMSASSIGNED IN CUITEMSASSIGNED( INUORDERID, DAOR_ORDER.FNUGETTASK_TYPE_ID( INUORDERID ) )
       LOOP
         NUINDEX := OTBITEMS.COUNT + 1;
         OTBITEMS( NUINDEX ).ITEMS_ID := RCITEMSASSIGNED.ITEMS_ID;
         OTBITEMS( NUINDEX ).ASSIGNED_ITEM_AMOUNT := RCITEMSASSIGNED.ASSIGNED_ITEM_AMOUNT;
         OTBITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT := RCITEMSASSIGNED.LEGAL_ITEM_AMOUNT;
         OTBITEMS( NUINDEX ).VALUE := RCITEMSASSIGNED.VALUE;
         OTBITEMS( NUINDEX ).ORDER_ITEMS_ID := RCITEMSASSIGNED.ORDER_ITEMS_ID;
         OTBITEMS( NUINDEX ).OUT_ := RCITEMSASSIGNED.OUT_;
      END LOOP;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END GETITEMSORDERSAVE;
   PROCEDURE GETITEMSORDER( INUORDERID IN OR_ORDER.ORDER_ID%TYPE, OTBITEMS OUT NOCOPY TYTBITEMS )
    IS
      NUINDEX BINARY_INTEGER := 0;
      CURSOR CUITEMSASSIGNED( INUORDERID IN OR_ORDER.ORDER_ID%TYPE, INUTASKTYPE IN OR_ORDER.TASK_TYPE_ID%TYPE ) IS
SELECT  a.Items_Id,
                    a.Assigned_Item_Amount,
                    a.Legal_Item_Amount,
                    a.Value ,
                    a.order_items_id,
                    DISPLAY_ORDER,
                    a.out_

            FROM    Or_Order_Items a,
                    Ge_Items b,
                    or_task_types_items c

            WHERE   a.order_id = inuOrderId
              AND   a.Items_Id = b.Items_Id
              AND   c.items_id = b.items_id
              AND   b.element_type_id IS NULL
              AND   c.is_legalize_visible = 'Y'
              AND   c.task_type_id = inuTaskType

            ORDER BY DISPLAY_ORDER;
    BEGIN
      DAOR_ORDER.ACCKEY( INUORDERID );
      FOR RCITEMSASSIGNED IN CUITEMSASSIGNED( INUORDERID, DAOR_ORDER.FNUGETTASK_TYPE_ID( INUORDERID ) )
       LOOP
         NUINDEX := OTBITEMS.COUNT + 1;
         OTBITEMS( NUINDEX ).ITEMS_ID := RCITEMSASSIGNED.ITEMS_ID;
         OTBITEMS( NUINDEX ).ASSIGNED_ITEM_AMOUNT := RCITEMSASSIGNED.ASSIGNED_ITEM_AMOUNT;
         OTBITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT := RCITEMSASSIGNED.LEGAL_ITEM_AMOUNT;
         OTBITEMS( NUINDEX ).VALUE := RCITEMSASSIGNED.VALUE;
         OTBITEMS( NUINDEX ).ORDER_ITEMS_ID := RCITEMSASSIGNED.ORDER_ITEMS_ID;
         OTBITEMS( NUINDEX ).OUT_ := RCITEMSASSIGNED.OUT_;
      END LOOP;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END GETITEMSORDER;
   PROCEDURE FILLORDERITEMSTEMPTABLESAVE( INUORDER IN OR_ORDER.ORDER_ID%TYPE, IBLRESETVALUES IN BOOLEAN := TRUE )
    IS
      TBITEMS TYTBITEMS;
      NUINDEX BINARY_INTEGER;
      RCTEMORDITE DAOR_TEMP_ORDER_ITEMS.STYOR_TEMP_ORDER_ITEMS;
      CNUOR_WITHOUT_ITEM CONSTANT NUMBER := 392;
      NUGETITEMCLASSIFID GE_ITEMS.ITEM_CLASSIF_ID%TYPE;
    BEGIN
      UT_TRACE.TRACE( 'INICIO or_boitems.FillOrderItemsTempTableSave', 12 );
      IF ( NOT FBLISEMPTYORDERITEMSTEMPTAB( INUORDER ) ) THEN
         RETURN;
      END IF;
      GETITEMSORDERSAVE( INUORDER, TBITEMS );
      IF ( TBITEMS.COUNT = 0 ) THEN
         RETURN;
      END IF;
      NUINDEX := TBITEMS.FIRST;
      LOOP
         RCTEMORDITE.TEMP_ORDER_ITEMS_ID := TBITEMS( NUINDEX ).ORDER_ITEMS_ID;
         RCTEMORDITE.ORDER_ID := INUORDER;
         RCTEMORDITE.ITEMS_ID := TBITEMS( NUINDEX ).ITEMS_ID;
         RCTEMORDITE.ASSIGNED_ITEM_AMOUNT := TBITEMS( NUINDEX ).ASSIGNED_ITEM_AMOUNT;
         RCTEMORDITE.OUT_ := TBITEMS( NUINDEX ).OUT_;
         NUGETITEMCLASSIFID := DAGE_ITEMS.FNUGETITEM_CLASSIF_ID( RCTEMORDITE.ITEMS_ID );
         IF ( DAGE_ITEM_CLASSIF.FSBGETQUANTITY_CONTROL( NUGETITEMCLASSIFID ) IN ( OR_BOCONSTANTS.CNUDECREASE, OR_BOCONSTANTS.CNUINCREASE ) ) THEN
            RCTEMORDITE.VALUE := 0;
            IF ( IBLRESETVALUES ) THEN
               RCTEMORDITE.LEGAL_ITEM_AMOUNT := NULL;
             ELSE
               IF ( NVL( TBITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT, 0 ) > 0 ) THEN
                  RCTEMORDITE.LEGAL_ITEM_AMOUNT := TBITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT;
                ELSE
                  RCTEMORDITE.LEGAL_ITEM_AMOUNT := TBITEMS( NUINDEX ).ASSIGNED_ITEM_AMOUNT;
               END IF;
            END IF;
          ELSE
            RCTEMORDITE.LEGAL_ITEM_AMOUNT := 0;
            RCTEMORDITE.VALUE := 0;
         END IF;
         DAOR_TEMP_ORDER_ITEMS.INSRECORD( RCTEMORDITE );
         EXIT WHEN ( NUINDEX = TBITEMS.LAST );
         NUINDEX := TBITEMS.NEXT( NUINDEX );
      END LOOP;
      UT_TRACE.TRACE( 'FIN or_boitems.FillOrderItemsTempTableSave', 12 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FILLORDERITEMSTEMPTABLESAVE;
   PROCEDURE FILLORDERITEMSTEMPTABLE( INUORDER IN OR_ORDER.ORDER_ID%TYPE, IBLRESETVALUES IN BOOLEAN := TRUE )
    IS
      TBITEMS TYTBITEMS;
      NUINDEX BINARY_INTEGER;
      RCTEMORDITE DAOR_TEMP_ORDER_ITEMS.STYOR_TEMP_ORDER_ITEMS;
      CNUOR_WITHOUT_ITEM CONSTANT NUMBER := 392;
      NUGETITEMCLASSIFID GE_ITEMS.ITEM_CLASSIF_ID%TYPE;
    BEGIN
      UT_TRACE.TRACE( 'INICIO OR_bo_items.FillOrderItemsTempTable. Orden:' || INUORDER, 3 );
      IF ( NOT FBLISEMPTYORDERITEMSTEMPTAB( INUORDER ) ) THEN
         RETURN;
      END IF;
      GETITEMSORDER( INUORDER, TBITEMS );
      IF ( TBITEMS.COUNT = 0 ) THEN
         RETURN;
      END IF;
      NUINDEX := TBITEMS.FIRST;
      LOOP
         RCTEMORDITE.TEMP_ORDER_ITEMS_ID := TBITEMS( NUINDEX ).ORDER_ITEMS_ID;
         RCTEMORDITE.ORDER_ID := INUORDER;
         RCTEMORDITE.ITEMS_ID := TBITEMS( NUINDEX ).ITEMS_ID;
         RCTEMORDITE.ASSIGNED_ITEM_AMOUNT := TBITEMS( NUINDEX ).ASSIGNED_ITEM_AMOUNT;
         NUGETITEMCLASSIFID := DAGE_ITEMS.FNUGETITEM_CLASSIF_ID( RCTEMORDITE.ITEMS_ID );
         IF ( DAGE_ITEM_CLASSIF.FSBGETQUANTITY_CONTROL( NUGETITEMCLASSIFID ) IN ( OR_BOCONSTANTS.CNUDECREASE, OR_BOCONSTANTS.CNUINCREASE ) ) OR ( DAGE_ITEMS.FNUGETITEM_CLASSIF_ID( TBITEMS( NUINDEX ).ITEMS_ID ) = OR_BOORDERACTIVITIES.CNUACTIVITYTYPE ) THEN
            RCTEMORDITE.VALUE := NULL;
            IF ( IBLRESETVALUES ) THEN
               RCTEMORDITE.LEGAL_ITEM_AMOUNT := NULL;
             ELSE
               IF ( NVL( TBITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT, 0 ) > 0 ) THEN
                  RCTEMORDITE.LEGAL_ITEM_AMOUNT := TBITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT;
                ELSE
                  RCTEMORDITE.LEGAL_ITEM_AMOUNT := TBITEMS( NUINDEX ).ASSIGNED_ITEM_AMOUNT;
               END IF;
            END IF;
          ELSE
            RCTEMORDITE.LEGAL_ITEM_AMOUNT := 0;
            RCTEMORDITE.VALUE := 0;
         END IF;
         DAOR_TEMP_ORDER_ITEMS.INSRECORD( RCTEMORDITE );
         EXIT WHEN ( NUINDEX = TBITEMS.LAST );
         NUINDEX := TBITEMS.NEXT( NUINDEX );
      END LOOP;
      UT_TRACE.TRACE( 'FIN or_boitems.FillOrderItemsTempTable', 12 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FILLORDERITEMSTEMPTABLE;
   PROCEDURE COMPUTEITEMS( INUORDER IN OR_ORDER.ORDER_ID%TYPE )
    IS
      RCTMPORDITE DAOR_TEMP_ORDER_ITEMS.STYOR_TEMP_ORDER_ITEMS;
      SBCOMERR VARCHAR2( 200 );
      TBITEMS GE_TYTBSTRING;
      CNUCANLEGAESNULOMENOR CONSTANT NUMBER := 2142;
      RCORDERDATA DAOR_ORDER.STYOR_ORDER;
      CURSOR CU_TEMPORDERITEMS( NUORDER IN OR_ORDER.ORDER_ID%TYPE ) IS
SELECT a.*, rowid
            FROM   Or_Temp_Order_Items a
            WHERE  Order_Id = nuOrder;
    BEGIN
      UT_TRACE.TRACE( 'Va a calcular Items (ComputeItems). Orden:' || INUORDER );
      RCORDERDATA := DAOR_ORDER.FRCGETRECORD( INUORDER );
      OR_BCTEMP_ORDER_ITEMS.DELAMOUNTZEROITEMS( INUORDER );
      OPEN CU_TEMPORDERITEMS( INUORDER );
      FETCH CU_TEMPORDERITEMS
         INTO RCTMPORDITE;
      IF ( CU_TEMPORDERITEMS%NOTFOUND ) THEN
         RETURN;
      END IF;
      WHILE ( CU_TEMPORDERITEMS%FOUND )
       LOOP
         UT_TRACE.TRACE( '--->Item:' || RCTMPORDITE.ITEMS_ID || 'Cant.Legalizar:' || RCTMPORDITE.LEGAL_ITEM_AMOUNT );
         IF ( RCTMPORDITE.LEGAL_ITEM_AMOUNT IS NULL ) OR ( RCTMPORDITE.LEGAL_ITEM_AMOUNT < 0 ) THEN
            SBCOMERR := TO_CHAR( RCTMPORDITE.ITEMS_ID ) || '|' || TO_CHAR( RCORDERDATA.NUMERATOR_ID ) || '-' || TO_CHAR( RCORDERDATA.SEQUENCE );
            ERRORS.SETERROR( CNUCANLEGAESNULOMENOR, SBCOMERR );
            RAISE EX.CONTROLLED_ERROR;
         END IF;
         RCTMPORDITE.VALUE := 0;
         UT_TRACE.TRACE( 'Valor Item:' || RCTMPORDITE.VALUE );
         DAOR_TEMP_ORDER_ITEMS.UPDRECORD( RCTMPORDITE );
         FETCH CU_TEMPORDERITEMS
            INTO RCTMPORDITE;
      END LOOP;
      BLCOMPUTEITEMS := TRUE;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END COMPUTEITEMS;
   PROCEDURE UPDITEMBALFROMORDERANDOPEUNI( INUORDER IN OR_ORDER_ITEMS.ORDER_ID%TYPE, INUOPEUNI IN OR_OPE_UNI_ITEM_BALA.OPERATING_UNIT_ID%TYPE, ITBACTIVITYITEMS IN OR_BCORDERACTIVITIES.TYTBACTIVITYITEMS, INUCONTRACTORID IN GE_CONTRATO.ID_CONTRATISTA%TYPE := NULL, INUCONTRACTID IN GE_CONTRATO.ID_CONTRATO%TYPE := NULL )
    IS
      TBORDERITEMS DAOR_ORDER_ITEMS.TYTBOR_ORDER_ITEMS;
      TBADITIONALDATA TYTBADITIONALDATA;
      SBDECREASE OR_ORDER_ITEMS.OUT_%TYPE;
      SBMOVETYPE GE_PARAMETER.VALUE%TYPE;
      NUCOST OR_OPE_UNI_ITEM_BALA.TOTAL_COSTS%TYPE;
      RCITEMSERIADO DAGE_ITEMS_SERIADO.STYGE_ITEMS_SERIADO;
      NUUNIITEMMOVID OR_UNI_ITEM_BALA_MOV.UNI_ITEM_BALA_MOV_ID%TYPE;
    BEGIN
      UT_TRACE.TRACE( 'Inicia OR_BOITEMS.UpdItemBalFromOrderAndOpeUni inuOrder:' || INUORDER, 4 );
      UPDITEMSCOST( INUORDER, INUOPEUNI, NULL, ITBACTIVITYITEMS, GE_BOCONSTANTS.CSBNO, TBORDERITEMS, TBADITIONALDATA, INUCONTRACTORID, INUCONTRACTID );
      GE_BOITEMWARRANTY.UPDITEMSCOSTSERIED( INUORDER );
      IF ( TBORDERITEMS.COUNT > 0 ) THEN
         FOR NUINDEX IN TBORDERITEMS.FIRST..TBORDERITEMS.LAST
          LOOP
            SBDECREASE := TBORDERITEMS( NUINDEX ).OUT_;
            IF ( SBDECREASE IS NULL ) THEN
               IF ( TBADITIONALDATA( NUINDEX ).SBQUANTITYCONTROL = OR_BOCONSTANTS.CNUDECREASE ) THEN
                  SBDECREASE := GE_BOCONSTANTS.CSBYES;
                ELSIF ( TBADITIONALDATA( NUINDEX ).SBQUANTITYCONTROL = OR_BOCONSTANTS.CNUINCREASE ) THEN
                  SBDECREASE := GE_BOCONSTANTS.CSBNO;
               END IF;
            END IF;
            IF ( SBDECREASE = GE_BOCONSTANTS.CSBYES ) THEN
               SBMOVETYPE := OR_BOITEMSMOVE.CSBDECREASEMOVETYPE;
             ELSIF ( SBDECREASE = GE_BOCONSTANTS.CSBNO ) AND NVL( TBADITIONALDATA( NUINDEX ).SBRECOVERY, GE_BOCONSTANTS.CSBYES ) = GE_BOCONSTANTS.CSBYES THEN
               SBMOVETYPE := OR_BOITEMSMOVE.CSBINCREASEMOVETYPE;
             ELSE
               SBMOVETYPE := OR_BOITEMSMOVE.CSBNEUTRALMOVETYPE;
            END IF;
            UT_TRACE.TRACE( '-->Actualización de saldo de items orden: ' || INUORDER || ' item: ' || TBORDERITEMS( NUINDEX ).ITEMS_ID, 4 );
            IF ( TBADITIONALDATA( NUINDEX ).SBQUANTITYCONTROL != OR_BOCONSTANTS.CSBNO ) THEN
               NUCOST := NULL;
               NUUNIITEMMOVID := NULL;
               IF ( TBORDERITEMS( NUINDEX ).OUT_ = GE_BOCONSTANTS.CSBNO ) THEN
                  OR_BOITEMSMOVE.CREATEMOVBYLEGALIZE( INUORDER, INUOPEUNI, TBORDERITEMS( NUINDEX ).ITEMS_ID, RCITEMSERIADO, SBMOVETYPE, TBORDERITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT, NUCOST, NUUNIITEMMOVID );
                ELSIF ( TBORDERITEMS( NUINDEX ).OUT_ = GE_BOCONSTANTS.CSBYES ) THEN
                  IF ( TBORDERITEMS( NUINDEX ).SERIAL_ITEMS_ID IS NULL OR ( DAGE_ITEMS_SERIADO.FNUGETID_ITEMS_ESTADO_INV( TBORDERITEMS( NUINDEX ).SERIAL_ITEMS_ID ) NOT IN ( GE_BOITEMSCONSTANTS.CNUSTATUS_ENUSO, GE_BOITEMSCONSTANTS.CNUSTATUS_POR_RECUPERAR ) ) ) THEN
                     OR_BOITEMSMOVE.CREATEMOVBYLEGALIZE( INUORDER, INUOPEUNI, TBORDERITEMS( NUINDEX ).ITEMS_ID, RCITEMSERIADO, SBMOVETYPE, TBORDERITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT, NUCOST, NUUNIITEMMOVID );
                  END IF;
                ELSE
                  OR_BOITEMSMOVE.CREATEMOVBYLEGALIZE( INUORDER, INUOPEUNI, TBORDERITEMS( NUINDEX ).ITEMS_ID, RCITEMSERIADO, SBMOVETYPE, TBORDERITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT, NUCOST, NUUNIITEMMOVID );
               END IF;
            END IF;
         END LOOP;
      END IF;
      UT_TRACE.TRACE( 'fin OR_BOITEMS.UpdItemBalFromOrderAndOpeUni inuOrder:' || INUORDER, 4 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   FUNCTION FBLHAVEOPEUNIITEMSENOUGH( INUOPERUNIT IN OR_OPE_UNI_ITEM_BALA.OPERATING_UNIT_ID%TYPE, INUITEMCODE IN OR_OPE_UNI_ITEM_BALA.ITEMS_ID%TYPE, INUITEMAMOUNT IN OR_OPE_UNI_ITEM_BALA.BALANCE%TYPE, ISBLOCKMODE IN VARCHAR2 := OR_BOCONSTANTS.CSBNO )
    RETURN BOOLEAN
    IS
      NUBALANCE OR_OPE_UNI_ITEM_BALA.BALANCE%TYPE;
      CURSOR CU_LOCK IS
SELECT Balance
            FROM   Or_Ope_Uni_Item_Bala
            WHERE  Items_Id = inuItemCode
              AND Operating_Unit_Id = inuOperUnit
            FOR UPDATE of Balance;
    BEGIN
      DAOR_OPE_UNI_ITEM_BALA.ACCKEY( INUITEMCODE, INUOPERUNIT );
      NUBALANCE := DAOR_OPE_UNI_ITEM_BALA.FNUGETBALANCE( INUITEMCODE, INUOPERUNIT );
      IF ( NUBALANCE >= INUITEMAMOUNT ) THEN
         IF ( ISBLOCKMODE = OR_BOCONSTANTS.CSBSI ) THEN
            OPEN CU_LOCK;
            CLOSE CU_LOCK;
         END IF;
         RETURN TRUE;
      END IF;
      RETURN FALSE;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         IF ( CU_LOCK%ISOPEN ) THEN
            CLOSE CU_LOCK;
         END IF;
         RETURN FALSE;
      WHEN OTHERS THEN
         IF ( CU_LOCK%ISOPEN ) THEN
            CLOSE CU_LOCK;
         END IF;
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FBLHAVEOPEUNIITEMSENOUGH;
   PROCEDURE FREEITEMSFOROPERATINGUNIT( INUORDER IN OR_ORDER.ORDER_ID%TYPE, INUOPERUNIT IN OR_ORDER.OPERATING_UNIT_ID%TYPE )
    IS
      TBITEMS TYTBITEMS;
      NUCONTA BINARY_INTEGER;
    BEGIN
      OR_BOITEMS.GETITEMSORDER( INUORDER, TBITEMS );
      IF ( TBITEMS.COUNT != 0 ) THEN
         NUCONTA := TBITEMS.FIRST;
         LOOP
            FREEBALANCE( TBITEMS( NUCONTA ).ITEMS_ID, INUOPERUNIT, TBITEMS( NUCONTA ).ASSIGNED_ITEM_AMOUNT );
            EXIT WHEN ( NUCONTA = TBITEMS.LAST );
            NUCONTA := TBITEMS.NEXT( NUCONTA );
         END LOOP;
      END IF;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FREEITEMSFOROPERATINGUNIT;
   PROCEDURE UPDITEMSFOROPERATINGUNIT( INUORDER IN OR_ORDER.ORDER_ID%TYPE, INUOPERUNIT IN OR_ORDER.OPERATING_UNIT_ID%TYPE )
    IS
      TBITEMS TYTBITEMS;
      NUCONTA BINARY_INTEGER;
    BEGIN
      OR_BOITEMS.GETITEMSORDER( INUORDER, TBITEMS );
      IF ( TBITEMS.COUNT = 0 ) THEN
         RETURN;
      END IF;
      NUCONTA := TBITEMS.FIRST;
      LOOP
         OR_BOOPEUNIITEMBALA.UPDBALANCE( TBITEMS( NUCONTA ).ITEMS_ID, INUOPERUNIT, TBITEMS( NUCONTA ).ASSIGNED_ITEM_AMOUNT, TBITEMS( NUCONTA ).OUT_ );
         EXIT WHEN ( NUCONTA = TBITEMS.LAST );
         NUCONTA := TBITEMS.NEXT( NUCONTA );
      END LOOP;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END UPDITEMSFOROPERATINGUNIT;
   FUNCTION FBLEXISTITEMINTOTALTABLE( INUITEM IN GE_ITEMS.ITEMS_ID%TYPE, ITBITEMS IN OR_BOITEMS.TYTBTOTALITEMSORDERS, ONUPOSITION OUT NUMBER )
    RETURN BOOLEAN
    IS
      NUINDEX BINARY_INTEGER;
    BEGIN
      ONUPOSITION := -1;
      IF ( ITBITEMS.COUNT = 0 ) THEN
         RETURN FALSE;
      END IF;
      NUINDEX := ITBITEMS.FIRST;
      LOOP
         IF ( INUITEM = ITBITEMS( NUINDEX ).ITEMS_ID ) THEN
            ONUPOSITION := NUINDEX;
            RETURN TRUE;
         END IF;
         EXIT WHEN ( NUINDEX = ITBITEMS.LAST );
         NUINDEX := ITBITEMS.NEXT( NUINDEX );
      END LOOP;
      RETURN FALSE;
    EXCEPTION
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FBLEXISTITEMINTOTALTABLE;
   PROCEDURE UPDATEITEMAMOUNTINTOTALTABLE( INUITEMID IN OR_ORDER_ITEMS.ITEMS_ID%TYPE, INUASSITEMAMOUNT IN OR_ORDER_ITEMS.ASSIGNED_ITEM_AMOUNT%TYPE, IOTBITEMS IN OUT OR_BOITEMS.TYTBTOTALITEMSORDERS, INUPOSITION IN NUMBER )
    IS
      NUGETITEMCLASSIFID GE_ITEMS.ITEM_CLASSIF_ID%TYPE;
    BEGIN
      NUGETITEMCLASSIFID := DAGE_ITEMS.FNUGETITEM_CLASSIF_ID( INUITEMID );
      IF ( DAGE_ITEM_CLASSIF.FSBGETQUANTITY_CONTROL( NUGETITEMCLASSIFID ) = OR_BOCONSTANTS.CNUDECREASE ) THEN
         IOTBITEMS( INUPOSITION ).ASSIGNED_ITEM_AMOUNT := IOTBITEMS( INUPOSITION ).ASSIGNED_ITEM_AMOUNT + INUASSITEMAMOUNT;
       ELSIF DAGE_ITEM_CLASSIF.FSBGETQUANTITY_CONTROL( NUGETITEMCLASSIFID ) = OR_BOCONSTANTS.CNUINCREASE THEN
         IF ( INUASSITEMAMOUNT > IOTBITEMS( INUPOSITION ).ASSIGNED_ITEM_AMOUNT ) THEN
            IOTBITEMS( INUPOSITION ).ASSIGNED_ITEM_AMOUNT := INUASSITEMAMOUNT;
         END IF;
       ELSE
         NULL;
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END UPDATEITEMAMOUNTINTOTALTABLE;
   PROCEDURE LOADITEMSTOTOTALTABLE( ITBORDITEMS IN OR_BOITEMS.TYTBITEMS, IOTBITEMS IN OUT OR_BOITEMS.TYTBTOTALITEMSORDERS )
    IS
      NUINDEX BINARY_INTEGER;
      NUTOTINDEX BINARY_INTEGER;
      NUPOSITION NUMBER := -1;
    BEGIN
      IF ( ITBORDITEMS.COUNT = 0 ) THEN
         RETURN;
      END IF;
      NUINDEX := ITBORDITEMS.FIRST;
      LOOP
         IF ( FBLEXISTITEMINTOTALTABLE( ITBORDITEMS( NUINDEX ).ITEMS_ID, IOTBITEMS, NUPOSITION ) ) THEN
            UPDATEITEMAMOUNTINTOTALTABLE( ITBORDITEMS( NUINDEX ).ITEMS_ID, ITBORDITEMS( NUINDEX ).ASSIGNED_ITEM_AMOUNT, IOTBITEMS, NUPOSITION );
          ELSE
            IF ( IOTBITEMS.COUNT = 0 ) THEN
               NUTOTINDEX := 1;
             ELSE
               NUTOTINDEX := IOTBITEMS.LAST + 1;
            END IF;
            IOTBITEMS( NUTOTINDEX ).ITEMS_ID := ITBORDITEMS( NUINDEX ).ITEMS_ID;
            IOTBITEMS( NUTOTINDEX ).ASSIGNED_ITEM_AMOUNT := ITBORDITEMS( NUINDEX ).ASSIGNED_ITEM_AMOUNT;
         END IF;
         EXIT WHEN ( NUINDEX = ITBORDITEMS.LAST );
         NUINDEX := ITBORDITEMS.NEXT( NUINDEX );
      END LOOP;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END LOADITEMSTOTOTALTABLE;
   PROCEDURE GETTOTALITEMSFORALLORDERS( ITBORDERS IN DAOR_ORDER.TYTBORDER_ID, OTBITEMS OUT OR_BOITEMS.TYTBTOTALITEMSORDERS )
    IS
      NUINDEX BINARY_INTEGER;
      SBORDERS VARCHAR2( 2000 );
      SBSQL VARCHAR2( 4000 );
      RCTOTALITEMS OR_BOITEMS.TYRCTOTALITEMSORDERS;
      TBORDERITEMS OR_BOITEMS.TYTBITEMS;
    BEGIN
      IF ( ITBORDERS.COUNT = 0 ) THEN
         RETURN;
      END IF;
      NUINDEX := ITBORDERS.FIRST;
      LOOP
         OR_BOITEMS.GETITEMSORDER( ITBORDERS( NUINDEX ), TBORDERITEMS );
         LOADITEMSTOTOTALTABLE( TBORDERITEMS, OTBITEMS );
         EXIT WHEN ( NUINDEX = ITBORDERS.LAST );
         NUINDEX := ITBORDERS.NEXT( NUINDEX );
      END LOOP;
    EXCEPTION
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END GETTOTALITEMSFORALLORDERS;
   PROCEDURE DELETEISOMDIAGTECHCARD( INUTECH_CARD_ITEM_ID IN GE_TECH_CARD_ITEM.TECH_CARD_ITEM_ID%TYPE )
    IS
      CURSOR CUISOMDIAGITEM( TECH_CARD_ITEM IN NUMBER ) IS
SELECT Item_Isom_Diagram_Id
            FROM   Ge_Item_Isom_Diagram
            WHERE  Ge_Item_Isom_Diagram.Tech_Card_Item_Id in (Tech_Card_Item);
    BEGIN
      FOR RCRECORD IN CUISOMDIAGITEM( INUTECH_CARD_ITEM_ID )
       LOOP
         DELETE FROM Ge_Item_Isom_Diagram
             WHERE Item_Isom_Diagram_Id = rcRecord.Item_Isom_Diagram_Id;
      END LOOP;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         IF CUISOMDIAGITEM%ISOPEN THEN
            CLOSE CUISOMDIAGITEM;
         END IF;
         RAISE;
      WHEN OTHERS THEN
         IF CUISOMDIAGITEM%ISOPEN THEN
            CLOSE CUISOMDIAGITEM;
         END IF;
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END DELETEISOMDIAGTECHCARD;
   PROCEDURE DELETEPHOTOTECHCARD( INUTECH_CARD_ITEM_ID IN GE_TECH_CARD_ITEM.TECH_CARD_ITEM_ID%TYPE )
    IS
      CURSOR CUPHOTOITEM( TECH_CARD_ITEM IN NUMBER ) IS
SELECT Item_Photo_Id
            FROM   Ge_Item_Photo
            WHERE  Ge_Item_Photo.Tech_Card_Item_Id in (Tech_Card_Item);
    BEGIN
      FOR RCRECORD IN CUPHOTOITEM( INUTECH_CARD_ITEM_ID )
       LOOP
         DELETE From Ge_Item_Photo
             Where Item_Photo_Id = rcRecord.Item_Photo_Id;
      END LOOP;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         IF CUPHOTOITEM%ISOPEN THEN
            CLOSE CUPHOTOITEM;
         END IF;
         RAISE;
      WHEN OTHERS THEN
         IF CUPHOTOITEM%ISOPEN THEN
            CLOSE CUPHOTOITEM;
         END IF;
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END DELETEPHOTOTECHCARD;
   FUNCTION FNUGETITEMMOVECAUS
    RETURN NUMBER
    IS
    BEGIN
      RETURN ( GNUITEMMOVECAUS );
    EXCEPTION
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FNUGETITEMMOVECAUS;
   PROCEDURE INSERTINTEMTAB( INUITEMMOVECAUS IN NUMBER )
    IS
    BEGIN
      GNUITEMMOVECAUS := INUITEMMOVECAUS;
    EXCEPTION
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END INSERTINTEMTAB;
   PROCEDURE UPDATELEGALITEMSAMMOUNT( INUORDER IN OR_ORDER.ORDER_ID%TYPE, INULEGAL_ITEM_AMOUNT IN OR_TEMP_ORDER_ITEMS.LEGAL_ITEM_AMOUNT%TYPE )
    IS
    BEGIN
      UPDATE or_temp_order_items
        SET    legal_item_amount = inulegal_item_amount
        WHERE  ORDER_id = inuOrder ;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END UPDATELEGALITEMSAMMOUNT;
   PROCEDURE INSERTORUPDATEITEMSLIS( INUITEMID IN GE_UNIT_COST_ITE_LIS.ITEMS_ID%TYPE, INUPRICE IN GE_UNIT_COST_ITE_LIS.PRICE%TYPE )
    IS
    BEGIN
      GE_BOLISTUNITARYCOST.ADDITEMPRICETOLIST( INUITEMID, INUPRICE );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END INSERTORUPDATEITEMSLIS;
   FUNCTION FSBVERSION
    RETURN VARCHAR2
    IS
    BEGIN
      RETURN CSBVERSION;
   END;
   FUNCTION FNUGETTEMPORDERITEMSID( INUORDERID IN OR_TEMP_ORDER_ITEMS.ORDER_ID%TYPE, INUITEMSID IN OR_TEMP_ORDER_ITEMS.ITEMS_ID%TYPE )
    RETURN OR_TEMP_ORDER_ITEMS.TEMP_ORDER_ITEMS_ID%TYPE
    IS
      CURSOR CUTEMPORDERITEMS( NUORDERID IN OR_TEMP_ORDER_ITEMS.ORDER_ID%TYPE, NUITEMSID IN OR_TEMP_ORDER_ITEMS.ITEMS_ID%TYPE ) IS
SELECT temp_order_items_id
          FROM  OR_temp_order_items
         WHERE  order_id = nuOrderId
           AND  Items_Id = nuItemsId;
      NUTEMPORDERITEMSID OR_TEMP_ORDER_ITEMS.TEMP_ORDER_ITEMS_ID%TYPE := NULL;
    BEGIN
      IF CUTEMPORDERITEMS%ISOPEN THEN
         CLOSE CUTEMPORDERITEMS;
      END IF;
      OPEN CUTEMPORDERITEMS( INUORDERID, INUITEMSID );
      FETCH CUTEMPORDERITEMS
         INTO NUTEMPORDERITEMSID;
      CLOSE CUTEMPORDERITEMS;
      RETURN NUTEMPORDERITEMSID;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         IF CUTEMPORDERITEMS%ISOPEN THEN
            CLOSE CUTEMPORDERITEMS;
         END IF;
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         IF CUTEMPORDERITEMS%ISOPEN THEN
            CLOSE CUTEMPORDERITEMS;
         END IF;
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FNUGETTEMPORDERITEMSID;
   PROCEDURE ADDITEMSTEMPTABLE( INUORDERID IN OR_TEMP_ORDER_ITEMS.ORDER_ID%TYPE, INUITEMSID IN OR_TEMP_ORDER_ITEMS.ITEMS_ID%TYPE, INULEGALITEMAMOUNT IN OR_TEMP_ORDER_ITEMS.LEGAL_ITEM_AMOUNT%TYPE, ISBOUT_ IN OR_TEMP_ORDER_ITEMS.OUT_%TYPE )
    IS
      RCTEMORDITE DAOR_TEMP_ORDER_ITEMS.STYOR_TEMP_ORDER_ITEMS;
      NUTEMPORDERITEMSID OR_TEMP_ORDER_ITEMS.TEMP_ORDER_ITEMS_ID%TYPE;
    BEGIN
      UT_TRACE.TRACE( 'OR_BOItems.AddItemsTempTable INICIO ', 2 );
      NUTEMPORDERITEMSID := FNUGETTEMPORDERITEMSID( INUORDERID, INUITEMSID );
      RCTEMORDITE.TEMP_ORDER_ITEMS_ID := OR_BOSEQUENCES.FNUNEXTOR_ORDER_ITEMS;
      RCTEMORDITE.ORDER_ID := INUORDERID;
      RCTEMORDITE.ITEMS_ID := INUITEMSID;
      RCTEMORDITE.LEGAL_ITEM_AMOUNT := INULEGALITEMAMOUNT;
      RCTEMORDITE.ASSIGNED_ITEM_AMOUNT := 0;
      RCTEMORDITE.VALUE := 0;
      RCTEMORDITE.OUT_ := ISBOUT_;
      DAOR_TEMP_ORDER_ITEMS.INSRECORD( RCTEMORDITE );
      UT_TRACE.TRACE( 'OR_BOItems.AddItemsTempTable FIN ', 2 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   FUNCTION FBLEXISTORDERITEMS( INUORDERID IN OR_ORDER.ORDER_ID%TYPE )
    RETURN BOOLEAN
    IS
      RCORDERNETNET OR_BCITEMS.CUITEMSINORDER%ROWTYPE;
    BEGIN
      IF OR_BCITEMS.CUITEMSINORDER%ISOPEN THEN
         CLOSE OR_BCITEMS.CUITEMSINORDER;
      END IF;
      OPEN OR_BCITEMS.CUITEMSINORDER( INUORDERID );
      FETCH OR_BCITEMS.CUITEMSINORDER
         INTO RCORDERNETNET;
      IF OR_BCITEMS.CUITEMSINORDER%NOTFOUND THEN
         CLOSE OR_BCITEMS.CUITEMSINORDER;
         RETURN FALSE;
      END IF;
      CLOSE OR_BCITEMS.CUITEMSINORDER;
      RETURN TRUE;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         IF OR_BCITEMS.CUITEMSINORDER%ISOPEN THEN
            CLOSE OR_BCITEMS.CUITEMSINORDER;
         END IF;
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         IF OR_BCITEMS.CUITEMSINORDER%ISOPEN THEN
            CLOSE OR_BCITEMS.CUITEMSINORDER;
         END IF;
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   FUNCTION FBLEXISTTASKTYPESITEMS( INUTASTTYPEID IN OR_ORDER.TASK_TYPE_ID%TYPE )
    RETURN BOOLEAN
    IS
      RCORDERNETNET OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE%ROWTYPE;
    BEGIN
      IF OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE%ISOPEN THEN
         CLOSE OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE;
      END IF;
      OPEN OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE( INUTASTTYPEID );
      FETCH OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE
         INTO RCORDERNETNET;
      IF OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE%NOTFOUND THEN
         CLOSE OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE;
         RETURN FALSE;
      END IF;
      CLOSE OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE;
      RETURN TRUE;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         IF OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE%ISOPEN THEN
            CLOSE OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE;
         END IF;
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         IF OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE%ISOPEN THEN
            CLOSE OR_BCITEMS.CUTASKTYPESITEMSBYTASTYPE;
         END IF;
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   PROCEDURE INSERTORUPDATEITEMSTEMPTABLE( INUORDERID IN OR_TEMP_ORDER_ITEMS.ORDER_ID%TYPE, INUITEMSID IN OR_TEMP_ORDER_ITEMS.ITEMS_ID%TYPE, INULEGALITEMAMOUNT IN OR_TEMP_ORDER_ITEMS.LEGAL_ITEM_AMOUNT%TYPE, ISBOUT_ IN OR_TEMP_ORDER_ITEMS.OUT_%TYPE, IONUTEMPORDERITEMSID IN OUT OR_TEMP_ORDER_ITEMS.TEMP_ORDER_ITEMS_ID%TYPE )
    IS
      RCTEMORDITE DAOR_TEMP_ORDER_ITEMS.STYOR_TEMP_ORDER_ITEMS;
    BEGIN
      UT_TRACE.TRACE( 'OR_BOItems.InsertOrUpdateItemsTempTable INICIO ', 2 );
      IF IONUTEMPORDERITEMSID IS NULL OR NOT DAOR_TEMP_ORDER_ITEMS.FBLEXIST( IONUTEMPORDERITEMSID ) THEN
         UT_TRACE.TRACE( 'insertandotablaTEMPORAL OLD_ORDER_item_id=' || IONUTEMPORDERITEMSID, 15 );
         IF DAGE_ITEMS.FNUGETITEM_CLASSIF_ID( INUITEMSID ) != OR_BOORDERACTIVITIES.CNUACTIVITYTYPE OR IONUTEMPORDERITEMSID IS NULL THEN
            IONUTEMPORDERITEMSID := OR_BOSEQUENCES.FNUNEXTOR_ORDER_ITEMS;
         END IF;
         RCTEMORDITE.TEMP_ORDER_ITEMS_ID := IONUTEMPORDERITEMSID;
         RCTEMORDITE.ORDER_ID := INUORDERID;
         RCTEMORDITE.ITEMS_ID := INUITEMSID;
         RCTEMORDITE.LEGAL_ITEM_AMOUNT := INULEGALITEMAMOUNT;
         RCTEMORDITE.ASSIGNED_ITEM_AMOUNT := 0;
         RCTEMORDITE.VALUE := 0;
         RCTEMORDITE.OUT_ := ISBOUT_;
         DAOR_TEMP_ORDER_ITEMS.INSRECORD( RCTEMORDITE );
       ELSE
         UT_TRACE.TRACE( 'ActualizandoTablaTemporal ORDER_item_id=' || IONUTEMPORDERITEMSID, 15 );
         RCTEMORDITE := DAOR_TEMP_ORDER_ITEMS.FRCGETRECORD( IONUTEMPORDERITEMSID );
         RCTEMORDITE.ORDER_ID := INUORDERID;
         RCTEMORDITE.ITEMS_ID := INUITEMSID;
         RCTEMORDITE.LEGAL_ITEM_AMOUNT := INULEGALITEMAMOUNT;
         RCTEMORDITE.OUT_ := ISBOUT_;
         DAOR_TEMP_ORDER_ITEMS.UPDRECORD( RCTEMORDITE );
      END IF;
      UT_TRACE.TRACE( 'OR_BOItems.InsertOrUpdateItemsTempTable FIN ', 2 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   PROCEDURE DELETETEMPORDERITEMS( INUORDERID IN OR_TEMP_ORDER_ITEMS.ORDER_ID%TYPE )
    IS
    BEGIN
      DELETE or_temp_order_items WHERE order_id = inuOrderId;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   PROCEDURE FILLORDERITEMSTEMPTABLEPL( INUORDER IN OR_ORDER.ORDER_ID%TYPE, IBLRESETVALUES IN BOOLEAN := TRUE, INUCAUSALID IN OR_ORDER.CAUSAL_ID%TYPE )
    IS
      TBITEMS OR_BCLEGALIZEITEMS.TYTBITEMS;
      NUINDEX BINARY_INTEGER;
      RCTEMORDITE DAOR_TEMP_ORDER_ITEMS.STYOR_TEMP_ORDER_ITEMS;
      CNUOR_WITHOUT_ITEM CONSTANT NUMBER := 392;
      NUGETITEMCLASSIFID GE_ITEMS.ITEM_CLASSIF_ID%TYPE;
    BEGIN
      IF ( NOT FBLISEMPTYORDERITEMSTEMPTAB( INUORDER ) ) THEN
         RETURN;
      END IF;
      OR_BCLEGALIZEITEMS.GETITEMSORDER( INUORDER, TBITEMS );
      IF ( TBITEMS.COUNT = 0 ) THEN
         RETURN;
      END IF;
      NUINDEX := TBITEMS.FIRST;
      LOOP
         RCTEMORDITE.TEMP_ORDER_ITEMS_ID := TBITEMS( NUINDEX ).ORDER_ITEMS_ID;
         RCTEMORDITE.ORDER_ID := INUORDER;
         RCTEMORDITE.ITEMS_ID := TBITEMS( NUINDEX ).ITEMS_ID;
         RCTEMORDITE.ASSIGNED_ITEM_AMOUNT := TBITEMS( NUINDEX ).ASSIGNED_ITEM_AMOUNT;
         RCTEMORDITE.OUT_ := TBITEMS( NUINDEX ).OUT_;
         NUGETITEMCLASSIFID := DAGE_ITEMS.FNUGETITEM_CLASSIF_ID( RCTEMORDITE.ITEMS_ID );
         IF ( DAGE_ITEM_CLASSIF.FSBGETQUANTITY_CONTROL( NUGETITEMCLASSIFID ) IN ( OR_BOCONSTANTS.CNUDECREASE, OR_BOCONSTANTS.CNUINCREASE ) ) OR ( DAGE_ITEMS.FNUGETITEM_CLASSIF_ID( TBITEMS( NUINDEX ).ITEMS_ID ) = OR_BOORDERACTIVITIES.CNUACTIVITYTYPE ) THEN
            RCTEMORDITE.VALUE := NULL;
            IF ( IBLRESETVALUES ) THEN
               RCTEMORDITE.LEGAL_ITEM_AMOUNT := NULL;
             ELSE
               IF ( NVL( TBITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT, 0 ) > 0 ) THEN
                  RCTEMORDITE.LEGAL_ITEM_AMOUNT := TBITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT;
                ELSE
                  IF ( NOT GE_BOCAUSAL.FBLGETSUCESSFULLCLASSCAUSAL( INUCAUSALID ) ) THEN
                     RCTEMORDITE.LEGAL_ITEM_AMOUNT := 0;
                   ELSE
                     RCTEMORDITE.LEGAL_ITEM_AMOUNT := TBITEMS( NUINDEX ).ASSIGNED_ITEM_AMOUNT;
                  END IF;
               END IF;
            END IF;
          ELSE
            RCTEMORDITE.LEGAL_ITEM_AMOUNT := 0;
            RCTEMORDITE.VALUE := 0;
         END IF;
         DAOR_TEMP_ORDER_ITEMS.INSRECORD( RCTEMORDITE );
         EXIT WHEN ( NUINDEX = TBITEMS.LAST );
         NUINDEX := TBITEMS.NEXT( NUINDEX );
      END LOOP;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FILLORDERITEMSTEMPTABLEPL;
   PROCEDURE UPDITEMSCOST( INUORDER IN OR_ORDER_ITEMS.ORDER_ID%TYPE, INUOPEUNI IN OR_OPE_UNI_ITEM_BALA.OPERATING_UNIT_ID%TYPE, IDTDATE IN OR_ORDER.ASSIGNED_DATE%TYPE, ITBACTIVITYITEMS IN OR_BCORDERACTIVITIES.TYTBACTIVITYITEMS, ISBFORCELISTCOST IN VARCHAR2, OTBORDERITEMS OUT DAOR_ORDER_ITEMS.TYTBOR_ORDER_ITEMS, OTBADITIONALDATA OUT TYTBADITIONALDATA, INUCONTRACTORID IN GE_CONTRATO.ID_CONTRATISTA%TYPE := NULL, INUCONTRACTID IN GE_CONTRATO.ID_CONTRATO%TYPE := NULL )
    IS
      RCORDERITEMS DAOR_ORDER_ITEMS.STYOR_ORDER_ITEMS;
      DTASSIGNEDDATE OR_ORDER.ASSIGNED_DATE%TYPE;
      SBQUANTITYCONTROL GE_ITEM_CLASSIF.QUANTITY_CONTROL%TYPE;
      SBCOSTMETHOD GE_ITEM_CLASSIF.COST_METHOD%TYPE;
      NUBALANCE OR_OPE_UNI_ITEM_BALA.BALANCE%TYPE;
      NUBALANCEPRICE OR_OPE_UNI_ITEM_BALA.TOTAL_COSTS%TYPE;
      NUTOTALVALUEITEM OR_ORDER_ITEMS.VALUE%TYPE;
      NUCOSTCOTIZEDVALITEM OR_ORDER_ITEMS.VALUE%TYPE;
      NULIQMETHOD PS_PACKAGE_TYPE.LIQUIDATION_METHOD%TYPE;
      RCITEMS DAGE_ITEMS.STYGE_ITEMS;
      BLISACTIVITY BOOLEAN;
      SBDECREASE OR_ORDER_ITEMS.OUT_%TYPE;
      RCITEMSERIADO DAGE_ITEMS_SERIADO.STYGE_ITEMS_SERIADO;
      NUUNIITEMMOVID OR_UNI_ITEM_BALA_MOV.UNI_ITEM_BALA_MOV_ID%TYPE;
      NUINDEX BINARY_INTEGER;
      RCQUOTATION DACC_QUOTATION.STYCC_QUOTATION;
      NUPACKAGEID OR_ORDER_ACTIVITY.PACKAGE_ID%TYPE;
      NUTASKTYPEID OR_TASK_TYPE.TASK_TYPE_ID%TYPE;
      NUOPERAIUORDER OR_ORDER.OPERATIVE_AIU_VALUE%TYPE := 0;
      NUOPERAIUVALUE OR_ORDER.OPERATIVE_AIU_VALUE%TYPE := 0;
      NUADMINAIUORDER OR_ORDER.ADMIN_AIU_VALUE%TYPE := 0;
      NUADMINAIUVALUE NUMBER;
      NUAIUPERCENT NUMBER;
      RCORDER DAOR_ORDER.STYOR_ORDER;
      RCTASKTYPE DAOR_TASK_TYPE.STYOR_TASK_TYPE;
      BLGENERATEAUI BOOLEAN;
      NUADDRESSID OR_ORDER.EXTERNAL_ADDRESS_ID%TYPE := NULL;
      CURSOR CU_ITEMORDER( NUORDER IN OR_ORDER.ORDER_ID%TYPE ) IS
SELECT a.*, rowid
            FROM   Or_Order_Items a
            WHERE  Order_Id = nuOrder
            AND   nvl(legal_item_amount, 0) > 0;
      PROCEDURE CLOSECURSOR
       IS
       BEGIN
         IF ( CU_ITEMORDER%ISOPEN ) THEN
            CLOSE CU_ITEMORDER;
         END IF;
       EXCEPTION
         WHEN EX.CONTROLLED_ERROR THEN
            RAISE;
         WHEN OTHERS THEN
            ERRORS.SETERROR;
            RAISE EX.CONTROLLED_ERROR;
      END;
    BEGIN
      UT_TRACE.TRACE( 'Inicia or_boitems.UpdItemsCost. inuOrder: ' || TO_CHAR( INUORDER ) || ' inuOpeUni: ' || TO_CHAR( INUOPEUNI ) || ' isbForceListCost: ' || ISBFORCELISTCOST || ' inuContractorId ' || TO_CHAR( INUCONTRACTORID ) || ' inuContractId ' || TO_CHAR( INUCONTRACTID ), 5 );
      DAOR_ORDER.GETRECORD( INUORDER, RCORDER );
      IF ( IDTDATE IS NULL ) THEN
         DTASSIGNEDDATE := RCORDER.ASSIGNED_DATE;
       ELSE
         DTASSIGNEDDATE := IDTDATE;
      END IF;
      DAOR_TASK_TYPE.GETRECORD( RCORDER.TASK_TYPE_ID, RCTASKTYPE );
      NUTASKTYPEID := RCTASKTYPE.TASK_TYPE_ID;
      BLGENERATEAUI := OR_BOCONCEPTVALUE.FBOCONCEPTWITHADMAIU( RCTASKTYPE.CONCEPT );
      IF BLGENERATEAUI THEN
         UT_TRACE.TRACE( 'SI hay configuración para generación de cargo AIU para el concepto del tipo de trabajo (' || RCORDER.TASK_TYPE_ID || ')', 2 );
       ELSE
         UT_TRACE.TRACE( 'NO hay configuración para generación de cargo AIU para el concepto del tipo de trabajo (' || RCORDER.TASK_TYPE_ID || ')', 2 );
      END IF;
      NUADDRESSID := RCORDER.EXTERNAL_ADDRESS_ID;
      OR_BOITEMVALUE.GETLIQMETHOD( INUORDER, NUPACKAGEID, NULIQMETHOD );
      IF ( NUPACKAGEID IS NOT NULL ) THEN
         RCQUOTATION := CC_BCQUOTATION.FRCGETVALIDQUOTBYPACK( NUPACKAGEID );
      END IF;
      OPEN CU_ITEMORDER( INUORDER );
      FETCH CU_ITEMORDER
         BULK COLLECT INTO OTBORDERITEMS;
      CLOSE CU_ITEMORDER;
      IF ( OTBORDERITEMS.COUNT > 0 ) THEN
         FOR NUINDEX IN OTBORDERITEMS.FIRST..OTBORDERITEMS.LAST
          LOOP
            NUADMINAIUVALUE := 0;
            NUOPERAIUVALUE := 0;
            BLISACTIVITY := DAGE_ITEMS.FNUGETITEM_CLASSIF_ID( OTBORDERITEMS( NUINDEX ).ITEMS_ID ) = OR_BOORDERACTIVITIES.FNUACTIVITYTYPE();
            RCITEMS.RECOVERY := NULL;
            IF ( NOT BLISACTIVITY AND OTBORDERITEMS( NUINDEX ).OUT_ = GE_BOCONSTANTS.CSBNO ) THEN
               RCITEMS := DAGE_ITEMS.FRCGETRECORD( OTBORDERITEMS( NUINDEX ).ITEMS_ID );
               RCITEMS.RECOVERY := NVL( RCITEMS.RECOVERY, GE_BOCONSTANTS.CSBNO );
               IF ( RCITEMS.RECOVERY = GE_BOCONSTANTS.CSBYES ) THEN
                  OTBORDERITEMS( NUINDEX ).ITEMS_ID := NVL( RCITEMS.RECOVERY_ITEM_ID, OTBORDERITEMS( NUINDEX ).ITEMS_ID );
               END IF;
            END IF;
            UT_TRACE.TRACE( 'Obtiene el costo del item. nuLiqMethod: ' || TO_CHAR( NULIQMETHOD ), 2 );
            OR_BOITEMVALUE.GETITEMVALUEANDCOSTMETHOD( OTBORDERITEMS( NUINDEX ).ITEMS_ID, OTBORDERITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT, INUOPEUNI, DTASSIGNEDDATE, OTBORDERITEMS( NUINDEX ).OUT_, NUBALANCE, NUBALANCEPRICE, NUTOTALVALUEITEM, SBCOSTMETHOD, SBQUANTITYCONTROL, ISBFORCELISTCOST, INUORDER, INUCONTRACTORID, INUCONTRACTID );
            OTBORDERITEMS( NUINDEX ).VALUE := NVL( NUTOTALVALUEITEM, 0 );
            NUCOSTCOTIZEDVALITEM := NULL;
            NUOPERAIUVALUE := OR_BOITEMVALUE.FNUGETOPERATIVEAIU( INUORDER, NVL( NUTOTALVALUEITEM, 0 ), OTBORDERITEMS( NUINDEX ).ITEMS_ID, INUOPEUNI );
            UT_TRACE.TRACE( 'Costo Operativo del ítem =' || NUOPERAIUVALUE, 15 );
            IF OTBORDERITEMS( NUINDEX ).OUT_ = GE_BOCONSTANTS.CSBYES THEN
               NUOPERAIUORDER := NUOPERAIUORDER + NVL( NUOPERAIUVALUE, 0 );
            END IF;
            IF ( OR_BOORDERITEMS.FBLITEMWASINWARRANTY( OTBORDERITEMS( NUINDEX ), ITBACTIVITYITEMS ) OR ( RCITEMS.RECOVERY = GE_BOCONSTANTS.CSBNO ) ) THEN
               UT_TRACE.TRACE( 'El ítem tiene garantía => Precio=0', 15 );
               OTBORDERITEMS( NUINDEX ).TOTAL_PRICE := 0;
             ELSIF ( OTBORDERITEMS( NUINDEX ).OUT_ = GE_BOCONSTANTS.CSBNO ) THEN
               UT_TRACE.TRACE( 'El ítem no es de Salida => Costo=Precio=0', 15 );
               OTBORDERITEMS( NUINDEX ).VALUE := 0;
               OTBORDERITEMS( NUINDEX ).TOTAL_PRICE := 0;
             ELSE
               IF RCQUOTATION.QUOTATION_ID IS NOT NULL AND NULIQMETHOD IN ( OR_BOCONSTANTS.CNUMETODO_UNITARY_PRICE, OR_BOCONSTANTS.CNUMETODO_DELEGATE_PRICE ) THEN
                  OR_BOORDERITEMS.SETITEMVALUEBYQUOTATION( RCQUOTATION, OTBORDERITEMS( NUINDEX ).ITEMS_ID, NUTASKTYPEID, NVL( OTBORDERITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT, 0 ), NULIQMETHOD, RCORDER.EXEC_INITIAL_DATE, NUCOSTCOTIZEDVALITEM, NUAIUPERCENT );
                  NUAIUPERCENT := NVL( NUAIUPERCENT, 0 );
                  IF NULIQMETHOD = OR_BOCONSTANTS.CNUMETODO_DELEGATE_PRICE THEN
                     NUADMINAIUVALUE := NUCOSTCOTIZEDVALITEM * NUAIUPERCENT / 100;
                   ELSE
                     NUADMINAIUVALUE := 0;
                  END IF;
                  UT_TRACE.TRACE( 'Establece el precio del ítem dada la cotización. nuCostCotizedValItem: [' || TO_CHAR( NUCOSTCOTIZEDVALITEM ) || ']', 2 );
               END IF;
               IF NUCOSTCOTIZEDVALITEM IS NOT NULL THEN
                  UT_TRACE.TRACE( 'El ítem está cotizado.', 15 );
                  OTBORDERITEMS( NUINDEX ).VALUE := OTBORDERITEMS( NUINDEX ).VALUE + NVL( NUOPERAIUVALUE, 0 );
                  OTBORDERITEMS( NUINDEX ).TOTAL_PRICE := NUCOSTCOTIZEDVALITEM + NUADMINAIUVALUE;
                  IF OTBORDERITEMS( NUINDEX ).OUT_ = GE_BOCONSTANTS.CSBYES AND NULIQMETHOD = OR_BOCONSTANTS.CNUMETODO_DELEGATE_PRICE AND BLGENERATEAUI THEN
                     NUADMINAIUORDER := NVL( NUADMINAIUORDER, 0 ) + NVL( NUADMINAIUVALUE, 0 );
                  END IF;
                ELSE
                  UT_TRACE.TRACE( 'El ítem no está cotizado.', 15 );
                  IF NULIQMETHOD = OR_BOCONSTANTS.CNUMETODO_DELEGATE_PRICE THEN
                     NUADMINAIUVALUE := OR_BOITEMVALUE.FNUGETADMINAIU( OTBORDERITEMS( NUINDEX ).VALUE, NUOPERAIUVALUE );
                     IF OTBORDERITEMS( NUINDEX ).OUT_ = GE_BOCONSTANTS.CSBYES AND BLGENERATEAUI THEN
                        NUADMINAIUORDER := NVL( NUADMINAIUORDER, 0 ) + NVL( NUADMINAIUVALUE, 0 );
                     END IF;
                     OTBORDERITEMS( NUINDEX ).VALUE := OTBORDERITEMS( NUINDEX ).VALUE + NVL( NUOPERAIUVALUE, 0 );
                     OTBORDERITEMS( NUINDEX ).TOTAL_PRICE := ( NVL( NUADMINAIUVALUE, 0 ) + NVL( OTBORDERITEMS( NUINDEX ).VALUE, 0 ) );
                   ELSIF NULIQMETHOD = OR_BOCONSTANTS.CNUMETODO_UNITARY_PRICE THEN
                     OTBORDERITEMS( NUINDEX ).VALUE := OTBORDERITEMS( NUINDEX ).VALUE + NVL( NUOPERAIUVALUE, 0 );
                     OTBORDERITEMS( NUINDEX ).TOTAL_PRICE := OR_BOITEMVALUE.FNUGETITEMPRICE( OTBORDERITEMS( NUINDEX ).ITEMS_ID, INUOPEUNI, NUADDRESSID, NUTASKTYPEID ) * OTBORDERITEMS( NUINDEX ).LEGAL_ITEM_AMOUNT;
                   ELSIF ( NULIQMETHOD = OR_BOCONSTANTS.CNUMETODO_FIXED_PRICE ) THEN
                     OTBORDERITEMS( NUINDEX ).VALUE := OTBORDERITEMS( NUINDEX ).VALUE + NVL( NUOPERAIUVALUE, 0 );
                     OTBORDERITEMS( NUINDEX ).TOTAL_PRICE := 0;
                   ELSE
                     OTBORDERITEMS( NUINDEX ).VALUE := OTBORDERITEMS( NUINDEX ).VALUE + NVL( NUOPERAIUVALUE, 0 );
                     OTBORDERITEMS( NUINDEX ).TOTAL_PRICE := 0;
                  END IF;
                  UT_TRACE.TRACE( 'otbOrderItems(nuIndex).total_price ' || TO_CHAR( OTBORDERITEMS( NUINDEX ).TOTAL_PRICE ), 2 );
               END IF;
            END IF;
            OTBADITIONALDATA( NUINDEX ).SBQUANTITYCONTROL := SBQUANTITYCONTROL;
            OTBADITIONALDATA( NUINDEX ).SBCOSTMETHOD := SBCOSTMETHOD;
            OTBADITIONALDATA( NUINDEX ).SBRECOVERY := RCITEMS.RECOVERY;
            DAOR_ORDER_ITEMS.UPDRECORD( OTBORDERITEMS( NUINDEX ) );
         END LOOP;
         DAOR_ORDER.UPDOPERATIVE_AIU_VALUE( INUORDER, NUOPERAIUORDER );
         DAOR_ORDER.UPDADMIN_AIU_VALUE( INUORDER, NUADMINAIUORDER );
      END IF;
      UT_TRACE.TRACE( 'fin or_boitems.UpdItemsCost', 5 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         CLOSECURSOR;
         RAISE;
      WHEN OTHERS THEN
         CLOSECURSOR;
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END UPDITEMSCOST;
   FUNCTION FNUGETITEMPRICETOCOTI( INUITEMID IN GE_ITEMS.ITEMS_ID%TYPE, INUTASKTYPEID IN OR_TASK_TYPE.TASK_TYPE_ID%TYPE, NUORDERID IN OR_ORDER.ORDER_ID%TYPE, INUOPERUNIT IN OR_OPERATING_UNIT.OPERATING_UNIT_ID%TYPE := NULL, INUADDRESSID IN AB_ADDRESS.ADDRESS_ID%TYPE := NULL, INULIQUIDMETHOD IN PS_PACKAGE_TYPE.LIQUIDATION_METHOD%TYPE := NULL, ONUVALUE OUT OR_ORDER_ITEMS.VALUE%TYPE )
    RETURN GE_UNIT_COST_ITE_LIS.SALES_VALUE%TYPE
    IS
      NULIQMETHOD PS_PACKAGE_TYPE.LIQUIDATION_METHOD%TYPE;
      NUSALESVALUE GE_UNIT_COST_ITE_LIS.SALES_VALUE%TYPE;
      NUCONTRACTORID GE_CONTRATO.ID_CONTRATISTA%TYPE;
      NUCONTRACTID GE_CONTRATO.ID_CONTRATO%TYPE;
      NUBALANCE OR_OPE_UNI_ITEM_BALA.BALANCE%TYPE;
      NUBALANCEPRICE OR_OPE_UNI_ITEM_BALA.TOTAL_COSTS%TYPE;
      SBCOSTMETHOD GE_ITEM_CLASSIF.COST_METHOD%TYPE;
      SBQUANTITYCONTROL GE_ITEM_CLASSIF.QUANTITY_CONTROL%TYPE;
      NUOPERAIUVALUE OR_ORDER.OPERATIVE_AIU_VALUE%TYPE := 0;
      RCUNITCOSTLIST DAGE_LIST_UNITARY_COST.STYGE_LIST_UNITARY_COST;
      NUADMINAIUVALUE NUMBER;
    BEGIN
      UT_TRACE.TRACE( 'INICIO OR_BOItems.fnugetItemPriceToCoti. inuItemId: ' || TO_CHAR( INUITEMID ) || ' inuTaskTypeId: ' || TO_CHAR( INUTASKTYPEID ) || ' inuOperUnit: ' || TO_CHAR( INUOPERUNIT ) || ' inuAddressId: ' || TO_CHAR( INUADDRESSID ) || ' inuLiquidMethod: ' || TO_CHAR( INULIQUIDMETHOD ), 2 );
      DAGE_ITEMS.ACCKEY( INUITEMID );
      DAOR_TASK_TYPE.ACCKEY( INUTASKTYPEID );
      NULIQMETHOD := INULIQUIDMETHOD;
      IF ( INUOPERUNIT IS NOT NULL ) THEN
         NUCONTRACTORID := DAOR_OPERATING_UNIT.FNUGETCONTRACTOR_ID( INUOPERUNIT, 0 );
      END IF;
      IF ( NUCONTRACTORID IS NOT NULL ) THEN
         NUCONTRACTID := CT_BOCONTRACT.FNUGETCONTRACT( NUCONTRACTORID, INUTASKTYPEID, UT_DATE.FDTSYSDATE );
      END IF;
      IF ( NULIQMETHOD IS NOT NULL ) THEN
         UT_TRACE.TRACE( 'nuLiqMethod: ' || TO_CHAR( NULIQMETHOD ) || ' nuContractId: ' || TO_CHAR( NUCONTRACTID ) || ' nuContractorId: ' || TO_CHAR( NUCONTRACTORID ), 2 );
         OR_BOITEMVALUE.GETITEMVALUEANDCOSTMETHOD( INUITEMID, 1, INUOPERUNIT, UT_DATE.FDTSYSDATE, GE_BOCONSTANTS.CSBYES, NUBALANCE, NUBALANCEPRICE, ONUVALUE, SBCOSTMETHOD, SBQUANTITYCONTROL, GE_BOCONSTANTS.CSBNO, NULL, NUCONTRACTORID, NUCONTRACTID, INUADDRESSID );
         NUOPERAIUVALUE := OR_BOITEMVALUE.FNUGETOPERATIVEAIU( NUORDERID, ONUVALUE, INUITEMID, INUOPERUNIT );
         IF NULIQMETHOD = OR_BOCONSTANTS.CNUMETODO_DELEGATE_PRICE THEN
            NUADMINAIUVALUE := OR_BOITEMVALUE.FNUGETADMINAIU( ONUVALUE, NUOPERAIUVALUE );
            ONUVALUE := ONUVALUE + NUOPERAIUVALUE;
            NUSALESVALUE := ONUVALUE + NUADMINAIUVALUE;
          ELSIF NULIQMETHOD = OR_BOCONSTANTS.CNUMETODO_UNITARY_PRICE THEN
            ONUVALUE := ONUVALUE + NUOPERAIUVALUE;
            NUSALESVALUE := OR_BOITEMVALUE.FNUGETITEMPRICE( INUITEMID, INUOPERUNIT, INUADDRESSID, INUTASKTYPEID );
          ELSE
            ONUVALUE := ONUVALUE + NUOPERAIUVALUE;
            NUSALESVALUE := 0;
         END IF;
       ELSE
         ONUVALUE := NULL;
         NUSALESVALUE := NULL;
      END IF;
      UT_TRACE.TRACE( 'FIN OR_BOItems.fnugetItemPriceToCoti. nuSalesValue: ' || TO_CHAR( NUSALESVALUE ) || ' onuValue: ' || TO_CHAR( ONUVALUE ), 2 );
      RETURN NUSALESVALUE;
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END FNUGETITEMPRICETOCOTI;
END OR_BOITEMS;
/


