
CREATE OR REPLACE PACKAGE BODY WF_BOCNFGENERALS IS
   CSBVERSION CONSTANT VARCHAR2( 250 ) := 'SAO92431';
   FUNCTION FSBVERSION
    RETURN VARCHAR2
    IS
    BEGIN
      RETURN CSBVERSION;
   END;
   PROCEDURE GETGEENTITYS( ORFDATASOURCE OUT CONSTANTS.TYREFCURSOR )
    IS
    BEGIN
      UT_TRACE.TRACE( 'Se inicia el metodo WF_BOCNFGENERALS.GetGEEntitys', 8 );
      WF_BCCNFGE_ENTITY.GETGEENTITYS( ORFDATASOURCE );
      UT_TRACE.TRACE( 'Se finaliza el metodo WF_BOCNFGENERALS.GetGEEntitys', 8 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   PROCEDURE GETMODULES( ORFDATASOURCE OUT CONSTANTS.TYREFCURSOR )
    IS
    BEGIN
      UT_TRACE.TRACE( 'Se inicia el metodo WF_BOCNFGENERALS.GetModules', 8 );
      WF_BCCNFGE_MODULE.GETMODULES( ORFDATASOURCE );
      UT_TRACE.TRACE( 'Se finaliza el metodo WF_BOCNFGENERALS.GetModules', 8 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   PROCEDURE GETNOTIFICATIONSBYMODULEID( INUMODULEID IN GE_NOTIFICATION.TARGET_MODULE_ID%TYPE, ORFDATASOURCE OUT CONSTANTS.TYREFCURSOR )
    IS
    BEGIN
      UT_TRACE.TRACE( 'Se inicia el metodo WF_BOCNFGENERALS.GetNotificationsbyModuleId(' || INUMODULEID || ')', 8 );
      WF_BCCNFGE_NOTIFICATION.GETNOTIFICATIONSBYMODULEID( INUMODULEID, ORFDATASOURCE );
      UT_TRACE.TRACE( 'Se finaliza el metodo WF_BOCNFGENERALS.GetNotificationsbyModuleId(' || INUMODULEID || ')', 8 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   PROCEDURE GETACTIONSBYMODULEID( INUMODULEID IN GE_ACTION_MODULE.MODULE_ID%TYPE, ORFDATASOURCE OUT CONSTANTS.TYREFCURSOR )
    IS
    BEGIN
      UT_TRACE.TRACE( 'Se inicia el metodo WF_BOCNFGENERALS.GetActionsbyModuleId(' || INUMODULEID || ')', 8 );
      WF_BCCNFGE_ACTION_MODULE.GETACTIONSBYMODULEID( INUMODULEID, ORFDATASOURCE );
      UT_TRACE.TRACE( 'Se finaliza el metodo WF_BOCNFGENERALS.GetActionsbyModuleId(' || INUMODULEID || ')', 8 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   PROCEDURE GETPRIORITIES( ORFDATASOURCE OUT CONSTANTS.TYREFCURSOR )
    IS
    BEGIN
      UT_TRACE.TRACE( 'Se inicia el metodo WF_BOCNFGENERALS.GetPriorities', 8 );
      ORFDATASOURCE := DAGE_PRIORITY.FRFGETRECORDS;
      UT_TRACE.TRACE( 'Se finaliza el metodo WF_BOCNFGENERALS.GetPriorities', 8 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
   PROCEDURE GETCOMMENTCLASS( ORFDATASOURCE OUT CONSTANTS.TYREFCURSOR )
    IS
    BEGIN
      UT_TRACE.TRACE( 'Se inicia el metodo WF_BOCNFGENERALS.GetCommentClass', 8 );
      ORFDATASOURCE := DAGE_COMMENT_CLASS.FRFGETRECORDS;
      UT_TRACE.TRACE( 'Se finaliza el metodo WF_BOCNFGENERALS.GetCommentClass', 8 );
    EXCEPTION
      WHEN EX.CONTROLLED_ERROR THEN
         RAISE EX.CONTROLLED_ERROR;
      WHEN OTHERS THEN
         ERRORS.SETERROR;
         RAISE EX.CONTROLLED_ERROR;
   END;
END WF_BOCNFGENERALS;
/


