PROMPT Crea Sinonimo a paquete LDC_CERTIFICADOS_OIA para LDCCREATETRAMITERECONEXIONXML
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM ADM_PERSON.LDC_CERTIFICADOS_OIA FOR LDC_CERTIFICADOS_OIA';
END;
/