INSERT INTO ldc_procedimiento_obj
  (TASK_TYPE_ID, CAUSAL_ID, PROCEDIMIENTO, DESCRIPCION, ORDEN_EJEC, ACTIVO)
VALUES
  (12149,
  9944,
  'LDCI_CRE_CAR_AVA_OBR_VEN_CON',
  'CREAR CARGOS AVANCE OBRA VENTAS CONSTRUCTORAS',
  1,
  'S');
INSERT INTO ldc_procedimiento_obj
  (TASK_TYPE_ID, CAUSAL_ID, PROCEDIMIENTO, DESCRIPCION, ORDEN_EJEC, ACTIVO)
VALUES
  (12150,
  9944,
  'LDCI_CRE_CAR_AVA_OBR_VEN_CON',
  'CREAR CARGOS AVANCE OBRA VENTAS CONSTRUCTORAS',
  1,
  'S');
INSERT INTO ldc_procedimiento_obj
  (TASK_TYPE_ID, CAUSAL_ID, PROCEDIMIENTO, DESCRIPCION, ORDEN_EJEC, ACTIVO)
VALUES
  (12162,
  9944,
  'LDCI_CRE_CAR_AVA_OBR_VEN_CON',
  'CREAR CARGOS AVANCE OBRA VENTAS CONSTRUCTORAS',
  1,
  'S');