Prompt Creando el parametro HORA_NO_REGISTRO_NEGO
BEGIN
MERGE INTO OPEN.PARAMETROS A USING
 (SELECT
  'HORA_NO_REGISTRO_NEGO' as CODIGO,
  'Hora desde no se debe permitir registro de negociaciones por las  24 horas siguientes' as DESCRIPCION,
  22 as VALOR_NUMERICO,
  NULL as VALOR_CADENA,
  NULL as VALOR_FECHA,
  5 as PROCESO,
  'A' as ESTADO,
  'S' as OBLIGATORIO,
  TO_DATE(sysdate, 'DD/MM/YYYY HH24:MI:SS') as FECHA_CREACION,
  NULL as FECHA_ACTUALIZACION,
  'OPEN' as USUARIO,
  'PMVM266' as TERMINAL
  FROM DUAL) B
ON (A.CODIGO = B.CODIGO)
WHEN NOT MATCHED THEN 
INSERT (
  CODIGO, DESCRIPCION, VALOR_NUMERICO, VALOR_CADENA, VALOR_FECHA, 
  PROCESO, ESTADO, OBLIGATORIO, FECHA_CREACION, FECHA_ACTUALIZACION, 
  USUARIO, TERMINAL)
VALUES (
  B.CODIGO, B.DESCRIPCION, B.VALOR_NUMERICO, B.VALOR_CADENA, B.VALOR_FECHA, 
  B.PROCESO, B.ESTADO, B.OBLIGATORIO, B.FECHA_CREACION, B.FECHA_ACTUALIZACION, 
  B.USUARIO, B.TERMINAL)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPCION = B.DESCRIPCION,
  A.VALOR_NUMERICO = B.VALOR_NUMERICO,
  A.VALOR_CADENA = B.VALOR_CADENA,
  A.VALOR_FECHA = B.VALOR_FECHA,
  A.PROCESO = B.PROCESO,
  A.ESTADO = B.ESTADO,
  A.OBLIGATORIO = B.OBLIGATORIO,
  A.FECHA_CREACION = B.FECHA_CREACION,
  A.FECHA_ACTUALIZACION = B.FECHA_ACTUALIZACION,
  A.USUARIO = B.USUARIO,
  A.TERMINAL = B.TERMINAL;

COMMIT;
END;
/