SELECT * FROM  OPEN.gi_comp_attribs
WHERE   composition_id in
(
SELECT  composition_id
FROM    OPEN.gi_config_comp
WHERE   config_id =
(
SELECT  config_id
FROM    OPEN.gi_config
WHERE   config_type_id = 4
AND     entity_root_id = 2012
AND     external_root_id = 100271
)
);
SELECT  *
FROM    OPEN.gi_config
WHERE   config_type_id = 4
AND     entity_root_id = 2012
AND     external_root_id = 100271;

SELECT  *
FROM    OPEN.GR_CONFIG_EXPRESSION, OPEN.PS_PACKAGE_ATTRIBS, OPEN.GE_ACTION_MODULE
WHERE   PS_PACKAGE_ATTRIBS.package_type_id = 100271
AND     (GR_CONFIG_EXPRESSION.config_expression_id = PS_PACKAGE_ATTRIBS.init_expression_id
OR      GR_CONFIG_EXPRESSION.config_expression_id = PS_PACKAGE_ATTRIBS.valid_expression_id
OR      GR_CONFIG_EXPRESSION.config_expression_id = GE_ACTION_MODULE.config_expression_id)
;
--Obtiene Objetos Asociados a GE_ATTRIBUTES
SELECT  *
FROM    OPEN.GR_CONFIG_EXPRESSION, OPEN.GE_ATTRIBUTES, OPEN.PS_PACK_TYPE_PARAM
WHERE   PS_PACK_TYPE_PARAM.package_type_id = 100271
AND     GE_ATTRIBUTES.attribute_id = PS_PACK_TYPE_PARAM.attribute_id
AND     GR_CONFIG_EXPRESSION.config_expression_id = GE_ATTRIBUTES.valid_expression
;
--Obtiene Objetos Asociados a PS_WHEN_PACKAGE
SELECT  *
FROM    OPEN.GR_CONFIG_EXPRESSION, OPEN.PS_WHEN_PACKAGE, OPEN.PS_PACKAGE_EVENTS
WHERE   PS_PACKAGE_EVENTS.package_type_id = 100271
AND     PS_PACKAGE_EVENTS.package_events_id = PS_WHEN_PACKAGE.package_event_id
AND     GR_CONFIG_EXPRESSION.config_expression_id = PS_WHEN_PACKAGE.config_expression_id
;
--Obtiene Objetos Asociados a OPEN.PS_PACKAGE_ACTION
SELECT  *
FROM    OPEN.GR_CONFIG_EXPRESSION, OPEN.PS_PACKAGE_ACTION
WHERE   PS_PACKAGE_ACTION.package_type_id = 100271
AND     GR_CONFIG_EXPRESSION.config_expression_id = PS_PACKAGE_ACTION.EXP_EXEC_ID
;

 SELECT * FROM OPEN.GR_CONFIG_EXPRESSION WHERE (CONFIG_EXPRESSION_ID) in (SELECT CONFIG_EXPRESSION_ID FROM OPEN.GE_ACTION_MODULE WHERE (ACTION_ID) in (SELECT ACTION_REGIS_EXEC FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));

  SELECT * FROM OPEN.GE_ACTION_MODULE WHERE (ACTION_ID) in (SELECT ACTION_REGIS_EXEC FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271);

   SELECT * FROM OPEN.GR_CONFIG_EXPRESSION WHERE (CONFIG_EXPRESSION_ID) in (SELECT INIT_EXPRESSION_ID FROM OPEN.PS_PACKAGE_ATTRIBS WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));
 SELECT * FROM OPEN.GR_CONFIG_EXPRESSION WHERE (CONFIG_EXPRESSION_ID) in (SELECT VALID_EXPRESSION_ID FROM OPEN.PS_PACKAGE_ATTRIBS WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));

 SELECT * FROM OPEN.GR_CONFIG_EXPRESSION WHERE (CONFIG_EXPRESSION_ID) in (SELECT VALID_EXPRESSION_ID FROM OPEN.PS_PACKAGE_ATTRIBS WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));

  SELECT * FROM OPEN.GE_STATEMENT WHERE (STATEMENT_ID) in (SELECT STATEMENT_ID FROM OPEN.PS_PACKAGE_ATTRIBS WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));

  SELECT *
FROM OPEN.PS_PACKAGE_ATTRIBS WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271);

 SELECT * FROM OPEN.GR_CONFIG_EXPRESSION WHERE (CONFIG_EXPRESSION_ID) in (SELECT VALID_EXPRESSION FROM OPEN.GE_ATTRIBUTES WHERE (ATTRIBUTE_ID) in (SELECT ATTRIBUTE_ID FROM OPEN.PS_PACK_TYPE_PARAM WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271)));

  SELECT * FROM OPEN.GE_ATTRIBUTES WHERE (ATTRIBUTE_ID) in (SELECT ATTRIBUTE_ID FROM OPEN.PS_PACK_TYPE_PARAM WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));

  SELECT *
FROM OPEN.PS_PACK_TYPE_PARAM WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271);

 SELECT * FROM OPEN.SERVICIO WHERE (SERVCODI) in (SELECT PRODUCT_TYPE_ID FROM OPEN.PS_PACKAGE_UNITTYPE WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));

 SELECT *
FROM OPEN.PS_PACKAGE_UNITTYPE WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271);

SELECT *
FROM OPEN.PS_PACK_TYPE_VALID WHERE (TAG_NAME) in (SELECT TAG_NAME FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271);

SELECT *
FROM OPEN.WF_ATTRIBUTES_EQUIV WHERE (VALUE_1) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271) AND INTERFACE_CONFIG_ID = 21;
 SELECT rowid FROM OPEN.GE_ACTION_MODULE WHERE (ACTION_ID) in (SELECT TARGET_ACTION_ID FROM OPEN.PS_PACKAGE_ACTION WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));

 SELECT * FROM OPEN.GR_CONFIG_EXPRESSION WHERE (CONFIG_EXPRESSION_ID) in (SELECT CONFIG_EXPRESSION_ID FROM OPEN.PS_WHEN_PACKAGE WHERE (PACKAGE_EVENT_ID) in (SELECT PACKAGE_EVENTS_ID FROM OPEN.PS_PACKAGE_EVENTS WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271)));

 SELECT *
FROM OPEN.PS_WHEN_PACKAGE WHERE (PACKAGE_EVENT_ID) in (SELECT PACKAGE_EVENTS_ID FROM OPEN.PS_PACKAGE_EVENTS WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));

SELECT *
FROM OPEN.PS_PACKAGE_EVENTS WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271);

 SELECT * FROM OPEN.GR_CONFIG_EXPRESSION WHERE (CONFIG_EXPRESSION_ID) in (SELECT CONFIG_EXPRESSION_ID FROM OPEN.GE_ACTION_MODULE WHERE (ACTION_ID) in (SELECT ACTION_ASSIGN_ID FROM OPEN.PS_PRODUCT_MOTIVE WHERE (PRODUCT_MOTIVE_ID) in (SELECT PRODUCT_MOTIVE_ID FROM OPEN.PS_PRD_MOTIV_PACKAGE WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271))));

  SELECT * FROM OPEN.GE_ACTION_MODULE WHERE (ACTION_ID) in (SELECT ACTION_ASSIGN_ID FROM OPEN.PS_PRODUCT_MOTIVE WHERE (PRODUCT_MOTIVE_ID) in (SELECT PRODUCT_MOTIVE_ID FROM OPEN.PS_PRD_MOTIV_PACKAGE WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271)));

   SELECT * FROM OPEN.SERVICIO WHERE (SERVCODI) in (SELECT PRODUCT_TYPE_ID FROM OPEN.PS_PRODUCT_MOTIVE WHERE (PRODUCT_MOTIVE_ID) in (SELECT PRODUCT_MOTIVE_ID FROM OPEN.PS_PRD_MOTIV_PACKAGE WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271)));

    SELECT * FROM OPEN.PS_MOTIVE_TYPE WHERE (MOTIVE_TYPE_ID) in (SELECT MOTIVE_TYPE_ID FROM OPEN.PS_PRODUCT_MOTIVE WHERE (PRODUCT_MOTIVE_ID) in (SELECT PRODUCT_MOTIVE_ID FROM OPEN.PS_PRD_MOTIV_PACKAGE WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271)));

   SELECT * FROM OPEN.PS_PRODUCT_MOTIVE WHERE (PRODUCT_MOTIVE_ID) in (SELECT PRODUCT_MOTIVE_ID FROM OPEN.PS_PRD_MOTIV_PACKAGE WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));

   SELECT *
FROM OPEN.PS_PRD_MOTIV_PACKAGE WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271);

 SELECT * FROM OPEN.GR_CONFIG_EXPRESSION WHERE (CONFIG_EXPRESSION_ID) in (SELECT EXP_EXEC_ID FROM OPEN.PS_PACKAGE_ACTION WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));

  SELECT * FROM OPEN.GR_CONFIG_EXPRESSION WHERE (CONFIG_EXPRESSION_ID) in (SELECT CONFIG_EXPRESSION_ID FROM OPEN.GE_ACTION_MODULE WHERE (ACTION_ID) in (SELECT SOURCE_ACTION_ID FROM OPEN.PS_PACKAGE_ACTION WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271)));

   SELECT * FROM OPEN.GE_ACTION_MODULE WHERE (ACTION_ID) in (SELECT SOURCE_ACTION_ID FROM OPEN.PS_PACKAGE_ACTION WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));

    SELECT * FROM OPEN.GR_CONFIG_EXPRESSION WHERE (CONFIG_EXPRESSION_ID) in (SELECT CONFIG_EXPRESSION_ID FROM OPEN.GE_ACTION_MODULE WHERE (ACTION_ID) in (SELECT TARGET_ACTION_ID FROM OPEN.PS_PACKAGE_ACTION WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271)));

   SELECT * FROM OPEN.GE_ACTION_MODULE WHERE (ACTION_ID) in (SELECT TARGET_ACTION_ID FROM OPEN.PS_PACKAGE_ACTION WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271));
SELECT *
FROM OPEN.PS_PACKAGE_ACTION WHERE (PACKAGE_TYPE_ID) in (SELECT PACKAGE_TYPE_ID FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271);
SELECT *
FROM OPEN.PS_PACKAGE_TYPE WHERE PACKAGE_TYPE_ID=100271;
SELECT  *
FROM    OPEN.GR_CONFIG_EXPRESSION, OPEN.PS_WHEN_MOTIVE, OPEN.PS_PROD_MOTI_EVENTS, OPEN.PS_PRODUCT_MOTIVE
WHERE   OPEN.PS_PRODUCT_MOTIVE.product_motive_id in
(
select product_motive_id
FROM OPEN.ps_prd_motiv_package
WHERE PACKAGE_type_id = 100271
)
AND     PS_PROD_MOTI_EVENTS.product_motive_id = PS_PRODUCT_MOTIVE.product_motive_id
AND     ps_when_motive.prod_moti_events_id = PS_PROD_MOTI_EVENTS.prod_moti_events_id
AND     ps_when_motive.config_expression_id = GR_CONFIG_EXPRESSION.config_expression_id
;
--Obtiene Objetos asociados a GE_ATTRIBUTES
SELECT  *
FROM    OPEN.GR_CONFIG_EXPRESSION, OPEN.GE_ATTRIBUTES, OPEN.PS_PROD_MOTI_PARAM, OPEN.PS_PRODUCT_MOTIVE
WHERE   OPEN.PS_PRODUCT_MOTIVE.product_motive_id in
(
select product_motive_id
FROM OPEN.ps_prd_motiv_package
WHERE PACKAGE_type_id = 100271
)
AND     PS_PROD_MOTI_PARAM.product_motive_id = PS_PRODUCT_MOTIVE.product_motive_id
AND     PS_PROD_MOTI_PARAM.attribute_id = GE_ATTRIBUTES.attribute_id
AND     GR_CONFIG_EXPRESSION.config_expression_id = ge_Attributes.valid_expression
;
--Obtiene Objetos asociados a PS_PROD_MOTI_ATTRIB
SELECT  *
FROM    OPEN.GR_CONFIG_EXPRESSION, OPEN.PS_PROD_MOTI_ATTRIB, OPEN.PS_PRODUCT_MOTIVE
WHERE   PS_PRODUCT_MOTIVE.product_motive_id in
(
select product_motive_id
FROM OPEN.ps_prd_motiv_package
WHERE PACKAGE_type_id = 100271
)
AND     OPEN.PS_PRODUCT_MOTIVE.product_motive_id = PS_PROD_MOTI_ATTRIB.product_motive_id
AND     (GR_CONFIG_EXPRESSION.config_expression_id = PS_PROD_MOTI_ATTRIB.init_expression_id
OR       GR_CONFIG_EXPRESSION.config_expression_id = PS_PROD_MOTI_ATTRIB.valid_expression_id)
;
--Obtiene Objetos asociados a PS_MOTI_COMP_ATTRIBS
SELECT  *
FROM    OPEN.GR_CONFIG_EXPRESSION, OPEN.PS_MOTI_COMP_ATTRIBS,
        OPEN.PS_PROD_MOTIVE_COMP, OPEN.PS_PRODUCT_MOTIVE
WHERE   PS_PRODUCT_MOTIVE.product_motive_id in
(
select product_motive_id
FROM OPEN.ps_prd_motiv_package
WHERE PACKAGE_type_id = 100271
)
AND     PS_PRODUCT_MOTIVE.product_motive_id = PS_PROD_MOTIVE_COMP.product_motive_id
AND     PS_PROD_MOTIVE_COMP.prod_motive_comp_id = PS_MOTI_COMP_ATTRIBS.prod_motive_comp_id
AND     (PS_MOTI_COMP_ATTRIBS.init_expression_id = GR_CONFIG_EXPRESSION.config_expression_id
OR       PS_MOTI_COMP_ATTRIBS.valid_expression_id = GR_CONFIG_EXPRESSION.config_expression_id)
;
--Obtiene Objetos asociados a PS_WHEN_MOTI_COMPON
SELECT  *
FROM    OPEN.GR_CONFIG_EXPRESSION, OPEN.PS_WHEN_MOTI_COMPON, OPEN.PS_MOTI_COMPON_EVENT,
        OPEN.PS_PROD_MOTIVE_COMP, OPEN.PS_PRODUCT_MOTIVE
WHERE   PS_PRODUCT_MOTIVE.product_motive_id in
(
select product_motive_id
FROM OPEN.ps_prd_motiv_package
WHERE PACKAGE_type_id = 100271
)
AND     PS_PRODUCT_MOTIVE.product_motive_id = PS_PROD_MOTIVE_COMP.product_motive_id
AND     PS_PROD_MOTIVE_COMP.prod_motive_comp_id = PS_MOTI_COMPON_EVENT.prod_motive_comp_id
AND     PS_MOTI_COMPON_EVENT.moti_compon_event_id = PS_WHEN_MOTI_COMPON.moti_compon_event_id
AND     PS_WHEN_MOTI_COMPON.config_expression_id = GR_CONFIG_EXPRESSION.config_expression_id
;
--Obtiene Objetos Asociados a PS_PROD_MOTI_ACTION 
SELECT  *
FROM    OPEN.GR_CONFIG_EXPRESSION, OPEN.PS_PROD_MOTI_ACTION
WHERE   PS_PROD_MOTI_ACTION.product_motive_id in
(
select product_motive_id
FROM OPEN.ps_prd_motiv_package
WHERE PACKAGE_type_id = 100271
)
AND     ( GR_CONFIG_EXPRESSION.config_expression_id = PS_PROD_MOTI_ACTION.PRE_EXP_EXEC_ID OR 
          GR_CONFIG_EXPRESSION.config_expression_id = PS_PROD_MOTI_ACTION.POS_EXP_EXEC_ID ) 
;



 WITH BASE AS(
            SELECT GI_CONFIG.CONFIG_ID, GI_CONFIG.EXTERNAL_ROOT_ID
            FROM "OPEN".GI_CONFIG
            WHERE  GI_CONFIG.ENTITY_ROOT_ID = 2012
            AND    GI_CONFIG.CONFIG_TYPE_ID=4)
                
            SELECT * 
                FROM "OPEN".GI_FRAME FR
                INNER JOIN "OPEN".GI_CONFIG_COMP CC ON CC.COMPOSITION_ID=FR.COMPOSITION_ID
                WHERE (CC.CONFIG_ID) IN (SELECT CONFIG_ID
                                                FROM BASE
                                                WHERE EXTERNAL_ROOT_ID = &tramite)
                    AND CONFIG_ID  NOT IN (SELECT CONFIG_ID
                                                FROM BASE
                                                WHERE  EXTERNAL_ROOT_ID = 587)
                    AND FR.ORDER_VIEW=1;

select cmp.*, att.TECHNICAL_NAME, ent.name_
from open.gi_comp_attribs cmp
left join open.ge_entity_attributes att
on att.ENTITY_ATTRIBUTE_ID = cmp.ENTITY_ATTRIBUTE_ID
left join open.ge_entity ent
on ent.ENTITY_ID = att.ENTITY_ID

where
      cmp.COMPOSITION_ID in (1026250)                    ;





      select a.package_type_id Tipo_Solicitud,
       a.process_sequence Secuencia,
       a.required Requerido,
       a.display_name Nombre,
       a.tag_name Tag,
       a.attri_technical_name Nombre_XML,
       a.included_xml Incluido_XML,
       a.init_expression_id Regla_Inicializacion,
       (select ge.entity_id || ' - ' || ge.name_
          from ge_entity ge
         where ge.entity_id = a.entity_id) Endidad,
       (select gea.entity_attribute_id || ' - ' || gea.display_name
          from ge_entity_attributes gea
         where gea.entity_attribute_id = a.entity_attribute_id) Atributo_Entidad,
       a.mirror_enti_attrib  || ' - ' || ae.display_name Atributo_espejo_nombre,
       a.mirror_enti_attrib  || ' - ' || ae.technical_name Atributo_espejo_tecnico,
       ae.entity_id  || ' - ' || ee.name_ Entidad_espejo
  from open.ps_package_attribs a
 inner join open.gr_config_expression c
    on c.config_expression_id(+) = a.init_expression_id
 left join ge_entity_attributes ae
    on ae.entity_attribute_id = a.mirror_enti_attrib 
 left join ge_entity ee
    on ee.entity_id = ae.entity_id
 where package_type_id = &solicitud
--and a.required = 'Y'
 order by a.process_sequence