select * from orm.OPT_CONSULTA_TAREASPOST_PROG where id_usuario='DIASAL';
select * from orm.OPT_CONSULTA_TAREASPOST where id_usuario='DIASAL';
SELECT *
FROM ORM.OPT_CONSULTA_EJECS
WHERE ID_CONSULTA=3
