DECLARE
    nuConta NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO nuConta
    FROM DBA_OBJECTS o
    WHERE UPPER(o.OBJECT_NAME) = UPPER('trgbidurAB_PREMISE')
          AND o.OWNER = 'PERSONALIZACIONES'
          AND o.OBJECT_TYPE <> 'SYNONYM';

    IF nuConta > 0 THEN
        EXECUTE IMMEDIATE 'DROP TRIGGER PERSONALIZACIONES.trgbidurAB_PREMISE';
    END IF;
END;
/
PROMPT "Trigger trgbidurAB_PREMISE original borrado";
