Prompt "Ingresando CLASE_ITEMS_DE_MATERIAL en PARAMETROS"
BEGIN

    MERGE INTO OPEN.PARAMETROS A USING
    (SELECT
    'USUARIO_EXCL_VAL_EMP_FUNC_CONTR' as CODIGO,
    'USUARIOS EXCLUIDOS DE LA VALIDACION DE LA EMPRESA DEL CONTRATO' as DESCRIPCION,
    NULL as VALOR_NUMERICO,
    '1,5607' as VALOR_CADENA,
    NULL as VALOR_FECHA,
    5 as PROCESO,
    'A' as ESTADO,
    'S' as OBLIGATORIO,
    TO_DATE('28/03/2025 08:08:18', 'DD/MM/YYYY HH24:MI:SS') as FECHA_CREACION,
    TO_DATE('28/03/2025 08:08:30', 'DD/MM/YYYY HH24:MI:SS') as FECHA_ACTUALIZACION,
    'OPEN' as USUARIO,
    'PMVM115' as TERMINAL
    FROM DUAL) B
    ON (A.CODIGO = B.CODIGO)
    WHEN NOT MATCHED THEN 
    INSERT (
    CODIGO, DESCRIPCION, VALOR_NUMERICO, VALOR_CADENA, VALOR_FECHA, 
    PROCESO, ESTADO, OBLIGATORIO, FECHA_CREACION, FECHA_ACTUALIZACION, 
    USUARIO, TERMINAL)
    VALUES (
    B.CODIGO, B.DESCRIPCION, B.VALOR_NUMERICO, B.VALOR_CADENA, B.VALOR_FECHA, 
    B.PROCESO, B.ESTADO, B.OBLIGATORIO, B.FECHA_CREACION, B.FECHA_ACTUALIZACION, 
    B.USUARIO, B.TERMINAL)
    WHEN MATCHED THEN
    UPDATE SET 
    A.DESCRIPCION = B.DESCRIPCION,
    A.VALOR_NUMERICO = B.VALOR_NUMERICO,
    A.VALOR_CADENA = B.VALOR_CADENA,
    A.VALOR_FECHA = B.VALOR_FECHA,
    A.PROCESO = B.PROCESO,
    A.ESTADO = B.ESTADO,
    A.OBLIGATORIO = B.OBLIGATORIO,
    A.FECHA_CREACION = B.FECHA_CREACION,
    A.FECHA_ACTUALIZACION = B.FECHA_ACTUALIZACION,
    A.USUARIO = B.USUARIO,
    A.TERMINAL = B.TERMINAL;

    COMMIT;
    
END;
/
