SET SERVEROUTPUT ON;
DECLARE
		ICLXMLSEARCHTRANSIT   CLOB;
		OCLXMLTRANSITITEMS    CLOB;
		ONUERRORCODE          OPEN.GE_ERROR_LOG.ERROR_LOG_ID%TYPE;
		OSBERRORMESSAGE       OPEN.GE_ERROR_LOG.DESCRIPTION%TYPE;					
BEGIN          
/*1773,1774,1775,1931,1932,1933*/

          ICLXMLSEARCHTRANSIT := '<?xml version="1.0"?><SEARCH_TRANSIT_ITEM><OPERATING_UNIT>1931</OPERATING_UNIT></SEARCH_TRANSIT_ITEM>';
          dbms_output.put_line('[ICLXMLSEARCHTRANSIT]' || ICLXMLSEARCHTRANSIT); 
					"OPEN".OS_GET_TRANSIT_ITEM(ICLXMLSEARCHTRANSIT, OCLXMLTRANSITITEMS, ONUERRORCODE, OSBERRORMESSAGE);
          dbms_output.put_line('[ONUERRORCODE]' || ONUERRORCODE); 
          dbms_output.put_line('[OSBERRORMESSAGE]' || OSBERRORMESSAGE); 
          
          dbms_output.put_line('[OCLXMLTRANSITITEMS]' || OCLXMLTRANSITITEMS);           
          
END;
/