DECLARE
    CURSOR cuExisteCol IS
    SELECT COUNT(1)
    FROM DBA_TAB_COLUMNS TC
    WHERE TC.TABLE_NAME = 'LDC_RESUINSP'
      AND TC.COLUMN_NAME = 'ACTIVIDAD_VALIDACION';

    nuExiste    number;
BEGIN
    OPEN cuExisteCol;
    FETCH cuExisteCol INTO nuExiste;
    CLOSE cuExisteCol;

    IF nuExiste = 0 THEN
        EXECUTE IMMEDIATE 'alter table LDC_RESUINSP add ACTIVIDAD_VALIDACION NUMBER(15)';
        EXECUTE IMMEDIATE 'comment on column LDC_RESUINSP.ACTIVIDAD_VALIDACION is ''ACTIVIDAD A GENERAR PARA PAGO DE VALIDACION DEL DOCUMENTO''';
    END IF;
END;
/