select c.copaidcp,
       c.copaidct,
       c.copatico,
       tc.descripcion,
       c.copafeco,
       c.copabaad,
       ba.descripcion,
       c.copafepr,
       c.copafega,
       c.copaesta,
       decode(c.copaesta,
              'R',
              'Registrado',
              'D',
              'Pre acta generada',
              'P',
              'En proceso',
              'E',
              'Exitoso',
              'X',
              'Con error') desc_estado,
       c.coparesu,
       c.copacoel,
       c.copacoin,
       c.copacoco,
       c.copauser,
       c.copafcon,
       c.copaterm
  from ldc_coprauac c
  inner join ge_base_administra  ba on ba.id_base_administra  = c.copabaad
  left join ge_tipo_contrato  tc on tc.id_tipo_contrato  = c.copatico
 order by c.copafcon desc
