CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_LD_QUOTA_BY_SUBSC AFTER INSERT OR UPDATE OR DELETE ON LD_QUOTA_BY_SUBSC
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

QUOTA_BY_SUBSC_ID NUMBER(15);
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  QUOTA_BY_SUBSC_ID := :new.QUOTA_BY_SUBSC_ID;
  OPERATION := 'I';
ELSIF UPDATING THEN
  QUOTA_BY_SUBSC_ID := :new.QUOTA_BY_SUBSC_ID;
  OPERATION := 'U';
ELSE
  QUOTA_BY_SUBSC_ID := :old.QUOTA_BY_SUBSC_ID;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_LD_QUOTA_BY_SUBSC (
  QUOTA_BY_SUBSC_ID,
  OPERATION
)
VALUES (
  QUOTA_BY_SUBSC_ID,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EX.CONTROLLED_ERROR;
END;
/
