PACKAGE OR_UIORPAP
IS

    




















































    
    SUBTYPE STYNUMBER   IS NUMBER;


    
    
    
   
    




    FUNCTION FSBVERSION
    RETURN UT_DATATYPES.STYSAOVERSION;

	
	





    PROCEDURE LEGALIZEBYFILE;
    
END OR_UIORPAP;

PACKAGE BODY OR_UIORPAP
IS

    






















































    
    
    
    CSBVERSION                CONSTANT UT_DATATYPES.STYSAOVERSION    := 'SAO557133';

    
    
    
    
    CNUERR_FINAL_DATE         CONSTANT GE_MESSAGE.MESSAGE_ID%TYPE    := 811;

    
    CNUERR_PASS               CONSTANT GE_MESSAGE.MESSAGE_ID%TYPE    := 7971;

    
    CNUSUCCESSPROCESS         CONSTANT GE_MESSAGE.MESSAGE_ID%TYPE    := 919440;
    CNUTHREADS                CONSTANT STYNUMBER                     := 1;
    
    
    CNUERR_ARCH_PROCES	      CONSTANT    GE_MESSAGE.MESSAGE_ID%TYPE := 900809;

    
    
    

   
    














    FUNCTION FSBVERSION
    RETURN UT_DATATYPES.STYSAOVERSION
    IS
    BEGIN
        RETURN CSBVERSION;
    END FSBVERSION;
    
    





























    PROCEDURE LEGALIZEBYFILE
    IS
        SBFILEPATH              CC_FILE.FILE_SYS_LOCATION%TYPE;
        SBFILENAME              CC_FILE.FILE_NAME%TYPE;
        SBOPERATING_UNIT_ID     GE_BOINSTANCECONTROL.STYSBVALUE;            
        SBINITIAL_DATE          GE_BOINSTANCECONTROL.STYSBVALUE;            
        SBFINAL_DATE            GE_BOINSTANCECONTROL.STYSBVALUE;            
        DTINITIAL               OR_ORDER.EXEC_INITIAL_DATE%TYPE;
        DTFINAL                 OR_ORDER.EXECUTION_FINAL_DATE%TYPE;
        
        
        NUCOPRIDCO              CONCPROC.COPRIDCO%TYPE;
        
        NUCOUNTFILES            CONCPROC.COPRIDCO%TYPE;
        
        SBPROCESSNAME           ESTAPROG.ESPRPROG%TYPE;
        
        SBTRACEMESSAGE          ESTAPROG.ESPRMESG%TYPE := GE_BCMESSAGE.FSBGETDESCRIPTION(800070);
        RCFILE                  ST_BOFILEMANAGER.TYRCFILESYSOBJ;
        ONUNUMLINES             UT_DATATYPES.STYNUMBERINDEX;
    BEGIN

        UT_TRACE.TRACE('INICIA OR_UIORPAP.LegalizeByFile', 9);

        
        SBFILEPATH :=  FW_BOUTILFILES.FSBGETPATHFILE;
        UT_TRACE.TRACE('sbFilePath: '||SBFILEPATH,2);

        
        SBFILENAME := GE_BOINSTANCECONTROL.FSBGETFIELDVALUE ('FILE', 'FILE0');
        UT_TRACE.TRACE('sbFileName: '||SBFILENAME||' Longitud: '||UT_STRING.FNULENGTH(SBFILENAME),2);

        SBOPERATING_UNIT_ID     := GE_BOINSTANCECONTROL.FSBGETFIELDVALUE ('OR_UNIT_BY_PERSON', 'OPERATING_UNIT_ID');
        SBINITIAL_DATE          := GE_BOINSTANCECONTROL.FSBGETFIELDVALUE ('OR_ORDER', 'EXEC_INITIAL_DATE');
        SBFINAL_DATE            := GE_BOINSTANCECONTROL.FSBGETFIELDVALUE ('OR_ORDER', 'EXECUTION_FINAL_DATE');

        DTINITIAL               := TO_DATE(SBINITIAL_DATE,UT_DATE.FSBDATE_FORMAT);
  	    DTFINAL                 := TO_DATE(SBFINAL_DATE,UT_DATE.FSBDATE_FORMAT);

        
        IF (DTFINAL > UT_DATE.FDTSYSDATE)THEN
            GE_BOERRORS.SETERRORCODE(CNUERR_FINAL_DATE);
        END IF;

        
        GE_BOUTILITIES.VALIDDATE(DTINITIAL, DTFINAL);
        
        
  	    NUCOUNTFILES  :=   OR_BOORDER.FNUONGOINGEXECUTIONS(OR_BCORDER.CSBORPAP, SBFILENAME);

  	    
        IF(NUCOUNTFILES > PKBILLCONST.CERO)THEN
            GE_BOERRORS.SETERRORCODE(CNUERR_ARCH_PROCES);
        
        ELSE
            
            OR_BOORDER.GENCONTROLPROCESS(OR_BCORDER.CSBORPAP, SBFILENAME, NUCOPRIDCO);
        END IF;

        
        CM_BOCONSLOGICSERVICE.DISABLECONPREVIEWMODE;
        
        
        RCFILE := ST_BOFILEMANAGER.FRCNEWFILESYSOBJ(SBFILEPATH||GE_BOCONSTANTS.CSBSLASH||SBFILENAME);
        
        ONUNUMLINES := ST_BOFILEMANAGER.FNUGETTXTLINESCOUNT(RCFILE);

        
        SBPROCESSNAME := PKSTATUSEXEPROGRAMMGR.FSBGETPROGRAMID(OR_BCORDER.CSBORPAP);

        
        PKSTATUSEXEPROGRAMMGR.ADDRECORDIDSESSION
        (
            SBPROCESSNAME,
            ONUNUMLINES,
            0,
            NULL,
            NULL,
            SBTRACEMESSAGE
        );
        
        
        GE_BOINSTANCECONTROL.ADDATTRIBUTE
        (
            GE_BOINSTANCECONSTANTS.CSBWORK_INSTANCE,
            NULL,
            GE_BOINSTANCECONSTANTS.CSBMES_ENTITY,
            GE_BOINSTANCECONSTANTS.CSBMES_ATTRIBUTE,
            CNUSUCCESSPROCESS
        );
        
        GE_BOINSTANCECONTROL.ADDATTRIBUTE
        (
            GE_BOINSTANCECONSTANTS.CSBWORK_INSTANCE,
            NULL,
            GE_BOINSTANCECONSTANTS.CSBMES_ARG_ENTITY,
            GE_BOINSTANCECONSTANTS.CSBMES_ARG_ATTRIBUTE,
            FM_BOINVESTIGATIONPLAN.CSBCCPRO||GE_BOCONSTANTS.CSBPIPE||SBPROCESSNAME
         );

        
        ST_BOBACKGROUNDPROCESS.INITIATEPROCESS
        (
            'RunORPAP',
            CNUTHREADS,
            SBFILEPATH,
            SBFILENAME,
            SBINITIAL_DATE,
            SBFINAL_DATE,
            SBOPERATING_UNIT_ID,
            NUCOPRIDCO,
            SBPROCESSNAME
         );
        
        PKGENERALSERVICES.COMMITTRANSACTION;
        
        UT_TRACE.TRACE('FINALIZA OR_UIORPAP.LegalizeByFile', 9);

    EXCEPTION
        WHEN EX.CONTROLLED_ERROR THEN
            UT_TRACE.TRACE('ex.CONTROLLED_ERROR OR_UIORPAP.LegalizeByFile', 9);
            PKGENERALSERVICES.ROLLBACKTRANSACTION;
            
            IF NUCOPRIDCO IS NOT NULL THEN
                OR_BOORDER.UPDPROCFINBYSESSION(NUCOPRIDCO);
            END IF;
            RAISE EX.CONTROLLED_ERROR;
        WHEN OTHERS THEN
            UT_TRACE.TRACE('others OR_UIORPAP.LegalizeByFile', 9);
            PKGENERALSERVICES.ROLLBACKTRANSACTION;
            
            IF NUCOPRIDCO IS NOT NULL THEN
                OR_BOORDER.UPDPROCFINBYSESSION(NUCOPRIDCO);
            END IF;
            ERRORS.SETERROR;
            RAISE EX.CONTROLLED_ERROR;
    END LEGALIZEBYFILE;


END OR_UIORPAP;

