CREATE TABLE PERSONALIZACIONES.LDCBI_GESTION_NO_CONVENCIONAL
(
    IdProducto        NUMBER(15),
    IdContrato        NUMBER(15),
    FechaCorte        DATE,
    IdUnidadOperativa INT,
    Recaudo           DECIMAL(38, 2),
    CREATED_DATE      DATE
)
TABLESPACE TSD_SERV;

-- Grant/Revoke object privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON PERSONALIZACIONES.LDCBI_GESTION_NO_CONVENCIONAL TO INNOVACIONBI;
GRANT SELECT, INSERT, UPDATE, DELETE ON PERSONALIZACIONES.LDCBI_GESTION_NO_CONVENCIONAL TO INNOVACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON PERSONALIZACIONES.LDCBI_GESTION_NO_CONVENCIONAL TO DATAOPS;