CREATE TABLE OPEN.LDCBI_INCOFACT (
    INFACODI       NUMBER(15)  NOT NULL,
    OPERATION      VARCHAR2(1) NOT NULL,
    PROCESS_STATUS NUMBER(3) DEFAULT -1,
    CREATED_DATE   DATE      DEFAULT SYSDATE
);

-- Create/Recreate indexes
CREATE INDEX IDX_LDCBI_INCOFACT ON OPEN.LDCBI_INCOFACT (PROCESS_STATUS, CREATED_DATE);
CREATE INDEX IDX_LDCBI_INCOFACT_PRST ON OPEN.LDCBI_INCOFACT (PROCESS_STATUS);

-- Grant/Revoke object privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON OPEN.LDCBI_INCOFACT TO INNOVACIONBI;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPEN.LDCBI_INCOFACT TO INNOVACION;
GRANT SELECT, INSERT, UPDATE, DELETE ON OPEN.LDCBI_INCOFACT TO DATAOPS;