-- Create table
CREATE TABLE OPEN.LDCBI_LDC_PAGUNIDAT (
    PAGARE_ID       NUMBER(15) NOT NULL,
    OPERATION       VARCHAR2(1) NOT NULL,
    PROCESS_STATUS  NUMBER(3) DEFAULT -1,
    CREATED_DATE    DATE DEFAULT SYSDATE
);

-- Create/Recreate indexes
CREATE index OPEN.IDX_LDCBI_LDC_PAGUNIDAT ON OPEN.LDCBI_LDC_PAGUNIDAT (PROCESS_STATUS, CREATED_DATE);
CREATE index OPEN.IDX_LDCBI_LDC_PAGUNIDAT_PRST ON OPEN.LDCBI_LDC_PAGUNIDAT (PROCESS_STATUS);

-- Grant/Revoke object privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON OPEN.LDCBI_LDC_PAGUNIDAT TO INNOVACION;