/***************************************************************************
Propiedad Intelectual de Gases del Caribe
Parametro       : TIPO_SOLICITUD_FLAG_VALIDATE  
Autor           : Paola Acosta
Fecha           : 17-12-2024
Modificaciones  :
Autor       Fecha           Caso        Descripcion
pacosta     17-12-2024      OSF-3755    Creacion
***************************************************************************/

MERGE INTO OPEN.PARAMETROS A USING
 (SELECT
  'TIPO_SOLICITUD_FLAG_VALIDATE' as CODIGO,
  'Tipos de solicitud para el atributo FLAG_VALIDATE del flujo de interacción' as DESCRIPCION,
  NULL as VALOR_NUMERICO,
  '100030' as VALOR_CADENA,
  NULL as VALOR_FECHA,
  20 as PROCESO, 
  'A' as ESTADO,
  'N' as OBLIGATORIO,
  SYSDATE as FECHA_CREACION,
  SYSDATE as FECHA_ACTUALIZACION,
  'OPEN' as USUARIO,
  'NO TERMINAL' as TERMINAL
  FROM DUAL) B
ON (A.CODIGO = B.CODIGO)
WHEN NOT MATCHED THEN 
INSERT (
  CODIGO, DESCRIPCION, VALOR_NUMERICO, VALOR_CADENA, VALOR_FECHA, 
  PROCESO, ESTADO, OBLIGATORIO, FECHA_CREACION, FECHA_ACTUALIZACION, 
  USUARIO, TERMINAL)
VALUES (
  B.CODIGO, B.DESCRIPCION, B.VALOR_NUMERICO, B.VALOR_CADENA, B.VALOR_FECHA, 
  B.PROCESO, B.ESTADO, B.OBLIGATORIO, B.FECHA_CREACION, B.FECHA_ACTUALIZACION, 
  B.USUARIO, B.TERMINAL)
WHEN MATCHED THEN
UPDATE SET 
  A.DESCRIPCION = B.DESCRIPCION,
  A.VALOR_NUMERICO = B.VALOR_NUMERICO,
  A.VALOR_CADENA = B.VALOR_CADENA,
  A.VALOR_FECHA = B.VALOR_FECHA,
  A.PROCESO = B.PROCESO,
  A.ESTADO = B.ESTADO,
  A.OBLIGATORIO = B.OBLIGATORIO,
  A.FECHA_CREACION = B.FECHA_CREACION,
  A.FECHA_ACTUALIZACION = B.FECHA_ACTUALIZACION,
  A.USUARIO = B.USUARIO,
  A.TERMINAL = B.TERMINAL;

COMMIT;
/