SELECT PEFACODI PERIODO_FACT,
       PEFACICL CICLO,
       SESUSUSC CONTRATO,
       SESUNUSE PRODUCTO,
       SESUSERV TIPO_SERV,
       SESUESCO || '- ' ||  E.ESCODESC AS  ESTADO_CORTE,
       S.SESUESFN ESTADO_FIN, 
       DIFECODI,
       DIFECONC ||' -'|| C.CONCDESC CONCEPTO,
       DIFESAPE, 
       DIFEFEIN ,
       DIFEVACU,
       DIFENUCU  - DIFECUPA AS NUM_CUOTAS_PEND
FROM PERIFACT PF 
LEFT JOIN SERVSUSC S ON PEFACICL  = SESUCICL 
LEFT JOIN ESTACORT E ON E.ESCOCODI= SESUESCO 
LEFT JOIN DIFERIDO D ON D.DIFENUSE = SESUNUSE
LEFT JOIN CONCEPTO C ON C.CONCCODI = D.DIFECONC  
WHERE EXISTS ( SELECT NULL 
              FROM PROCEJEC P2 
              WHERE P2.PREJCOPE= PF.PEFACODI  
              AND P2.PREJPROG = 'FGCC' 
              AND P2.PREJESPR ='T' )
AND EXISTS ( SELECT NULL
            FROM DIFERIDO D1
            WHERE D1.DIFECONC IN (832)
            AND D1.DIFESAPE > 0
            AND D1.DIFENUSE = SESUNUSE )
AND EXISTS ( SELECT NULL
            FROM DIFERIDO D2
            WHERE D2.DIFECONC IN (895)
            AND D2.DIFESAPE > 0
            AND D2.DIFENUSE = SESUNUSE )
AND EXISTS ( SELECT NULL
            FROM DIFERIDO D3 
            WHERE D3.DIFECONC IN (936)
            AND D3.DIFESAPE > 0
            AND D3.DIFENUSE = SESUNUSE )
AND PF.PEFAFFMO >= '01/02/2023'
AND DIFESAPE >0
AND DIFECONC IN ( 936,895,832)
ORDER BY PEFACODI DESC  ;         