CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_PR_CERTIFICATE AFTER INSERT OR UPDATE OR DELETE ON PR_CERTIFICATE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

CERTIFICATE_ID NUMBER(15);
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  CERTIFICATE_ID := :new.CERTIFICATE_ID;
  OPERATION := 'I';
ELSIF UPDATING THEN
  CERTIFICATE_ID := :new.CERTIFICATE_ID;
  OPERATION := 'U';
ELSE
  CERTIFICATE_ID := :old.CERTIFICATE_ID;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_PR_CERTIFICATE (
  CERTIFICATE_ID,
  OPERATION
)
VALUES (
  CERTIFICATE_ID,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EX.CONTROLLED_ERROR;
END;
/
