CREATE OR REPLACE TRIGGER ADM_PERSON.TRIGGER_FLAG
BEFORE UPDATE OF LDFLAGCONTABI ON LDCI_REGISTRAINTERFAZ
REFERENCING OLD AS Old NEW AS New
FOR EACH ROW
BEGIN
:New.FECHAUPDATE:=sysdate;
:New.USERUPDATE:=USER;
:New.TERMINALUPDATE:=USERENV('TERMINAL');
:New.FLAGOLD:=:Old.LDFLAGCONTABI;
END;
/
