select r.*, O.TASK_TYPE_ID
from open.or_order o, open.or_related_order r 
where o.task_type_id=11074
  and o.order_id=r.order_id
START WITH R.ORDER_ID=  o.order_id
CONNECT BY  R.ORDER_ID= PRIOR R.RELATED_ORDER_ID;

  ;

SELECT  R.ORDER_ID ORDEN_PADRE, O.ORDER_ID ORDEN_HIJA, O.TASK_TYPE_ID, O.CREATED_DATE, O.ORDER_STATUS_ID, O.OPERATING_UNIT_ID, LEVEL
FROM   OPEN.OR_RELATED_ORDER R, OPEN.OR_ORDER O
WHERE O.ORDER_ID=R.RELATED_ORDER_ID
START WITH R.ORDER_ID IN (SELECT OT.ORDER_ID FROM OPEN.OR_ORDER OT WHERE OT.TASK_TYPE_ID=11074)
CONNECT BY  R.ORDER_ID= PRIOR R.RELATED_ORDER_ID;



SELECT  R.ORDER_ID ORDEN_PADRE, O.ORDER_ID ORDEN_HIJA, O.TASK_TYPE_ID, O.CREATED_DATE, O.ORDER_STATUS_ID, O.OPERATING_UNIT_ID, LEVEL
FROM   OPEN.OR_RELATED_ORDER R, OPEN.OR_ORDER O

WHERE O.ORDER_ID=R.RELATED_ORDER_ID
START WITH R.ORDER_ID IN (SELECT OT.ORDER_ID FROM OPEN.OR_ORDER OT WHERE OT.TASK_TYPE_ID=11074)
CONNECT by nocycle prior R.ORDER_ID=  R.RELATED_ORDER_ID
;

--142153830

WITH DISENO AS (SELECT O.ORDER_ID PADRE, O.ORDER_ID, O.OPERATING_UNIT_ID, O.TASK_TYPE_ID, O.CREATED_DATE, O.ORDER_STATUS_ID, A.COMMENT_, O.CAUSAL_ID FROM OPEN.OR_ORDER O INNER JOIN OPEN.OR_ORDER_ACTIVITY A ON A.ORDER_ID=O.ORDER_ID WHERE O.TASK_TYPE_ID=11074 AND A.TASK_TYPE_ID=11074)
,
APROBACION AS(
SELECT DISENO.ORDER_ID PADRE, O2.ORDER_ID, O2.OPERATING_UNIT_ID, O2.TASK_TYPE_ID, O2.CREATED_DATE, O2.ORDER_STATUS_ID, NULL COMMENT_, O2.CAUSAL_ID
              FROM DISENO, OR_RELATED_ORDER R, OPEN.OR_ORDER O2
              WHERE O2.ORDER_ID=R.RELATED_ORDER_ID
              START WITH R.ORDER_ID=DISENO.PADRE
              CONNECT BY  R.ORDER_ID= PRIOR R.RELATED_ORDER_ID)
,
TODOS AS (
SELECT *
FROM DISENO
UNION ALL
SELECT *
FROM APROBACION)
SELECT DISTINCT T.PADRE AGRUPACION,
       T.ORDER_ID ORDEN,
       T.TASK_TYPE_ID||'-'||OPEN.DAOR_TASK_TYPE.FSBGETDESCRIPTION(T.TASK_TYPE_ID, NULL) TIPO_TRABAJO,
       T.OPERATING_UNIT_ID||'-'||OPEN.DAOR_OPERATING_UNIT.FSBGETNAME(T.OPERATING_UNIT_ID, NULL) UNIDAD,
       T.ORDER_STATUS_ID||'-'||OPEN.DAOR_ORDER_STATUS.FSBGETDESCRIPTION(T.ORDER_STATUS_ID,null) estado,
       T.CREATED_DATE FECHA_CREACION,
       T.CAUSAL_ID||'-'||OPEN.DAGE_CAUSAL.FSBGETDESCRIPTION(T.CAUSAL_ID, NULL) CAUSAL,
       T.COMMENT_ "Comentario Generacion Diseño",
       (SELECT  C.ORDER_COMMENT FROM OPEN.OR_ORDER_COMMENT C WHERE C.ORDER_ID=T.ORDER_ID AND C.LEGALIZE_COMMENT='Y' AND ROWNUM=1) COMENTARIO_LEGALIZACION
FROM TODOS T
ORDER BY  2
      
;




WITH DISENO AS (SELECT O.ORDER_ID PADRE, O.ORDER_ID, O.OPERATING_UNIT_ID, O.TASK_TYPE_ID, O.CREATED_DATE, O.ORDER_STATUS_ID, A.COMMENT_, O.CAUSAL_ID FROM OPEN.OR_ORDER O INNER JOIN OPEN.OR_ORDER_ACTIVITY A ON A.ORDER_ID=O.ORDER_ID WHERE O.TASK_TYPE_ID=11074 AND A.TASK_TYPE_ID=11074)
SELECT DISENO.ORDER_ID PADRE, O2.ORDER_ID, O2.OPERATING_UNIT_ID, O2.TASK_TYPE_ID, O2.CREATED_DATE, O2.ORDER_STATUS_ID, NULL COMMENT_, O2.CAUSAL_ID, LEVEL
              FROM DISENO, OR_RELATED_ORDER R, OPEN.OR_ORDER O2
              WHERE O2.ORDER_ID=R.RELATED_ORDER_ID
              START WITH R.ORDER_ID=DISENO.PADRE
              CONNECT BY  R.ORDER_ID= PRIOR R.RELATED_ORDER_ID
              
              
              
WITH DISENO AS (SELECT O.ORDER_ID PADRE, O.ORDER_ID, O.OPERATING_UNIT_ID, O.TASK_TYPE_ID, O.CREATED_DATE, O.ORDER_STATUS_ID, A.COMMENT_, O.CAUSAL_ID FROM OPEN.OR_ORDER O INNER JOIN OPEN.OR_ORDER_ACTIVITY A ON A.ORDER_ID=O.ORDER_ID WHERE O.TASK_TYPE_ID=11074 AND A.TASK_TYPE_ID=11074)
,
APROBACION AS(
SELECT DISENO.ORDER_ID PADRE, O2.ORDER_ID, O2.OPERATING_UNIT_ID, O2.TASK_TYPE_ID, O2.CREATED_DATE, O2.ORDER_STATUS_ID, NULL COMMENT_, O2.CAUSAL_ID
              FROM DISENO, OPEN.OR_ORDER O2
              WHERE O2.TASK_TYPE_ID IN (11075,11076,11077)
                AND (SELECT min(r.order_id)
                    FROM OPEN.OR_RELATED_ORDER R
                    START WITH R.RELATED_ORDER_ID=o2.ORDER_ID
              CONNECT BY PRIOR R.ORDER_ID=  R.RELATED_ORDER_ID)=DISENO.ORDER_ID
              )
,
TODOS AS (
SELECT *
FROM DISENO
UNION ALL
SELECT *
FROM APROBACION)
SELECT DISTINCT T.PADRE AGRUPACION,
       T.ORDER_ID ORDEN,
       T.TASK_TYPE_ID||'-'||OPEN.DAOR_TASK_TYPE.FSBGETDESCRIPTION(T.TASK_TYPE_ID, NULL) TIPO_TRABAJO,
       T.OPERATING_UNIT_ID||'-'||OPEN.DAOR_OPERATING_UNIT.FSBGETNAME(T.OPERATING_UNIT_ID, NULL) UNIDAD,
       T.ORDER_STATUS_ID||'-'||OPEN.DAOR_ORDER_STATUS.FSBGETDESCRIPTION(T.ORDER_STATUS_ID,null) estado,
       T.CREATED_DATE FECHA_CREACION,
       T.CAUSAL_ID||'-'||OPEN.DAGE_CAUSAL.FSBGETDESCRIPTION(T.CAUSAL_ID, NULL) CAUSAL,
       T.COMMENT_ "Comentario Generacion Diseño",
       (SELECT  C.ORDER_COMMENT FROM OPEN.OR_ORDER_COMMENT C WHERE C.ORDER_ID=T.ORDER_ID AND C.LEGALIZE_COMMENT='Y' AND ROWNUM=1) COMENTARIO_LEGALIZACION
FROM TODOS T
ORDER BY  2
      
;              


