SELECT /*+ ordered index(or_order IDX_OR_ORDER21)
                       index(ge_causal PK_GE_CAUSAL) */
 OR_ORDER.order_id --'X'
  FROM open.OR_ORDER, open.GE_CAUSAL
 WHERE DEFINED_CONTRACT_ID = 10641 --INUCONTRACTID
   AND IS_PENDING_LIQ IN ('Y', 'E')
   AND OR_ORDER.CAUSAL_ID = GE_CAUSAL.CAUSAL_ID
   AND GE_CAUSAL.CLASS_CAUSAL_ID = 1 --CNUSUCCESSFULLCLASSCAUSAL
   AND ORDER_STATUS_ID = 8 --OR_BOCONSTANTS.CNUORDER_STAT_CLOSED
UNION
SELECT OR_ORDER.order_id -- 'X'
  FROM open.OR_ORDER
 WHERE DEFINED_CONTRACT_ID = 10641 --INUCONTRACTID
   AND (ORDER_STATUS_ID < 8 /*OR_BOCONSTANTS.CNUORDER_STAT_CLOSED*/
       OR ORDER_STATUS_ID = 11 /*OR_BOCONSTANTS.CNUORDER_STAT_LOCK*/
       );
