SELECT SA_EXECUTABLE.EXECUTABLE_ID,
       SA_EXECUTABLE.NAME,
       GE_ENTITY.ENTITY_ID,
       GE_ENTITY.NAME_,
       GE_ENTITY.DESCRIPTION,
       GE_ENTITY.DISPLAY_NAME
  FROM OPEN.GI_ENTITY_DISP_DATA,
       OPEN.GE_ENTITY,
       OPEN.SA_EXECUTABLE
 WHERE GE_ENTITY.ENTITY_ID = GI_ENTITY_DISP_DATA.ENTITY_ID
   AND GI_ENTITY_DISP_DATA.EXECUTABLE_ID = SA_EXECUTABLE.EXECUTABLE_ID
   AND upper(GE_ENTITY.NAME_) = upper('LDC_PERFIL_ABONO_PROD');
