WITH solicitud AS
 (select mm.package_id
    from open.mo_motive mm, OPEN.MO_DATA_FOR_ORDER a
   where mm.motive_id = a.motive_id
     and a.item_id = 4294830)
SELECT 'MOPRP' FORMA,
       P.PACKAGE_ID,
       P.MOTIVE_STATUS_ID,
       P.PACKAGE_TYPE_ID,
       P.REQUEST_DATE,
       EL.MESSAGE,
       NULL,
       EL.date_
  FROM OPEN.MO_EXECUTOR_LOG_MOT LM,
       OPEN.GE_EXECUTOR_LOG     EL,
       OPEN.MO_PACKAGES         P,
       solicitud                s
 WHERE LM.EXECUTOR_LOG_ID = EL.EXECUTOR_LOG_ID
   AND P.PACKAGE_ID = LM.PACKAGE_ID
   AND LM.STATUS_EXEC_LOG_ID = 4
   AND P.PACKAGE_TYPE_ID = 100101
   and p.motive_status_id = 13
   AND P.PACKAGE_ID = s.package_id
UNION ALL
SELECT 'MOPWP' FORMA,
       P.PACKAGE_ID,
       P.MOTIVE_STATUS_ID,
       P.PACKAGE_TYPE_ID,
       P.REQUEST_DATE,
       EL.MESSAGE,
       NULL,
       EL.date_
  FROM OPEN.MO_WF_PACK_INTERFAC LM,
       OPEN.GE_EXECUTOR_LOG     EL,
       OPEN.MO_PACKAGES         P,
       solicitud                s
 WHERE LM.EXECUTOR_LOG_ID = EL.EXECUTOR_LOG_ID AND
 P.PACKAGE_ID = LM.PACKAGE_ID AND LM.STATUS_ACTIVITY_ID = 4 and
 p.motive_status_id = 13 AND P.PACKAGE_TYPE_ID = 100101 AND
 P.PACKAGE_ID = s.package_id
UNION ALL
SELECT 'MOPWM' FORMA,
       P.PACKAGE_ID,
       P.MOTIVE_STATUS_ID,
       P.PACKAGE_TYPE_ID,
       P.REQUEST_DATE,
       EL.MESSAGE,
       NULL,
       EL.date_
  FROM OPEN.MO_WF_MOTIV_INTERFAC LM,
       OPEN.GE_EXECUTOR_LOG      EL,
       OPEN.MO_PACKAGES          P,
       OPEN.MO_MOTIVE            M,
       solicitud                 s
 WHERE LM.EXECUTOR_LOG_ID = EL.EXECUTOR_LOG_ID AND
 P.PACKAGE_ID = M.PACKAGE_ID AND M.MOTIVE_ID = LM.MOTIVE_ID and
 p.motive_status_id = 13 AND P.PACKAGE_TYPE_ID = 100101 AND
 P.PACKAGE_ID = s.package_id
UNION ALL
SELECT 'MOPWC' FORMA,
       P.PACKAGE_ID,
       P.MOTIVE_STATUS_ID,
       P.PACKAGE_TYPE_ID,
       P.REQUEST_DATE,
       EL.MESSAGE,
       NULL,
       EL.date_
  FROM OPEN.MO_WF_COMP_INTERFAC LM,
       OPEN.GE_EXECUTOR_LOG     EL,
       OPEN.MO_PACKAGES         P,
       OPEN.MO_COMPONENT        C,
       solicitud                s
 WHERE LM.EXECUTOR_LOG_ID = EL.EXECUTOR_LOG_ID AND
 P.PACKAGE_ID = C.PACKAGE_ID AND C.COMPONENT_ID = LM.COMPONENT_ID AND
 LM.STATUS_ACTIVITY_ID = 4 and p.motive_status_id = 13 AND
 P.PACKAGE_TYPE_ID = 100101 AND P.PACKAGE_ID = s.package_id
UNION ALL
SELECT 'INRMO/WFEWF' FORMA,
       P.PACKAGE_ID,
       P.MOTIVE_STATUS_ID,
       P.PACKAGE_TYPE_ID,
       P.REQUEST_DATE,
       EL.MESSAGE_DESC,
       WF.INSTANCE_ID,
       EL.LOG_DATE
  FROM OPEN.WF_INSTANCE      WF,
       OPEN.WF_EXCEPTION_LOG EL,
       OPEN.MO_PACKAGES      P,
       OPEN.WF_DATA_EXTERNAL DE,
       solicitud             s
 WHERE WF.INSTANCE_ID = EL.INSTANCE_ID AND DE.PLAN_ID = WF.PLAN_ID AND
 DE.PACKAGE_ID = P.PACKAGE_ID AND WF.STATUS_ID = 9 AND EL.STATUS = 1 and
 p.motive_status_id = 13 AND P.PACKAGE_TYPE_ID = 100101 AND
 P.PACKAGE_ID = s.package_id
UNION ALL
SELECT 'INRMO' FORMA,
       P.PACKAGE_ID,
       P.MOTIVE_STATUS_ID,
       P.PACKAGE_TYPE_ID,
       P.REQUEST_DATE,
       LAST_MESS_DESC_ERROR,
       W.INSTANCE_ID,
       I.INSERTING_DATE
  FROM OPEN.IN_INTERFACE_HISTORY I,
       OPEN.WF_INSTANCE          W,
       OPEN.MO_PACKAGES          P,
       OPEN.WF_DATA_EXTERNAL     DE,
       solicitud                 s
 WHERE I.STATUS_ID = 9 AND I.REQUEST_NUMBER_ORIGI = W.INSTANCE_ID AND
 DE.PLAN_ID = W.PLAN_ID AND DE.PACKAGE_ID = P.PACKAGE_ID and
 p.motive_status_id = 13 AND P.PACKAGE_TYPE_ID = 100101 AND
 P.PACKAGE_ID = s.package_id
 ORDER BY REQUEST_DATE
