select s.Tab_Name, S.PROCESS_NAME, S.APLICA_EXECUTABLE, SE.*
  from open.sa_tab s, SA_EXECUTABLE SE
 where 1 = 1
   or s.tab_name like '%P_CAMBIO_TITULAR_PORTAL_WEB_100293%'
   or s.process_name like '%P_CAMBIO_TITULAR_PORTAL_WEB_100293%'
   or s.aplica_executable like '%P_CAMBIO_TITULAR_PORTAL_WEB_100293%'
   AND SE.NAME = S.PROCESS_NAME;

select s.*
  from open.sa_tab s
 where s.tab_name like '%P_CAMBIO_TITULAR_PORTAL_WEB_100293%'
    or s.process_name like '%P_CAMBIO_TITULAR_PORTAL_WEB_100293%'
    or s.aplica_executable like '%P_CAMBIO_TITULAR_PORTAL_WEB_100293%'
--AND S.APLICA_EXECUTABLE = 'CNCRM';   

--AND S.APLICA_EXECUTABLE = 'CNCRM';
--:PACKAGE_STATUS: = '13 - REGISTRADO' AND LDC_BOORDENES.FNUCONTROLVISUALANULSOLI(:PACKAGE_TYPE:) IN (1,2,3) AND LDC_BCSALESCOMMISSION.fnuGetPackagesVR(:PACKAGE_ID:)=:PACKAGE_ID:
--:PACKAGE_STATUS: = '13 - REGISTRADO' select LDC_BOORDENES.FNUCONTROLVISUALANULSOLI(213260380) c1, LDC_BCSALESCOMMISSION.fnuGetPackagesVR(213260380) c2from dual --=:PACKAGE_ID:

--INSERT INTO SA_TAB VALUES (SEQ_SA_TAB.NEXTVAL, 'REQUEST', 'PBTEMP', 'CNCRM', NULL, NULL, 0, NULL, NULL);
--1 345681  INFO_VIGENCIAS_EXENCION PBTEMP  CNCRM     0     ACcZXOAA+AAAAmkAAA
