MERGE INTO OPEN.LD_PARAMETER A USING
 (SELECT
  'TRG_RESTRICT_LEGALIZA_SERVNUEV' as "PARAMETER_ID",
  1 as "NUMERIC_VALUE",
  null as "VALUE_CHAIN",
  'ENTREGA ACTIVA=1 INACTIVA=0 CASO SN-603' as "DESCRIPTION"
  FROM DUAL) B
ON (A.PARAMETER_ID = B.PARAMETER_ID)
WHEN NOT MATCHED THEN 
INSERT (
  PARAMETER_ID, NUMERIC_VALUE, VALUE_CHAIN, DESCRIPTION)
VALUES (
  B.PARAMETER_ID, B.NUMERIC_VALUE, B.VALUE_CHAIN, B.DESCRIPTION)
WHEN MATCHED THEN
UPDATE SET 
  A.NUMERIC_VALUE = B.NUMERIC_VALUE,
  A.VALUE_CHAIN = B.VALUE_CHAIN,
  A.DESCRIPTION = B.DESCRIPTION;
/
COMMIT;
/