DECLARE
 nuTab1 number := 0;
BEGIN

 SELECT COUNT(*) INTO nuTab1
 FROM DBA_TABLES
 WHERE TABLE_NAME = 'LDC_GRUPVIFA';

 if nuTab1 = 0 then
	execute IMMEDIATE 'CREATE TABLE LDC_GRUPVIFA( GRUPCODI NUMBER(15) NOT NULL,
                            GRUPDESC VARCHAR2(400) NOT NULL)';
	execute IMMEDIATE 'ALTER TABLE LDC_GRUPVIFA ADD CONSTRAINTS PK_GRUPVIFA PRIMARY KEY (GRUPCODI)';
	execute IMMEDIATE 'COMMENT ON COLUMN LDC_GRUPVIFA.GRUPCODI IS ''CODIGO DEL GRUPO''';
	execute IMMEDIATE 'COMMENT ON COLUMN LDC_GRUPVIFA.GRUPDESC IS ''DESCRIPCION DEL GRUPO''';
	execute IMMEDIATE 'COMMENT ON TABLE LDC_GRUPVIFA IS ''GRUPO DE VISUALIZACION DE FACTURAS''';
	
	EXECUTE immediate 'grant select, insert, delete, update on LDC_GRUPVIFA to SYSTEM_OBJ_PRIVS_ROLE';
	execute immediate 'grant select on LDC_GRUPVIFA to RSELOPEN';
	execute immediate 'grant select on LDC_GRUPVIFA to reportes';

  end if;
end;
/