CREATE OR REPLACE TRIGGER ADM_PERSON.TRG_BI_SUSPCONE AFTER INSERT OR UPDATE OR DELETE ON SUSPCONE
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW

DECLARE

SUCOIDSC NUMBER(15);
OPERATION VARCHAR2(1);

BEGIN

IF INSERTING THEN
  SUCOIDSC := :new.SUCOIDSC;
  OPERATION := 'I';
ELSIF UPDATING THEN
  SUCOIDSC := :new.SUCOIDSC;
  OPERATION := 'U';
ELSE
  SUCOIDSC := :old.SUCOIDSC;
  OPERATION := 'D';
END IF;

INSERT INTO LDCBI_SUSPCONE (
  SUCOIDSC,
  OPERATION
)
VALUES (
  SUCOIDSC,
  OPERATION
);

EXCEPTION
  WHEN OTHERS THEN
    RAISE EX.CONTROLLED_ERROR;
END;
/
