PROMPT Crea sinonimo objeto dependiente LDCI_PROUPDOBSTATUSCERTOIAWS
BEGIN
    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM LDCI_PROUPDOBSTATUSCERTOIAWS FOR ADM_PERSON.LDCI_PROUPDOBSTATUSCERTOIAWS';
END;
/
