DECLARE
    nuContador  NUMBER;
BEGIN

    SELECT  COUNT(1) 
    INTO    nuContador
    FROM 	OR_ACT_BY_REQ_DATA
    WHERE   item_id = 100009983;
	
	IF (nuContador = 0) THEN
  
		INSERT INTO OR_ACT_BY_REQ_DATA(ACT_BY_REQ_DATA_ID, PRODUCT_TYPE_ID, MOTIVE_TYPE_ID, COMPONENT_TYPE_ID, TECHNOLOGY_TYPE_ID, CONFIG_EXPRESSION_ID, 
								ITEM_ID, SEQUENCE_, ACTIVE, WF_TAG_NAME, CLASS_SERVICE_ID, ACTION_ID) 
            VALUES(SEQ_OR_ACT_BY_REQ_DATA.NEXTVAL, 7014, 9, 7038, NULL, 121394520, 100009983, 0, 'Y', NULL, NULL, NULL);
				
		COMMIT;
	END IF;
END;
/