DECLARE
  nuConta NUMBER;
BEGIN
SELECT COUNT(1) INTO nuConta
  FROM DBA_OBJECTS
  WHERE OBJECT_NAME = 'LDC_PKCM_LECTESP4'
   AND OWNER = 'OPEN'
   AND OBJECT_TYPE='PACKAGE';

  IF nuConta >= 1 THEN
      EXECUTE IMMEDIATE 'DROP PACKAGE OPEN.LDC_PKCM_LECTESP4';
  END IF;
END;
/
